event_api_happening_list:
    path: /api/happenings
    methods: [GET]
    controller: Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Api\Happening\ListAction

event_api_happening_list_options:
    path: /api/happenings
    methods: [OPTIONS]
    controller: Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Api\OptionsAction
