#
# Event home
#

event:
    path: /
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Home:index }

#
# Register
#

event_register:
    path: /register/{typeView}
    methods:  [GET, POST]
    requirements:
        typeView: \d+
    defaults: { _controller: EventBundle:Register:register }

event_register_new_user:
    path: /register/{typeView}/new
    methods:  [GET, POST]
    requirements:
        typeView: \d+
    defaults: { _controller: EventBundle:Register:registerNewUser }

#
# Change mail
#
event_account:
    path: /account
    methods: [GET, POST]
    defaults: { _controller: EventBundle:Account:update }

event_activate_new_mail:
    path: /account/change_mail/{token}
    methods: [GET]
    requirements:
        token: \w+
    defaults: { _controller: EventBundle:Account:activateNewMail }

#
# Forgot password
#

event_forgotten_password:
    path: /forgotten_password
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:ForgottenPassword:forgottenPassword }

event_create_new_password:
    path: /reset_password/{token}
    methods:  [GET, POST]
    requirements:
        token: \w+
    defaults: { _controller: EventBundle:ForgottenPassword:createNewPassword }

#
# Activate account
#

event_activate_account:
    path: /activate/{token}
    methods: [GET, POST]
    requirements:
        token: \w+
    defaults: { _controller: EventBundle:ActivateAccount:password }

#
# Join event
#

event_participate:
    path: /participate/{typeView}
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Register:participate }

#
# Sheet
#

event_sheet:
    path:     /fiche-de-presentation
    methods:  [GET]
    defaults: { _controller: EventBundle:Sheet:sheet }

event_sheet_locale:
    path:     /fiche-de-presentation/{locale}
    requirements:
        locale: '[a-z]{2}'
    methods:  [GET]
    defaults: { _controller: EventBundle:Sheet:sheet }

event_sheet_update:
    path:     /fiche-de-presentation/{locale}/update/{key}
    requirements:
        locale: '[a-z]{2}'
        key: \w+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Sheet:update }
event_sheet_object:
    path:     /fiche-de-presentation/{sheet}/{locale}/object/{key}
    requirements:
        locale: '[a-z]{2}'
        key: \w+
    methods:  [GET]
    defaults: { _controller: EventBundle:Sheet:object }

#
# Sheet - Participant
#

event_sheet_add_participant:
    path:     /sheet/{sheet}/add_participant
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Participant:add }

event_sheet_update_participant:
    path:     /sheet/{sheet}/update_participant/{participant}
    requirements:
        sheet: \d+
        participant: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Participant:update }

event_sheet_delete_participant:
    path:     /sheet/{sheet}/delete_participant/{participant}
    requirements:
        sheet: \d+
        participant: \d+
    methods:  [DELETE]
    defaults: { _controller: EventBundle:Participant:delete }

#
# Sheet - Package
#

event_sheet_package_update_step:
    path:     /sheet/{sheet}/update_step/{step}
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Package:updateStep }

event_sheet_package_products:
    path: /sheet/{sheet}/products/add
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Package:addProducts }

event_sheet_product_update:
    path: /sheet/{sheet}/products/update/{groupId}/{rowId}
    requirements:
        sheet: \w+
        groupId: \w+
        rowId: \w+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Package:updateProduct }

event_sheet_package_cart:
    path:     /sheet/{sheet}/cart
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Package:cart }

#
# Sheet Billing
#

event_sheet_billing:
    path:     /sheet/{sheet}/billing
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Billing:billing }

event_sheet_package_payment_mode:
    path:     /sheet/{sheet}/payment_mode
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Billing:paymentMode }

#
# Sheet - Order
#

event_sheet_list_orders:
    path:     /sheet/{sheet}/orders
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Order:listOrder }

event_sheet_summary:
    path:      /sheet/{sheet}/summary
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Order:summary }

event_sheet_order_pro_forma:
    path:     /sheet/{sheet}/pro_forma/{order}
    requirements:
        sheet: \d+
        order: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Order:proforma }

#
# Authentication
#

event_login:
    path:     /login
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Security:loginFirstStep }

event_login_second_step:
    path:     /login-second-step
    methods:  [GET]
    defaults: { _controller: EventBundle:Security:loginSecondStep }

event_login_check:
    path:     /login_check
    methods:  [POST]

event_logout_confirmation:
    path:     /logout-confirmation
    methods:  [GET]
    defaults: { _controller: EventBundle:Security:logoutConfirmation }

event_logout:
    path:     /logout
    methods:  [GET]

event_change_password:
    path:     /change-password
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:ChangePassword:changePassword }

#
# Catalog
#

event_catalog:
    path: /catalog
    methods:  [GET]
    defaults: { _controller: EventBundle:Catalog:categories }

event_catalog_category:
    path: /catalog/{categoryView}
    requirements:
        categoryView: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Catalog:category }

event_catalog_sheet:
    path: /catalog/{categoryView}/sheet/{sheet}
    requirements:
        categoryView: \d+
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Catalog:sheet }

event_catalog_sheet_meeting_request:
    path: /catalog/{categoryView}/sheet/{to}/meeting/request/from/{from}
    requirements:
        categoryView: \d+
        to: \d+
        from: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:MeetingRequest:createRequest }

#
# Schedule
#

event_sheet_schedule:
    path: /sheet/{sheet}/schedule
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Schedule:display }

event_sheet_schedule_add_unavailability:
    path: /sheet/{sheet}/schedule/unavailability/add
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Schedule:addUnavailability }

event_sheet_schedule_update_unavailability:
    path: /sheet/{sheet}/schedule/unavailability/{unavailability}/update
    requirements:
        sheet: \d+
        unavailability: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Schedule:updateUnavailability }

event_sheet_schedule_remove_unavailability:
    path: /sheet/{sheet}/schedule/unavailability/{unavailability}/remove
    requirements:
        sheet: \d+
        unavailability: \d+
    methods:  [DELETE]
    defaults: { _controller: EventBundle:Schedule:removeUnavailability }

event_sheet_schedule_participate_happening:
    path: /sheet/{sheet}/happening/{happening}/participate
    requirements:
        sheet: \d+
        happening: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Schedule:participateHappening }

event_sheet_schedule_unparticipate_happening:
    path: /sheet/{sheet}/happening/{happening}/unparticipate/{participant}
    requirements:
        sheet: \d+
        happening: \d+
        participant: \d+
    methods:  [POST]
    defaults: { _controller: EventBundle:Schedule:unparticipateHappening }

#
# Meeting
#

event_sheet_schedule_meeting:
    path: /sheet/{sheet}/meeting/{meeting}
    requirements:
        sheet: \d+
        meeting: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Meeting:display }

event_sheet_schedule_meeting_cancel:
    path: /sheet/{sheet}/meeting/{meeting}/cancel
    requirements:
        sheet: \d+
        meeting: \d+
    methods:  [GET, DELETE]
    defaults: { _controller: EventBundle:Meeting:cancel }

event_sheet_schedule_meeting_update:
    path: /sheet/{sheet}/meeting/{meeting}/update
    requirements:
        sheet: \d+
        meeting: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:Meeting:update }

#
# Meeting Request
#
event_meeting_list_request:
    path: /sheet/{sheet}/meeting/request
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:MeetingRequest:listRequest }

event_meeting_list_proposition:
    path: /sheet/{sheet}/meeting/proposition
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:MeetingRequest:listProposition }

event_meeting_request_approve:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/approve
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:MeetingRequest:approveRequest }

event_meeting_request_refuse:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/refuse
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:MeetingRequest:refuseRequest }

event_meeting_request_cancel:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/cancel
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:MeetingRequest:cancelRequest }

event_meeting_request_show:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:MeetingRequest:showRequest }

event_meeting_request_edit:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/edit
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: EventBundle:MeetingRequest:editRequest }

#
# Notification
#
event_notification_list:
    path:     /notification
    methods:  [GET]
    defaults: { _controller: EventBundle:Notification:list }
event_notification_read:
    path:     /notification/{notification}/read
    requirements:
        notification: \d+
    methods:  [GET]
    defaults: { _controller: EventBundle:Notification:read }
