Proximum\Vimeet\Domain\Template\Object\EditableText:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\Object\EditableTextConstraint:
            isInBlock: false
