Proximum\Vimeet\Domain\Template\TemplateObject\EditableText:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\TemplateObject\EditableTextConstraint:
            isInBlock: false
