Proximum\Vimeet\Domain\Template\TemplateObject\Item:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\TemplateObject\ItemConstraint: ~
