Proximum\Vimeet\Domain\Template\TemplateObject\MediaCollection:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\TemplateObject\MediaCollectionConstraint: ~
