Proximum\Vimeet\Domain\Template\TemplateObject\MultiUploadCollectionObject:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\TemplateObject\MultiUploadCollectionObjectConstraint: ~
