Proximum\Vimeet\Application\Command\Register\RegisterNewUser:
    properties:
        password:
            - NotBlank:
                message: validators.required.password
            - Length:
                min: 8
                minMessage: validators.password.min
