Proximum\Vimeet\Application\Command\Transactional\Mail\Customize:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        subject:
                            - NotBlank: ~
                        content:
                            - NotBlank: ~
    constraints:
        - Expression:
              expression: "this.hasNoAssociatedTypesConflict()"
              message: "validators.transactional.mail.typeNotEmpty"
