Proximum\Vimeet\Application\Command\Rooming\Accommodation\AbstractAccommodationCommand:
    properties:
        title:
            - NotBlank: ~
        overnightCapacities:
            - Valid: ~
            - Expression:
                expression: "!this.hasDuplicatedDay()"
                message: "validators.accommodation.noDuplicatedDayAllowed"
