Proximum\Vimeet\Application\Command\Event\Day\Update:
    properties:
        days:
            - All:
                - Collection:
                    startTime:
                        - NotNull: ~
                        - Type: { type: datetime }
                    endTime:
                        - NotNull: ~
                        - Type: { type: datetime }
                - Expression:
                    expression: "value['startTime'] < value['endTime']"
                    message: "validators.schedule_day.startTimeMustBeBeforeEndTime"
                - Expression:
                    expression: "value['startTime'].format('DD/MM/YYYY') === value['endTime'].format('DD/MM/YYYY')"
                    message: "validators.schedule_day.shouldBeTheSameDay"
