Proximum\Vimeet\Application\Command\Event\Design\UpdateDesign:
    properties:
        textColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        leftColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        headerLeftColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        rightColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        headerRightColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        localizedImages:
            - All:
                - Collection:
                    fields:
                        logo:
                            - Image:
                                mimeTypes: !php/const:Proximum\Vimeet\Domain\Event\Image::SUPPORTED_MIME_TYPE
                        mobileLogo:
                            - Image:
                                mimeTypes: !php/const:Proximum\Vimeet\Domain\Event\Image::SUPPORTED_MIME_TYPE
        backgroundColor:
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        backgroundImage:
            - Image:
                mimeTypes: !php/const:Proximum\Vimeet\Domain\Event\Image::SUPPORTED_MIME_TYPE
