Proximum\Vimeet\Application\Command\Schedule\Configure:
    properties:
        event:
            - NotBlank: ~
        hasMessage:
            - NotNull: ~
        scale:
            - NotBlank: ~
            - Type: { type: integer }
            - Range: { min: 1 }
