framework:
    messenger:
        failure_transport: job_failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            job_async:
                dsn: '%env(resolve:JOB_MESSENGER_TRANSPORT_DSN)%'
                options:
                    table_name: 'messenger_jobs'
                    auto_setup: false
            job_async_low:
                dsn: '%env(resolve:JOB_MESSENGER_TRANSPORT_DSN)%?queue_name=low_priority'
                options:
                    table_name: 'messenger_jobs'
                    auto_setup: false

            job_failed:
                dsn: '%env(resolve:JOB_MESSENGER_TRANSPORT_DSN)%?queue_name=job_failed'
                options:
                    table_name: 'messenger_jobs'
                    auto_setup: false
        routing:
            # Route your messages to the transports
            'Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Adapter\BatchJobQueue\Message\Job': job_async
            'Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Adapter\BatchJobQueue\Message\LongJob': job_async_low
