swiftmailer:
    # TODO: update deployement files to use env variable
    # url: '%env(MAILER_URL)%'
    default_mailer: default
    mailers:
        default:
            transport:  "%mailer_transport%"
            host:       "%mailer_host%"
            username:   "%mailer_user%"
            password:   "%mailer_password%"
            port:       "%mailer_port%"
            encryption: "%mailer_encryption%"
            # spool must NOT be activated, else closing smtp connexion won't be supported
        error:
            transport:  "%mailer_error_transport%"
            host:       "%mailer_error_host%"
            username:   "%mailer_error_user%"
            password:   "%mailer_error_password%"
            port:       "%mailer_error_port%"
            encryption: "%mailer_error_encryption%"
