Proximum\Vimeet\Application\Command\User\Event\AuthenticationTokenImport:
    properties:
        file:
            - NotNull: ~
            - File:
                mimeTypes: ['text/csv', 'text/plain', 'application/csv']
