rules:
    twig.template_too_complex:
        enabled: true
        max_depth: 30
    symfony.controller.action_method_too_long:
        enabled: true
        max_length: 20
        threshold: 12
    symfony.controller.too_many_template_variables:
        enabled: true
        max_count: 8
        threshold: 10
