rules:
    twig.template_too_complex:
        enabled: true
        max_depth: 45
    symfony.controller.action_method_too_long:
        enabled: true
        max_length: 20
        threshold: 15
    symfony.controller.too_many_template_variables:
        enabled: true
        max_count: 8
        threshold: 10

global_exclude_dirs:
    - vendor
    - tests
    - features
    - DataFixtures
    - var
    - src/Behat
