version: "3"

networks:
    proxy:
        external:
            name: proxy

volumes:
    db_data: ~
    logs: ~

services:
    database:
        image: mysql:5.6
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: proximum_vimeet
            MYSQL_USER: app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - proxy

    elasticsearch:
        image: elasticsearch:1.7
        ports:
            - "9200:9200"
        networks:
            - proxy

    nginx:
        build: docker/nginx
        volumes:
            - .:/srv
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - proxy

    php:
        build: docker/php
        networks:
            - proxy
        volumes:
            - .:/srv
