Proximum\Vimeet\Application\Command\Package\Update:
    properties:
        package:
            - NotBlank: ~
        title:
            - NotBlank: ~
        participantAndPlanning:
            - Valid: ~
        options:
            - Valid: ~
