---

# create a directory if it doesn't exist
- file:
    path: "{{ certificate_path }}/{{ certificate_domain }}"
    state: directory
    mode: 0755

- name: Generate certificate
  args:
    chdir: "{{ certificate_path }}/{{ certificate_domain }}"
    creates: "{{ certificate_path }}/{{ certificate_domain }}/cert.pem"
  command: |
    openssl req \
      -newkey rsa:2048 -nodes -keyout ./privkey.pem \
      -x509 -days 365 -out ./cert.pem \
      -subj "/C=FR/ST=Paris/L=Paris/O=elao/emailAddress={{ certificate_email }}/CN={{ certificate_domain }}"
