event:
    path: /
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event:index }

event_register:
    path: /register/{typeId}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event:register }

event_participation:
    path: /participation/{typeId}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event:participation }
