services:
    vimeet_app.form_extension.translation_domain_extension:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Extension\TranslationDomainExtension
        tags:
            - { name: form.type_extension, alias: form }
    vimeet_app.param_converter.event_domain_param_converter:
        class: Proximum\Vimeet\Bundle\AppBundle\ParamConverter\EventViewDomainParamConverter
        arguments:
            - @vimeet_infrastructure.repository.event_repository
        tags:
            - { name: request.param_converter, priority: 2, converter: event_domain_param_converter }
    vimeet_app.param_converter.participant_type_view_param_converter:
        class: Proximum\Vimeet\Bundle\AppBundle\ParamConverter\TypeViewParamConverter
        arguments:
            - @vimeet_infrastructure.repository.type_repository
        tags:
            - { name: request.param_converter, priority: 2, converter: participant_type_view_param_converter }

    #
    # Form type
    #
    vimeet_app.form_type_library.choice_with_description:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\ChoiceWithDescriptionType
        tags:
            - { name: form.type, alias: choice_with_description }
    vimeet_app.form_type_library.upload_with_choices_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\UploadWithChoicesType
        tags:
            - { name: form.type, alias: upload_with_choices }
    vimeet_app.form_type_library.text_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\TextType
        tags:
            - { name: form.type, alias: lib_text }
    vimeet_app.form_type_library.textarea_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\TextareaType
        tags:
            - { name: form.type, alias: lib_textarea }
    vimeet_app.form_type_library.option_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\OptionType
        tags:
            - { name: form.type, alias: lib_option }
    vimeet_app.form_type_library.country_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\CountryType
        tags:
            - { name: form.type, alias: lib_country }
    vimeet_app.form_type_library.email_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\EmailType
        tags:
            - { name: form.type, alias: lib_email }
    vimeet_app.form_type_library.nomenclature_type:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Type\Library\NomenclatureType
        arguments:
            - @vimeet_infrastructure.repository.nomenclature_item_repository
        tags:
            - { name: form.type, alias: lib_nomenclature }

    #
    # Event Listener
    #
    vimeet_app.domain_event_listener:
        class: Proximum\Vimeet\Bundle\AppBundle\EventListener\DomainEventListener
        arguments:
            - @router.default
            - @vimeet_infrastructure.repository.event_repository
        tags:
            - { name: kernel.event_listener, event: kernel.request }
