services:
    vimeet_app.form_extension.translation_domain_extension:
        class: Proximum\Vimeet\Bundle\AppBundle\Form\Extension\TranslationDomainExtension
        tags:
            - { name: form.type_extension }
    vimeet_app.param_converter.event_domain_param_converter:
        class: Proximum\Vimeet\Bundle\AppBundle\ParamConverter\EventViewDomainParamConverter
        arguments:
            - @vimeet_infrastructure.repository.event_repository
        tags:
            - { name: request.param_converter, priority: 2, converter: event_domain_param_converter }
