Proximum\Vimeet\Domain\Model\Spot:
    properties:
        reference:
            - NotBlank: { message: 'validators.spot.reference.type'}
            - Type: { type: string, message: 'validators.spot.reference.type' }
        size:
            - NotBlank: ~
            - Type: { type: float }
            - GreaterThan: 0
        meetingCapacity:
            - NotBlank: ~
            - Type: { type: int }
            - GreaterThan: 0
        seatCapacity:
            - NotBlank: ~
            - Type: { type: int }
            - GreaterThan: 0
        active:
            - Type: { type: bool }
        priority:
            - NotBlank: ~
            - Type: { type: int }
        visio:
            - Type: { type: bool }
