<?php

namespace Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

class Version20161107111045 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema) : void
    {
        $this->abortIf('mysql' != $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE admin_activate_account_token DROP FOREIGN KEY FK_1B64B39B642B8210');
        $this->addSql('ALTER TABLE admin_activate_account_token ADD CONSTRAINT FK_1B64B39B642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE admin_forgotten_password_token DROP FOREIGN KEY FK_C460BF0642B8210');
        $this->addSql('ALTER TABLE admin_forgotten_password_token ADD CONSTRAINT FK_C460BF0642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C171F7E88B');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C171F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_translation DROP FOREIGN KEY FK_3F2070412469DE2');
        $this->addSql('ALTER TABLE category_translation ADD CONSTRAINT FK_3F2070412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE change_mail_token DROP FOREIGN KEY FK_BF082E83A76ED395');
        $this->addSql('ALTER TABLE change_mail_token ADD CONSTRAINT FK_BF082E83A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE content_translation DROP FOREIGN KEY FK_E743EFE984A0A3ED');
        $this->addSql('ALTER TABLE content_translation ADD CONSTRAINT FK_E743EFE984A0A3ED FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_translation DROP FOREIGN KEY FK_1FE096EF71F7E88B');
        $this->addSql('ALTER TABLE event_translation ADD CONSTRAINT FK_1FE096EF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE boolean_template_filter DROP FOREIGN KEY FK_5F4E5D4971F7E88B');
        $this->addSql('ALTER TABLE boolean_template_filter ADD CONSTRAINT FK_5F4E5D4971F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tagged_nomenclature_filter DROP FOREIGN KEY FK_3417B3AF71F7E88B');
        $this->addSql('ALTER TABLE tagged_nomenclature_filter ADD CONSTRAINT FK_3417B3AF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_category DROP FOREIGN KEY FK_C74D7E271F7E88B');
        $this->addSql('ALTER TABLE happening_category ADD CONSTRAINT FK_C74D7E271F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_category_translation DROP FOREIGN KEY FK_7188412812469DE2');
        $this->addSql('ALTER TABLE happening_category_translation ADD CONSTRAINT FK_7188412812469DE2 FOREIGN KEY (category_id) REFERENCES happening_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_translation DROP FOREIGN KEY FK_F319FF82B7B10E6D');
        $this->addSql('ALTER TABLE happening_translation ADD CONSTRAINT FK_F319FF82B7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_speaker DROP FOREIGN KEY FK_43E5DFEF71F7E88B');
        $this->addSql('ALTER TABLE happening_speaker ADD CONSTRAINT FK_43E5DFEF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE speaker_translation DROP FOREIGN KEY FK_7872744D04A0F27');
        $this->addSql('ALTER TABLE speaker_translation ADD CONSTRAINT FK_7872744D04A0F27 FOREIGN KEY (speaker_id) REFERENCES happening_speaker (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening DROP FOREIGN KEY FK_1F3C70AD12469DE2');
        $this->addSql('ALTER TABLE happening DROP FOREIGN KEY FK_1F3C70AD71F7E88B');
        $this->addSql('ALTER TABLE happening ADD CONSTRAINT FK_1F3C70AD12469DE2 FOREIGN KEY (category_id) REFERENCES happening_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening ADD CONSTRAINT FK_1F3C70AD71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_participation DROP FOREIGN KEY FK_6B31720C9D1C3019');
        $this->addSql('ALTER TABLE happening_participation DROP FOREIGN KEY FK_6B31720CB7B10E6D');
        $this->addSql('ALTER TABLE happening_participation ADD CONSTRAINT FK_6B31720C9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_participation ADD CONSTRAINT FK_6B31720CB7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F2427EB8A5');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F267433D9C');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F278CED90B');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F2427EB8A5 FOREIGN KEY (request_id) REFERENCES meeting_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F278CED90B FOREIGN KEY (from_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71230354A65');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71261220EA6');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71267433D9C');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71278CED90B');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71230354A65 FOREIGN KEY (to_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71261220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71278CED90B FOREIGN KEY (from_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139464B980B');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E13959E5119C');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139CDFDE63F');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139464B980B FOREIGN KEY (to_sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E13959E5119C FOREIGN KEY (slot_id) REFERENCES meeting_slot (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139CDFDE63F FOREIGN KEY (from_sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_slot DROP FOREIGN KEY FK_40FFD8B571F7E88B');
        $this->addSql('ALTER TABLE meeting_slot ADD CONSTRAINT FK_40FFD8B571F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA37BC4DC6');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA71F7E88B');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA37BC4DC6 FOREIGN KEY (emitter_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_promotion_code DROP FOREIGN KEY FK_A99F68B77FA7082D');
        $this->addSql('ALTER TABLE order_promotion_code ADD CONSTRAINT FK_A99F68B77FA7082D FOREIGN KEY (promotion_code_id) REFERENCES promotion_code (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_row DROP FOREIGN KEY FK_C76BB9BB4584665A');
        $this->addSql('ALTER TABLE order_row ADD CONSTRAINT FK_C76BB9BB4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE _order DROP FOREIGN KEY FK_7F117F048B1206A5');
        $this->addSql('ALTER TABLE _order ADD CONSTRAINT FK_7F117F048B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867953D865311');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE68679571F7E88B');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867959D1C3019');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867953D865311 FOREIGN KEY (planning_id) REFERENCES product (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE68679571F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867959D1C3019 FOREIGN KEY (participant_id) REFERENCES product (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE package_plan DROP FOREIGN KEY FK_66173EB5E899029B');
        $this->addSql('ALTER TABLE package_plan ADD CONSTRAINT FK_66173EB5E899029B FOREIGN KEY (plan_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B118B1206A5');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B118D9F6D38');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B11A76ED395');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118D9F6D38 FOREIGN KEY (order_id) REFERENCES _order (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D2FC0CB0F');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_feature DROP FOREIGN KEY FK_CE0E6ED64584665A');
        $this->addSql('ALTER TABLE product_feature ADD CONSTRAINT FK_CE0E6ED64584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_product_included DROP FOREIGN KEY FK_A7FBB3633C39138C');
        $this->addSql('ALTER TABLE product_product_included DROP FOREIGN KEY FK_A7FBB3634584665A');
        $this->addSql('ALTER TABLE product_product_included ADD CONSTRAINT FK_A7FBB3633C39138C FOREIGN KEY (included_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_product_included ADD CONSTRAINT FK_A7FBB3634584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD71F7E88B');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_translation DROP FOREIGN KEY FK_1846DB704584665A');
        $this->addSql('ALTER TABLE product_translation ADD CONSTRAINT FK_1846DB704584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_code CHANGE event_id event_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC343F39F1');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC6916A637');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC71F7E88B');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC7AA18A9B');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC8E54762E');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC343F39F1 FOREIGN KEY (seer_type_id) REFERENCES type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC6916A637 FOREIGN KEY (seeable_type_id) REFERENCES type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC7AA18A9B FOREIGN KEY (seeable_category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC8E54762E FOREIGN KEY (seer_category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE search_facet_translation DROP FOREIGN KEY FK_2A164F35ECDF3491');
        $this->addSql('ALTER TABLE search_facet_translation ADD CONSTRAINT FK_2A164F35ECDF3491 FOREIGN KEY (search_facet_id) REFERENCES search_facet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sheet_comment DROP FOREIGN KEY FK_180847D18B1206A5');
        $this->addSql('ALTER TABLE sheet_comment DROP FOREIGN KEY FK_180847D1F675F31B');
        $this->addSql('ALTER TABLE sheet_comment ADD CONSTRAINT FK_180847D18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sheet_comment ADD CONSTRAINT FK_180847D1F675F31B FOREIGN KEY (author_id) REFERENCES admin (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E271F7E88B');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E27E3C61F9');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E2AC24F853');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E2C54C8C93');
        $this->addSql('ALTER TABLE sheet ADD spot_id INT DEFAULT NULL, ADD validation_state VARCHAR(255) DEFAULT \'draft\' NOT NULL');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E22DF1D37C FOREIGN KEY (spot_id) REFERENCES spot (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E271F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E27E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E2AC24F853 FOREIGN KEY (follower_id) REFERENCES admin (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E2C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_873C91E22DF1D37C ON sheet (spot_id)');
        $this->addSql('ALTER TABLE spot DROP FOREIGN KEY FK_B9327A7371F7E88B');
        $this->addSql('ALTER TABLE spot ADD CONSTRAINT FK_B9327A7371F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE template_registration DROP FOREIGN KEY FK_287CFBF271F7E88B');
        $this->addSql('ALTER TABLE template_registration ADD CONSTRAINT FK_287CFBF271F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sheet_template DROP FOREIGN KEY FK_223CACA771F7E88B');
        $this->addSql('ALTER TABLE sheet_template ADD CONSTRAINT FK_223CACA771F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1642B8210');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1A76ED395');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D18B1206A5');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE57294755AC1D');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572971F7E88B');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572997AB0195');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE5729F44CABFF');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE57294755AC1D FOREIGN KEY (registration_template_id) REFERENCES template_registration (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572971F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572997AB0195 FOREIGN KEY (sheet_template_id) REFERENCES sheet_template (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE5729F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE type_translation DROP FOREIGN KEY FK_FF7092FEC54C8C93');
        $this->addSql('ALTER TABLE type_translation ADD CONSTRAINT FK_FF7092FEC54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE unavailability DROP FOREIGN KEY FK_F0016D19D1C3019');
        $this->addSql('ALTER TABLE unavailability ADD CONSTRAINT FK_F0016D19D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_activate_account_token DROP FOREIGN KEY FK_389090CD8B1206A5');
        $this->addSql('ALTER TABLE user_activate_account_token DROP FOREIGN KEY FK_389090CDA76ED395');
        $this->addSql('ALTER TABLE user_activate_account_token ADD CONSTRAINT FK_389090CD8B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_activate_account_token ADD CONSTRAINT FK_389090CDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_forgotten_password_token DROP FOREIGN KEY FK_42C0A3A4A76ED395');
        $this->addSql('ALTER TABLE user_forgotten_password_token ADD CONSTRAINT FK_42C0A3A4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD welcomed TINYINT(1) DEFAULT \'0\' NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema) : void
    {
        $this->abortIf('mysql' != $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE _order DROP FOREIGN KEY FK_7F117F048B1206A5');
        $this->addSql('ALTER TABLE _order ADD CONSTRAINT FK_7F117F048B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE admin_activate_account_token DROP FOREIGN KEY FK_1B64B39B642B8210');
        $this->addSql('ALTER TABLE admin_activate_account_token ADD CONSTRAINT FK_1B64B39B642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE admin_forgotten_password_token DROP FOREIGN KEY FK_C460BF0642B8210');
        $this->addSql('ALTER TABLE admin_forgotten_password_token ADD CONSTRAINT FK_C460BF0642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE boolean_template_filter DROP FOREIGN KEY FK_5F4E5D4971F7E88B');
        $this->addSql('ALTER TABLE boolean_template_filter ADD CONSTRAINT FK_5F4E5D4971F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C171F7E88B');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C171F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE category_translation DROP FOREIGN KEY FK_3F2070412469DE2');
        $this->addSql('ALTER TABLE category_translation ADD CONSTRAINT FK_3F2070412469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE change_mail_token DROP FOREIGN KEY FK_BF082E83A76ED395');
        $this->addSql('ALTER TABLE change_mail_token ADD CONSTRAINT FK_BF082E83A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE content_translation DROP FOREIGN KEY FK_E743EFE984A0A3ED');
        $this->addSql('ALTER TABLE content_translation ADD CONSTRAINT FK_E743EFE984A0A3ED FOREIGN KEY (content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE event_translation DROP FOREIGN KEY FK_1FE096EF71F7E88B');
        $this->addSql('ALTER TABLE event_translation ADD CONSTRAINT FK_1FE096EF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening DROP FOREIGN KEY FK_1F3C70AD71F7E88B');
        $this->addSql('ALTER TABLE happening DROP FOREIGN KEY FK_1F3C70AD12469DE2');
        $this->addSql('ALTER TABLE happening ADD CONSTRAINT FK_1F3C70AD71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening ADD CONSTRAINT FK_1F3C70AD12469DE2 FOREIGN KEY (category_id) REFERENCES happening_category (id)');
        $this->addSql('ALTER TABLE happening_category DROP FOREIGN KEY FK_C74D7E271F7E88B');
        $this->addSql('ALTER TABLE happening_category ADD CONSTRAINT FK_C74D7E271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening_category_translation DROP FOREIGN KEY FK_7188412812469DE2');
        $this->addSql('ALTER TABLE happening_category_translation ADD CONSTRAINT FK_7188412812469DE2 FOREIGN KEY (category_id) REFERENCES happening_category (id)');
        $this->addSql('ALTER TABLE happening_participation DROP FOREIGN KEY FK_6B31720CB7B10E6D');
        $this->addSql('ALTER TABLE happening_participation DROP FOREIGN KEY FK_6B31720C9D1C3019');
        $this->addSql('ALTER TABLE happening_participation ADD CONSTRAINT FK_6B31720CB7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id)');
        $this->addSql('ALTER TABLE happening_participation ADD CONSTRAINT FK_6B31720C9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id)');
        $this->addSql('ALTER TABLE happening_speaker DROP FOREIGN KEY FK_43E5DFEF71F7E88B');
        $this->addSql('ALTER TABLE happening_speaker ADD CONSTRAINT FK_43E5DFEF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening_translation DROP FOREIGN KEY FK_F319FF82B7B10E6D');
        $this->addSql('ALTER TABLE happening_translation ADD CONSTRAINT FK_F319FF82B7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id)');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E13959E5119C');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139CDFDE63F');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139464B980B');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E13959E5119C FOREIGN KEY (slot_id) REFERENCES meeting_slot (id)');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139CDFDE63F FOREIGN KEY (from_sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139464B980B FOREIGN KEY (to_sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F278CED90B');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F267433D9C');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F2427EB8A5');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F278CED90B FOREIGN KEY (from_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id)');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F2427EB8A5 FOREIGN KEY (request_id) REFERENCES meeting_request (id)');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71267433D9C');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71278CED90B');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71230354A65');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71261220EA6');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71278CED90B FOREIGN KEY (from_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71230354A65 FOREIGN KEY (to_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71261220EA6 FOREIGN KEY (creator_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE meeting_slot DROP FOREIGN KEY FK_40FFD8B571F7E88B');
        $this->addSql('ALTER TABLE meeting_slot ADD CONSTRAINT FK_40FFD8B571F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA37BC4DC6');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA71F7E88B');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA37BC4DC6 FOREIGN KEY (emitter_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE order_promotion_code DROP FOREIGN KEY FK_A99F68B77FA7082D');
        $this->addSql('ALTER TABLE order_promotion_code ADD CONSTRAINT FK_A99F68B77FA7082D FOREIGN KEY (promotion_code_id) REFERENCES promotion_code (id)');
        $this->addSql('ALTER TABLE order_row DROP FOREIGN KEY FK_C76BB9BB4584665A');
        $this->addSql('ALTER TABLE order_row ADD CONSTRAINT FK_C76BB9BB4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE68679571F7E88B');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867959D1C3019');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867953D865311');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE68679571F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867959D1C3019 FOREIGN KEY (participant_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867953D865311 FOREIGN KEY (planning_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE package_plan DROP FOREIGN KEY FK_66173EB5E899029B');
        $this->addSql('ALTER TABLE package_plan ADD CONSTRAINT FK_66173EB5E899029B FOREIGN KEY (plan_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B118B1206A5');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B11A76ED395');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B118D9F6D38');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118D9F6D38 FOREIGN KEY (order_id) REFERENCES _order (id)');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D2FC0CB0F');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD71F7E88B');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE product_feature DROP FOREIGN KEY FK_CE0E6ED64584665A');
        $this->addSql('ALTER TABLE product_feature ADD CONSTRAINT FK_CE0E6ED64584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_product_included DROP FOREIGN KEY FK_A7FBB3634584665A');
        $this->addSql('ALTER TABLE product_product_included DROP FOREIGN KEY FK_A7FBB3633C39138C');
        $this->addSql('ALTER TABLE product_product_included ADD CONSTRAINT FK_A7FBB3634584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_product_included ADD CONSTRAINT FK_A7FBB3633C39138C FOREIGN KEY (included_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_translation DROP FOREIGN KEY FK_1846DB704584665A');
        $this->addSql('ALTER TABLE product_translation ADD CONSTRAINT FK_1846DB704584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE promotion_code CHANGE event_id event_id INT NOT NULL');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC71F7E88B');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC343F39F1');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC8E54762E');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC6916A637');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC7AA18A9B');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC343F39F1 FOREIGN KEY (seer_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC8E54762E FOREIGN KEY (seer_category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC6916A637 FOREIGN KEY (seeable_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC7AA18A9B FOREIGN KEY (seeable_category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE search_facet_translation DROP FOREIGN KEY FK_2A164F35ECDF3491');
        $this->addSql('ALTER TABLE search_facet_translation ADD CONSTRAINT FK_2A164F35ECDF3491 FOREIGN KEY (search_facet_id) REFERENCES search_facet (id)');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E22DF1D37C');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E271F7E88B');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E27E3C61F9');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E2C54C8C93');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E2AC24F853');
        $this->addSql('DROP INDEX IDX_873C91E22DF1D37C ON sheet');
        $this->addSql('ALTER TABLE sheet DROP spot_id, DROP validation_state');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E27E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E2C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E2AC24F853 FOREIGN KEY (follower_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE sheet_comment DROP FOREIGN KEY FK_180847D18B1206A5');
        $this->addSql('ALTER TABLE sheet_comment DROP FOREIGN KEY FK_180847D1F675F31B');
        $this->addSql('ALTER TABLE sheet_comment ADD CONSTRAINT FK_180847D18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE sheet_comment ADD CONSTRAINT FK_180847D1F675F31B FOREIGN KEY (author_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE sheet_template DROP FOREIGN KEY FK_223CACA771F7E88B');
        $this->addSql('ALTER TABLE sheet_template ADD CONSTRAINT FK_223CACA771F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE speaker_translation DROP FOREIGN KEY FK_7872744D04A0F27');
        $this->addSql('ALTER TABLE speaker_translation ADD CONSTRAINT FK_7872744D04A0F27 FOREIGN KEY (speaker_id) REFERENCES happening_speaker (id)');
        $this->addSql('ALTER TABLE spot DROP FOREIGN KEY FK_B9327A7371F7E88B');
        $this->addSql('ALTER TABLE spot ADD CONSTRAINT FK_B9327A7371F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE tagged_nomenclature_filter DROP FOREIGN KEY FK_3417B3AF71F7E88B');
        $this->addSql('ALTER TABLE tagged_nomenclature_filter ADD CONSTRAINT FK_3417B3AF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE template_registration DROP FOREIGN KEY FK_287CFBF271F7E88B');
        $this->addSql('ALTER TABLE template_registration ADD CONSTRAINT FK_287CFBF271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1A76ED395');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1642B8210');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D18B1206A5');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572971F7E88B');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572997AB0195');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE57294755AC1D');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE5729F44CABFF');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572971F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572997AB0195 FOREIGN KEY (sheet_template_id) REFERENCES sheet_template (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE57294755AC1D FOREIGN KEY (registration_template_id) REFERENCES template_registration (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE5729F44CABFF FOREIGN KEY (package_id) REFERENCES package (id)');
        $this->addSql('ALTER TABLE type_translation DROP FOREIGN KEY FK_FF7092FEC54C8C93');
        $this->addSql('ALTER TABLE type_translation ADD CONSTRAINT FK_FF7092FEC54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE unavailability DROP FOREIGN KEY FK_F0016D19D1C3019');
        $this->addSql('ALTER TABLE unavailability ADD CONSTRAINT FK_F0016D19D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id)');
        $this->addSql('ALTER TABLE user DROP welcomed');
        $this->addSql('ALTER TABLE user_activate_account_token DROP FOREIGN KEY FK_389090CDA76ED395');
        $this->addSql('ALTER TABLE user_activate_account_token DROP FOREIGN KEY FK_389090CD8B1206A5');
        $this->addSql('ALTER TABLE user_activate_account_token ADD CONSTRAINT FK_389090CDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_activate_account_token ADD CONSTRAINT FK_389090CD8B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE user_forgotten_password_token DROP FOREIGN KEY FK_42C0A3A4A76ED395');
        $this->addSql('ALTER TABLE user_forgotten_password_token ADD CONSTRAINT FK_42C0A3A4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
    }
}
