<?php

namespace Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Init DB and add admin accounts
 */
class Version20160718130808 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf('mysql' != $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE admin_activate_account_token (id INT AUTO_INCREMENT NOT NULL, admin_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expire_date DATETIME NOT NULL, UNIQUE INDEX UNIQ_1B64B39B5F37A13B (token), UNIQUE INDEX UNIQ_1B64B39B642B8210 (admin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admin_forgotten_password_token (id INT AUTO_INCREMENT NOT NULL, admin_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expire_date DATETIME NOT NULL, UNIQUE INDEX UNIQ_C460BF05F37A13B (token), UNIQUE INDEX UNIQ_C460BF0642B8210 (admin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admin (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, last_login_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_880E0D76E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admin_event (admin_id INT NOT NULL, event_id INT NOT NULL, INDEX IDX_9B84F15D642B8210 (admin_id), INDEX IDX_9B84F15D71F7E88B (event_id), PRIMARY KEY(admin_id, event_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE billing_info (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, lastname VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, function VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, vat_number VARCHAR(255) DEFAULT NULL, address_street VARCHAR(255) NOT NULL, address_zipcode VARCHAR(255) NOT NULL, address_city VARCHAR(255) NOT NULL, address_country VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_B4FB0F908B1206A5 (sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_row (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, product_id INT DEFAULT NULL, quantity INT NOT NULL, serialized_product LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_B420E5988B1206A5 (sheet_id), INDEX IDX_B420E5984584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_step (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, current_step INT NOT NULL, INDEX IDX_AC5CFE058B1206A5 (sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, filters LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_64C19C171F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_type (category_id INT NOT NULL, type_id INT NOT NULL, INDEX IDX_7452D6E12469DE2 (category_id), INDEX IDX_7452D6EC54C8C93 (type_id), PRIMARY KEY(category_id, type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_translation (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_3F2070412469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE change_mail_token (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, expire_date DATETIME NOT NULL, UNIQUE INDEX UNIQ_BF082E835F37A13B (token), UNIQUE INDEX UNIQ_BF082E83A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_FEC530A971F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content_translation (id INT AUTO_INCREMENT NOT NULL, content_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, value LONGTEXT NOT NULL, INDEX IDX_E743EFE984A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, time_zone VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, locales LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', fallback VARCHAR(255) NOT NULL, organiser_name VARCHAR(255) DEFAULT NULL, organiser_email VARCHAR(255) DEFAULT NULL, legal_information VARCHAR(255) DEFAULT NULL, mode VARCHAR(255) NOT NULL, vat DOUBLE PRECISION NOT NULL, element_to_join_with_invoice VARCHAR(255) DEFAULT NULL, asset_path VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, payment_address_street VARCHAR(255) NOT NULL, payment_address_zipcode VARCHAR(255) NOT NULL, payment_address_city VARCHAR(255) NOT NULL, payment_address_country VARCHAR(255) NOT NULL, configuration_left_color VARCHAR(255) NOT NULL, configuration_right_color VARCHAR(255) NOT NULL, configuration_text_color VARCHAR(255) NOT NULL, configuration_schedule_scale INT NOT NULL, configuration_catalog_online_date DATETIME DEFAULT NULL, configuration_happenings_open_date DATETIME DEFAULT NULL, configuration_schedule_publish_date DATETIME DEFAULT NULL, configuration_legal_info VARCHAR(255) DEFAULT NULL, configuration_contact_first_name VARCHAR(255) DEFAULT NULL, configuration_contact_last_name VARCHAR(255) DEFAULT NULL, configuration_organiser_phone VARCHAR(255) DEFAULT NULL, configuration_organiser_website VARCHAR(255) DEFAULT NULL, configuration_allow_deposit TINYINT(1) NOT NULL, configuration_deposit_until DATETIME DEFAULT NULL, configuration_minimum_for_deposit DOUBLE PRECISION DEFAULT NULL, configuration_deposit INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_translation (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, description LONGTEXT NOT NULL, locale VARCHAR(255) NOT NULL, bank_info LONGTEXT DEFAULT NULL, billing_address LONGTEXT DEFAULT NULL, payment_condition LONGTEXT DEFAULT NULL, payment_footer LONGTEXT DEFAULT NULL, INDEX IDX_1FE096EF71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening_category (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, picto VARCHAR(255) NOT NULL, position INT NOT NULL, INDEX IDX_C74D7E271F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening_category_translation (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_7188412812469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening_translation (id INT AUTO_INCREMENT NOT NULL, happening_id INT DEFAULT NULL, title LONGTEXT NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_F319FF82B7B10E6D (happening_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening_speaker (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, organization VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, INDEX IDX_43E5DFEF71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE speaker_translation (id INT AUTO_INCREMENT NOT NULL, speaker_id INT DEFAULT NULL, position VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_7872744D04A0F27 (speaker_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening_talking (id INT AUTO_INCREMENT NOT NULL, speaker_id INT DEFAULT NULL, happening_id INT DEFAULT NULL, position INT NOT NULL, INDEX IDX_A1C85B04D04A0F27 (speaker_id), INDEX IDX_A1C85B04B7B10E6D (happening_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, category_id INT DEFAULT NULL, begin DATETIME NOT NULL, end DATETIME NOT NULL, INDEX IDX_1F3C70AD71F7E88B (event_id), INDEX IDX_1F3C70AD12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE happening_participation (id INT AUTO_INCREMENT NOT NULL, happening_id INT DEFAULT NULL, participant_id INT DEFAULT NULL, INDEX IDX_6B31720CB7B10E6D (happening_id), INDEX IDX_6B31720C9D1C3019 (participant_id), UNIQUE INDEX unique_idx_1 (happening_id, participant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_message (id INT AUTO_INCREMENT NOT NULL, from_id INT DEFAULT NULL, meeting_id INT DEFAULT NULL, request_id INT DEFAULT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_2E6F78F278CED90B (from_id), INDEX IDX_2E6F78F267433D9C (meeting_id), INDEX IDX_2E6F78F2427EB8A5 (request_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_request (id INT AUTO_INCREMENT NOT NULL, meeting_id INT DEFAULT NULL, from_id INT DEFAULT NULL, to_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, state_updated_at DATETIME NOT NULL, INDEX IDX_A345C71267433D9C (meeting_id), INDEX IDX_A345C71278CED90B (from_id), INDEX IDX_A345C71230354A65 (to_id), INDEX IDX_A345C71261220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_request_from_participants (request_id INT NOT NULL, participant_id INT NOT NULL, INDEX IDX_EFBD76E8427EB8A5 (request_id), INDEX IDX_EFBD76E89D1C3019 (participant_id), PRIMARY KEY(request_id, participant_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_request_to_participants (request_id INT NOT NULL, participant_id INT NOT NULL, INDEX IDX_CD193033427EB8A5 (request_id), INDEX IDX_CD1930339D1C3019 (participant_id), PRIMARY KEY(request_id, participant_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting (id INT AUTO_INCREMENT NOT NULL, slot_id INT DEFAULT NULL, from_sheet_id INT DEFAULT NULL, to_sheet_id INT DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_F515E13959E5119C (slot_id), INDEX IDX_F515E139CDFDE63F (from_sheet_id), INDEX IDX_F515E139464B980B (to_sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_from_participants (meeting_id INT NOT NULL, participant_id INT NOT NULL, INDEX IDX_A281C0E067433D9C (meeting_id), INDEX IDX_A281C0E09D1C3019 (participant_id), PRIMARY KEY(meeting_id, participant_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_to_participants (meeting_id INT NOT NULL, participant_id INT NOT NULL, INDEX IDX_A4A6A9AE67433D9C (meeting_id), INDEX IDX_A4A6A9AE9D1C3019 (participant_id), PRIMARY KEY(meeting_id, participant_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_slot (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, begin DATETIME NOT NULL, end DATETIME NOT NULL, locked TINYINT(1) NOT NULL, INDEX IDX_40FFD8B571F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nomenclature (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, original_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, depth INT NOT NULL, value LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', sort TINYINT(1) NOT NULL, INDEX IDX_799A365271F7E88B (event_id), INDEX IDX_799A3652108B7592 (original_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, emitter_id INT DEFAULT NULL, recipient_id INT DEFAULT NULL, event_id INT DEFAULT NULL, action VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, url LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, view TINYINT(1) NOT NULL, INDEX IDX_BF5476CA37BC4DC6 (emitter_id), INDEX IDX_BF5476CAE92F8F78 (recipient_id), INDEX IDX_BF5476CA71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_promotion_code (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, promotion_code_id INT DEFAULT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', price DOUBLE PRECISION NOT NULL, INDEX IDX_A99F68B78D9F6D38 (order_id), INDEX IDX_A99F68B77FA7082D (promotion_code_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_row (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, product_id INT DEFAULT NULL, quantity INT NOT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', group_id INT DEFAULT NULL, price DOUBLE PRECISION NOT NULL, INDEX IDX_C76BB9BB8D9F6D38 (order_id), INDEX IDX_C76BB9BB4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE _order (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, created_at DATETIME NOT NULL, vat_mode VARCHAR(255) NOT NULL, groups_data LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', vat_applicable TINYINT(1) NOT NULL, vat_rate DOUBLE PRECISION NOT NULL, currency VARCHAR(255) NOT NULL, billing_info_last_name VARCHAR(255) NOT NULL, billing_info_first_name VARCHAR(255) NOT NULL, billing_info_position VARCHAR(255) DEFAULT NULL, billing_info_phone VARCHAR(255) DEFAULT NULL, billing_info_mobile VARCHAR(255) DEFAULT NULL, billing_info_email VARCHAR(255) NOT NULL, billing_info_company VARCHAR(255) NOT NULL, billing_info_vat_number VARCHAR(255) DEFAULT NULL, billing_info_address_street VARCHAR(255) NOT NULL, billing_info_address_zipcode VARCHAR(255) NOT NULL, billing_info_address_city VARCHAR(255) NOT NULL, billing_info_address_country VARCHAR(255) NOT NULL, INDEX IDX_7F117F048B1206A5 (sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, participant_id INT DEFAULT NULL, planning_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, plans_enabled TINYINT(1) NOT NULL, participant_and_planning_enabled TINYINT(1) NOT NULL, options_enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_DE68679571F7E88B (event_id), INDEX IDX_DE6867959D1C3019 (participant_id), INDEX IDX_DE6867953D865311 (planning_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_group (id INT AUTO_INCREMENT NOT NULL, package_id INT DEFAULT NULL, rank INT NOT NULL, INDEX IDX_F8C44322F44CABFF (package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_group_translation (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, `label` VARCHAR(255) NOT NULL, INDEX IDX_D0E0241FE54D947 (group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_option (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, option_id INT DEFAULT NULL, rank INT NOT NULL, INDEX IDX_647D736CFE54D947 (group_id), INDEX IDX_647D736CA7C41D6F (option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_plan (id INT AUTO_INCREMENT NOT NULL, package_id INT DEFAULT NULL, plan_id INT DEFAULT NULL, rank INT NOT NULL, INDEX IDX_66173EB5F44CABFF (package_id), INDEX IDX_66173EB5E899029B (plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_translation (id INT AUTO_INCREMENT NOT NULL, package_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, plans_label VARCHAR(255) NOT NULL, participant_and_planning_label VARCHAR(255) NOT NULL, options_label VARCHAR(255) NOT NULL, INDEX IDX_79B25F09F44CABFF (package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE participant (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, user_id INT DEFAULT NULL, order_id INT DEFAULT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', active TINYINT(1) NOT NULL, INDEX IDX_D79F6B118B1206A5 (sheet_id), INDEX IDX_D79F6B11A76ED395 (user_id), INDEX IDX_D79F6B118D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_feature (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, INDEX IDX_CE0E6ED64584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_feature_translation (id INT AUTO_INCREMENT NOT NULL, feature_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_353B32CA60E4B879 (feature_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_product_included (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, included_id INT DEFAULT NULL, quantity INT NOT NULL, INDEX IDX_A7FBB3634584665A (product_id), INDEX IDX_A7FBB3633C39138C (included_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, unit_price DOUBLE PRECISION NOT NULL, quantity_max INT DEFAULT NULL, availability_current INT DEFAULT NULL, availability_max INT DEFAULT NULL, updatable TINYINT(1) NOT NULL, updatable_until DATETIME DEFAULT NULL, buyable_until DATETIME DEFAULT NULL, subjected_to_validation TINYINT(1) NOT NULL, INDEX IDX_D34A04AD71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_translation (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, heading VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, addon LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, subjected_to_validation_help VARCHAR(255) DEFAULT NULL, INDEX IDX_1846DB704584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion (id INT AUTO_INCREMENT NOT NULL, promotion_code_id INT NOT NULL, product_id INT NOT NULL, type VARCHAR(255) NOT NULL, value DOUBLE PRECISION DEFAULT NULL, quantity INT NOT NULL, INDEX IDX_C11D7DD17FA7082D (promotion_code_id), INDEX IDX_C11D7DD14584665A (product_id), UNIQUE INDEX unique_promotion_product (promotion_code_id, product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion_code (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, title VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, valid_until DATETIME DEFAULT NULL, stock INT DEFAULT NULL, INDEX IDX_C1EFB80771F7E88B (event_id), UNIQUE INDEX unique_code_idx (event_id, code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion_code_row (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, promotion_code_id INT DEFAULT NULL, INDEX IDX_AA4465358B1206A5 (sheet_id), INDEX IDX_AA4465357FA7082D (promotion_code_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion_code_translation (id INT AUTO_INCREMENT NOT NULL, promotion_code_id INT NOT NULL, locale VARCHAR(255) NOT NULL, `label` VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_1251C02F7FA7082D (promotion_code_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rule (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, seer_type_id INT DEFAULT NULL, seer_category_id INT DEFAULT NULL, seeable_type_id INT DEFAULT NULL, seeable_category_id INT DEFAULT NULL, what LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_46D8ACCC71F7E88B (event_id), INDEX IDX_46D8ACCC343F39F1 (seer_type_id), INDEX IDX_46D8ACCC8E54762E (seer_category_id), INDEX IDX_46D8ACCC6916A637 (seeable_type_id), INDEX IDX_46D8ACCC7AA18A9B (seeable_category_id), UNIQUE INDEX unique_idx_1 (seer_type_id, seeable_type_id), UNIQUE INDEX unique_idx_2 (seer_type_id, seeable_category_id), UNIQUE INDEX unique_idx_3 (seer_category_id, seeable_type_id), UNIQUE INDEX unique_idx_4 (seer_category_id, seeable_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sheet_comment (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, author_id INT DEFAULT NULL, text LONGTEXT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_180847D18B1206A5 (sheet_id), INDEX IDX_180847D1F675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sheet (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, type_id INT DEFAULT NULL, follower_id INT DEFAULT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', registration_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', created_at DATETIME NOT NULL, last_login_at DATETIME DEFAULT NULL, state VARCHAR(255) NOT NULL, completed TINYINT(1) NOT NULL, INDEX IDX_873C91E271F7E88B (event_id), INDEX IDX_873C91E27E3C61F9 (owner_id), INDEX IDX_873C91E2C54C8C93 (type_id), INDEX IDX_873C91E2AC24F853 (follower_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE spot (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL, size DOUBLE PRECISION NOT NULL, meeting_capacity INT NOT NULL, seat_capacity INT NOT NULL, active TINYINT(1) NOT NULL, INDEX IDX_B9327A7371F7E88B (event_id), UNIQUE INDEX unique_reference_idx (reference, event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_registration (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locales LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', fallback VARCHAR(5) NOT NULL, value LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', created_at DATETIME NOT NULL, INDEX IDX_287CFBF271F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sheet_template (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locales LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', fallback VARCHAR(5) NOT NULL, value LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', created_at DATETIME NOT NULL, INDEX IDX_223CACA771F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trace (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, admin_id INT DEFAULT NULL, object VARCHAR(255) NOT NULL, action VARCHAR(255) NOT NULL, date DATETIME NOT NULL, comment LONGTEXT DEFAULT NULL, INDEX IDX_315BD5A1A76ED395 (user_id), INDEX IDX_315BD5A1642B8210 (admin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, sheet_id INT DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, date DATETIME NOT NULL, mode VARCHAR(255) NOT NULL, reference VARCHAR(255) DEFAULT NULL, state VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, INDEX IDX_723705D18B1206A5 (sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, sheet_template_id INT DEFAULT NULL, registration_template_id INT DEFAULT NULL, package_id INT DEFAULT NULL, position INT DEFAULT NULL, preview_template LONGTEXT NOT NULL, view_template LONGTEXT NOT NULL, validation_criteria_sheet_accepted TINYINT(1) NOT NULL, INDEX IDX_8CDE572971F7E88B (event_id), INDEX IDX_8CDE572997AB0195 (sheet_template_id), INDEX IDX_8CDE57294755AC1D (registration_template_id), INDEX IDX_8CDE5729F44CABFF (package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_translation (id INT AUTO_INCREMENT NOT NULL, type_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_FF7092FEC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unavailability (id INT AUTO_INCREMENT NOT NULL, participant_id INT DEFAULT NULL, begin DATETIME NOT NULL, end DATETIME NOT NULL, INDEX IDX_F0016D19D1C3019 (participant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_activate_account_token (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, sheet_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expire_date DATETIME NOT NULL, UNIQUE INDEX UNIQ_389090CD5F37A13B (token), UNIQUE INDEX UNIQ_389090CDA76ED395 (user_id), INDEX IDX_389090CD8B1206A5 (sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_forgotten_password_token (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expire_date DATETIME NOT NULL, UNIQUE INDEX UNIQ_42C0A3A45F37A13B (token), UNIQUE INDEX UNIQ_42C0A3A4A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, account_first_name VARCHAR(255) DEFAULT NULL, account_last_name VARCHAR(255) DEFAULT NULL, account_phone VARCHAR(255) DEFAULT NULL, account_mobile VARCHAR(255) DEFAULT NULL, account_avatar VARCHAR(255) DEFAULT NULL, account_position VARCHAR(255) DEFAULT NULL, account_company VARCHAR(255) DEFAULT NULL, account_website VARCHAR(255) DEFAULT NULL, account_address VARCHAR(255) DEFAULT NULL, account_zip_code VARCHAR(255) DEFAULT NULL, account_city VARCHAR(255) DEFAULT NULL, account_country VARCHAR(255) DEFAULT NULL, account_gender VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE admin_activate_account_token ADD CONSTRAINT FK_1B64B39B642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE admin_forgotten_password_token ADD CONSTRAINT FK_C460BF0642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE admin_event ADD CONSTRAINT FK_9B84F15D642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE admin_event ADD CONSTRAINT FK_9B84F15D71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE billing_info ADD CONSTRAINT FK_B4FB0F908B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_row ADD CONSTRAINT FK_B420E5988B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_row ADD CONSTRAINT FK_B420E5984584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_step ADD CONSTRAINT FK_AC5CFE058B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C171F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE category_type ADD CONSTRAINT FK_7452D6E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_type ADD CONSTRAINT FK_7452D6EC54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_translation ADD CONSTRAINT FK_3F2070412469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE change_mail_token ADD CONSTRAINT FK_BF082E83A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A971F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE content_translation ADD CONSTRAINT FK_E743EFE984A0A3ED FOREIGN KEY (content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE event_translation ADD CONSTRAINT FK_1FE096EF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening_category ADD CONSTRAINT FK_C74D7E271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening_category_translation ADD CONSTRAINT FK_7188412812469DE2 FOREIGN KEY (category_id) REFERENCES happening_category (id)');
        $this->addSql('ALTER TABLE happening_translation ADD CONSTRAINT FK_F319FF82B7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id)');
        $this->addSql('ALTER TABLE happening_speaker ADD CONSTRAINT FK_43E5DFEF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE speaker_translation ADD CONSTRAINT FK_7872744D04A0F27 FOREIGN KEY (speaker_id) REFERENCES happening_speaker (id)');
        $this->addSql('ALTER TABLE happening_talking ADD CONSTRAINT FK_A1C85B04D04A0F27 FOREIGN KEY (speaker_id) REFERENCES happening_speaker (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening_talking ADD CONSTRAINT FK_A1C85B04B7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE happening ADD CONSTRAINT FK_1F3C70AD71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE happening ADD CONSTRAINT FK_1F3C70AD12469DE2 FOREIGN KEY (category_id) REFERENCES happening_category (id)');
        $this->addSql('ALTER TABLE happening_participation ADD CONSTRAINT FK_6B31720CB7B10E6D FOREIGN KEY (happening_id) REFERENCES happening (id)');
        $this->addSql('ALTER TABLE happening_participation ADD CONSTRAINT FK_6B31720C9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id)');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F278CED90B FOREIGN KEY (from_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id)');
        $this->addSql('ALTER TABLE meeting_message ADD CONSTRAINT FK_2E6F78F2427EB8A5 FOREIGN KEY (request_id) REFERENCES meeting_request (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71278CED90B FOREIGN KEY (from_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71230354A65 FOREIGN KEY (to_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_request ADD CONSTRAINT FK_A345C71261220EA6 FOREIGN KEY (creator_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE meeting_request_from_participants ADD CONSTRAINT FK_EFBD76E8427EB8A5 FOREIGN KEY (request_id) REFERENCES meeting_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_request_from_participants ADD CONSTRAINT FK_EFBD76E89D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_request_to_participants ADD CONSTRAINT FK_CD193033427EB8A5 FOREIGN KEY (request_id) REFERENCES meeting_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_request_to_participants ADD CONSTRAINT FK_CD1930339D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E13959E5119C FOREIGN KEY (slot_id) REFERENCES meeting_slot (id)');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139CDFDE63F FOREIGN KEY (from_sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139464B980B FOREIGN KEY (to_sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE meeting_from_participants ADD CONSTRAINT FK_A281C0E067433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_from_participants ADD CONSTRAINT FK_A281C0E09D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_to_participants ADD CONSTRAINT FK_A4A6A9AE67433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_to_participants ADD CONSTRAINT FK_A4A6A9AE9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_slot ADD CONSTRAINT FK_40FFD8B571F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE nomenclature ADD CONSTRAINT FK_799A365271F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE nomenclature ADD CONSTRAINT FK_799A3652108B7592 FOREIGN KEY (original_id) REFERENCES nomenclature (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA37BC4DC6 FOREIGN KEY (emitter_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE order_promotion_code ADD CONSTRAINT FK_A99F68B78D9F6D38 FOREIGN KEY (order_id) REFERENCES _order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_promotion_code ADD CONSTRAINT FK_A99F68B77FA7082D FOREIGN KEY (promotion_code_id) REFERENCES promotion_code (id)');
        $this->addSql('ALTER TABLE order_row ADD CONSTRAINT FK_C76BB9BB8D9F6D38 FOREIGN KEY (order_id) REFERENCES _order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_row ADD CONSTRAINT FK_C76BB9BB4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE _order ADD CONSTRAINT FK_7F117F048B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE68679571F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867959D1C3019 FOREIGN KEY (participant_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867953D865311 FOREIGN KEY (planning_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE package_group ADD CONSTRAINT FK_F8C44322F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package_group_translation ADD CONSTRAINT FK_D0E0241FE54D947 FOREIGN KEY (group_id) REFERENCES package_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package_option ADD CONSTRAINT FK_647D736CFE54D947 FOREIGN KEY (group_id) REFERENCES package_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package_option ADD CONSTRAINT FK_647D736CA7C41D6F FOREIGN KEY (option_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package_plan ADD CONSTRAINT FK_66173EB5F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package_plan ADD CONSTRAINT FK_66173EB5E899029B FOREIGN KEY (plan_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE package_translation ADD CONSTRAINT FK_79B25F09F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118D9F6D38 FOREIGN KEY (order_id) REFERENCES _order (id)');
        $this->addSql('ALTER TABLE product_feature ADD CONSTRAINT FK_CE0E6ED64584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_feature_translation ADD CONSTRAINT FK_353B32CA60E4B879 FOREIGN KEY (feature_id) REFERENCES product_feature (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_product_included ADD CONSTRAINT FK_A7FBB3634584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_product_included ADD CONSTRAINT FK_A7FBB3633C39138C FOREIGN KEY (included_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE product_translation ADD CONSTRAINT FK_1846DB704584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE promotion ADD CONSTRAINT FK_C11D7DD17FA7082D FOREIGN KEY (promotion_code_id) REFERENCES promotion_code (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion ADD CONSTRAINT FK_C11D7DD14584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_code ADD CONSTRAINT FK_C1EFB80771F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_code_row ADD CONSTRAINT FK_AA4465358B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_code_row ADD CONSTRAINT FK_AA4465357FA7082D FOREIGN KEY (promotion_code_id) REFERENCES promotion_code (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_code_translation ADD CONSTRAINT FK_1251C02F7FA7082D FOREIGN KEY (promotion_code_id) REFERENCES promotion_code (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC343F39F1 FOREIGN KEY (seer_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC8E54762E FOREIGN KEY (seer_category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC6916A637 FOREIGN KEY (seeable_type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC7AA18A9B FOREIGN KEY (seeable_category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE sheet_comment ADD CONSTRAINT FK_180847D18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE sheet_comment ADD CONSTRAINT FK_180847D1F675F31B FOREIGN KEY (author_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E27E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E2C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE sheet ADD CONSTRAINT FK_873C91E2AC24F853 FOREIGN KEY (follower_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE spot ADD CONSTRAINT FK_B9327A7371F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE template_registration ADD CONSTRAINT FK_287CFBF271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE sheet_template ADD CONSTRAINT FK_223CACA771F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572971F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572997AB0195 FOREIGN KEY (sheet_template_id) REFERENCES sheet_template (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE57294755AC1D FOREIGN KEY (registration_template_id) REFERENCES template_registration (id)');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE5729F44CABFF FOREIGN KEY (package_id) REFERENCES package (id)');
        $this->addSql('ALTER TABLE type_translation ADD CONSTRAINT FK_FF7092FEC54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE unavailability ADD CONSTRAINT FK_F0016D19D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id)');
        $this->addSql('ALTER TABLE user_activate_account_token ADD CONSTRAINT FK_389090CDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_activate_account_token ADD CONSTRAINT FK_389090CD8B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id)');
        $this->addSql('ALTER TABLE user_forgotten_password_token ADD CONSTRAINT FK_42C0A3A4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');

        // add admin accounts
        $this->addSql('INSERT INTO admin (email, password, salt, locale, firstname, lastname, role, created_at) VALUES("goi@proximumgroup.com", "YzzBNEhw7I6H5xPuziQEAPAsg5g=", "D/TBAVl5oYyYU6/4F7gOT0mQkbBD8c5rBHga80zO", "fr", "Layla", "GOI", "ROLE_SUPER_ADMIN", NOW())');
        $this->addSql('INSERT INTO admin (email, password, salt, locale, firstname, lastname, role, created_at) VALUES("larose@proximumgroup.com", "O9CLi6YZtHirpgd3fF/r2M2LMFs=", "hOcoU9/L7niTCDDLQOhqTzbrrEMO0/HWlbSQ6DNh", "fr", "Vincent", "LAROSE", "ROLE_ORGANIZER", NOW())');
        $this->addSql('INSERT INTO admin (email, password, salt, locale, firstname, lastname, role, created_at) VALUES("gagnard@proximumgroup.com", "ENwYwD3WZei+Uv9Yl+DkbwlC6EY=", "AkV6xDVrMTmD285rboI/Z9G31Id+WrvtoaLs/q3A", "fr", "Julien", "GAGNARD", "ROLE_OPERATOR", NOW())');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf('mysql' != $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE admin_activate_account_token DROP FOREIGN KEY FK_1B64B39B642B8210');
        $this->addSql('ALTER TABLE admin_forgotten_password_token DROP FOREIGN KEY FK_C460BF0642B8210');
        $this->addSql('ALTER TABLE admin_event DROP FOREIGN KEY FK_9B84F15D642B8210');
        $this->addSql('ALTER TABLE sheet_comment DROP FOREIGN KEY FK_180847D1F675F31B');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E2AC24F853');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1642B8210');
        $this->addSql('ALTER TABLE category_type DROP FOREIGN KEY FK_7452D6E12469DE2');
        $this->addSql('ALTER TABLE category_translation DROP FOREIGN KEY FK_3F2070412469DE2');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC8E54762E');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC7AA18A9B');
        $this->addSql('ALTER TABLE content_translation DROP FOREIGN KEY FK_E743EFE984A0A3ED');
        $this->addSql('ALTER TABLE admin_event DROP FOREIGN KEY FK_9B84F15D71F7E88B');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C171F7E88B');
        $this->addSql('ALTER TABLE content DROP FOREIGN KEY FK_FEC530A971F7E88B');
        $this->addSql('ALTER TABLE event_translation DROP FOREIGN KEY FK_1FE096EF71F7E88B');
        $this->addSql('ALTER TABLE happening_category DROP FOREIGN KEY FK_C74D7E271F7E88B');
        $this->addSql('ALTER TABLE happening_speaker DROP FOREIGN KEY FK_43E5DFEF71F7E88B');
        $this->addSql('ALTER TABLE happening DROP FOREIGN KEY FK_1F3C70AD71F7E88B');
        $this->addSql('ALTER TABLE meeting_slot DROP FOREIGN KEY FK_40FFD8B571F7E88B');
        $this->addSql('ALTER TABLE nomenclature DROP FOREIGN KEY FK_799A365271F7E88B');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA71F7E88B');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE68679571F7E88B');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD71F7E88B');
        $this->addSql('ALTER TABLE promotion_code DROP FOREIGN KEY FK_C1EFB80771F7E88B');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC71F7E88B');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E271F7E88B');
        $this->addSql('ALTER TABLE spot DROP FOREIGN KEY FK_B9327A7371F7E88B');
        $this->addSql('ALTER TABLE template_registration DROP FOREIGN KEY FK_287CFBF271F7E88B');
        $this->addSql('ALTER TABLE sheet_template DROP FOREIGN KEY FK_223CACA771F7E88B');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572971F7E88B');
        $this->addSql('ALTER TABLE happening_category_translation DROP FOREIGN KEY FK_7188412812469DE2');
        $this->addSql('ALTER TABLE happening DROP FOREIGN KEY FK_1F3C70AD12469DE2');
        $this->addSql('ALTER TABLE speaker_translation DROP FOREIGN KEY FK_7872744D04A0F27');
        $this->addSql('ALTER TABLE happening_talking DROP FOREIGN KEY FK_A1C85B04D04A0F27');
        $this->addSql('ALTER TABLE happening_translation DROP FOREIGN KEY FK_F319FF82B7B10E6D');
        $this->addSql('ALTER TABLE happening_talking DROP FOREIGN KEY FK_A1C85B04B7B10E6D');
        $this->addSql('ALTER TABLE happening_participation DROP FOREIGN KEY FK_6B31720CB7B10E6D');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F2427EB8A5');
        $this->addSql('ALTER TABLE meeting_request_from_participants DROP FOREIGN KEY FK_EFBD76E8427EB8A5');
        $this->addSql('ALTER TABLE meeting_request_to_participants DROP FOREIGN KEY FK_CD193033427EB8A5');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F267433D9C');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71267433D9C');
        $this->addSql('ALTER TABLE meeting_from_participants DROP FOREIGN KEY FK_A281C0E067433D9C');
        $this->addSql('ALTER TABLE meeting_to_participants DROP FOREIGN KEY FK_A4A6A9AE67433D9C');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E13959E5119C');
        $this->addSql('ALTER TABLE nomenclature DROP FOREIGN KEY FK_799A3652108B7592');
        $this->addSql('ALTER TABLE order_promotion_code DROP FOREIGN KEY FK_A99F68B78D9F6D38');
        $this->addSql('ALTER TABLE order_row DROP FOREIGN KEY FK_C76BB9BB8D9F6D38');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B118D9F6D38');
        $this->addSql('ALTER TABLE package_group DROP FOREIGN KEY FK_F8C44322F44CABFF');
        $this->addSql('ALTER TABLE package_plan DROP FOREIGN KEY FK_66173EB5F44CABFF');
        $this->addSql('ALTER TABLE package_translation DROP FOREIGN KEY FK_79B25F09F44CABFF');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE5729F44CABFF');
        $this->addSql('ALTER TABLE package_group_translation DROP FOREIGN KEY FK_D0E0241FE54D947');
        $this->addSql('ALTER TABLE package_option DROP FOREIGN KEY FK_647D736CFE54D947');
        $this->addSql('ALTER TABLE happening_participation DROP FOREIGN KEY FK_6B31720C9D1C3019');
        $this->addSql('ALTER TABLE meeting_request_from_participants DROP FOREIGN KEY FK_EFBD76E89D1C3019');
        $this->addSql('ALTER TABLE meeting_request_to_participants DROP FOREIGN KEY FK_CD1930339D1C3019');
        $this->addSql('ALTER TABLE meeting_from_participants DROP FOREIGN KEY FK_A281C0E09D1C3019');
        $this->addSql('ALTER TABLE meeting_to_participants DROP FOREIGN KEY FK_A4A6A9AE9D1C3019');
        $this->addSql('ALTER TABLE unavailability DROP FOREIGN KEY FK_F0016D19D1C3019');
        $this->addSql('ALTER TABLE product_feature_translation DROP FOREIGN KEY FK_353B32CA60E4B879');
        $this->addSql('ALTER TABLE cart_row DROP FOREIGN KEY FK_B420E5984584665A');
        $this->addSql('ALTER TABLE order_row DROP FOREIGN KEY FK_C76BB9BB4584665A');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867959D1C3019');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867953D865311');
        $this->addSql('ALTER TABLE package_option DROP FOREIGN KEY FK_647D736CA7C41D6F');
        $this->addSql('ALTER TABLE package_plan DROP FOREIGN KEY FK_66173EB5E899029B');
        $this->addSql('ALTER TABLE product_feature DROP FOREIGN KEY FK_CE0E6ED64584665A');
        $this->addSql('ALTER TABLE product_product_included DROP FOREIGN KEY FK_A7FBB3634584665A');
        $this->addSql('ALTER TABLE product_product_included DROP FOREIGN KEY FK_A7FBB3633C39138C');
        $this->addSql('ALTER TABLE product_translation DROP FOREIGN KEY FK_1846DB704584665A');
        $this->addSql('ALTER TABLE promotion DROP FOREIGN KEY FK_C11D7DD14584665A');
        $this->addSql('ALTER TABLE order_promotion_code DROP FOREIGN KEY FK_A99F68B77FA7082D');
        $this->addSql('ALTER TABLE promotion DROP FOREIGN KEY FK_C11D7DD17FA7082D');
        $this->addSql('ALTER TABLE promotion_code_row DROP FOREIGN KEY FK_AA4465357FA7082D');
        $this->addSql('ALTER TABLE promotion_code_translation DROP FOREIGN KEY FK_1251C02F7FA7082D');
        $this->addSql('ALTER TABLE billing_info DROP FOREIGN KEY FK_B4FB0F908B1206A5');
        $this->addSql('ALTER TABLE cart_row DROP FOREIGN KEY FK_B420E5988B1206A5');
        $this->addSql('ALTER TABLE cart_step DROP FOREIGN KEY FK_AC5CFE058B1206A5');
        $this->addSql('ALTER TABLE meeting_message DROP FOREIGN KEY FK_2E6F78F278CED90B');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71278CED90B');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71230354A65');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139CDFDE63F');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139464B980B');
        $this->addSql('ALTER TABLE _order DROP FOREIGN KEY FK_7F117F048B1206A5');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B118B1206A5');
        $this->addSql('ALTER TABLE promotion_code_row DROP FOREIGN KEY FK_AA4465358B1206A5');
        $this->addSql('ALTER TABLE sheet_comment DROP FOREIGN KEY FK_180847D18B1206A5');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D18B1206A5');
        $this->addSql('ALTER TABLE user_activate_account_token DROP FOREIGN KEY FK_389090CD8B1206A5');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE57294755AC1D');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572997AB0195');
        $this->addSql('ALTER TABLE category_type DROP FOREIGN KEY FK_7452D6EC54C8C93');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC343F39F1');
        $this->addSql('ALTER TABLE rule DROP FOREIGN KEY FK_46D8ACCC6916A637');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E2C54C8C93');
        $this->addSql('ALTER TABLE type_translation DROP FOREIGN KEY FK_FF7092FEC54C8C93');
        $this->addSql('ALTER TABLE change_mail_token DROP FOREIGN KEY FK_BF082E83A76ED395');
        $this->addSql('ALTER TABLE meeting_request DROP FOREIGN KEY FK_A345C71261220EA6');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA37BC4DC6');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE participant DROP FOREIGN KEY FK_D79F6B11A76ED395');
        $this->addSql('ALTER TABLE sheet DROP FOREIGN KEY FK_873C91E27E3C61F9');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1A76ED395');
        $this->addSql('ALTER TABLE user_activate_account_token DROP FOREIGN KEY FK_389090CDA76ED395');
        $this->addSql('ALTER TABLE user_forgotten_password_token DROP FOREIGN KEY FK_42C0A3A4A76ED395');
        $this->addSql('DROP TABLE admin_activate_account_token');
        $this->addSql('DROP TABLE admin_forgotten_password_token');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE admin_event');
        $this->addSql('DROP TABLE billing_info');
        $this->addSql('DROP TABLE cart_row');
        $this->addSql('DROP TABLE cart_step');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE category_type');
        $this->addSql('DROP TABLE category_translation');
        $this->addSql('DROP TABLE change_mail_token');
        $this->addSql('DROP TABLE content');
        $this->addSql('DROP TABLE content_translation');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_translation');
        $this->addSql('DROP TABLE happening_category');
        $this->addSql('DROP TABLE happening_category_translation');
        $this->addSql('DROP TABLE happening_translation');
        $this->addSql('DROP TABLE happening_speaker');
        $this->addSql('DROP TABLE speaker_translation');
        $this->addSql('DROP TABLE happening_talking');
        $this->addSql('DROP TABLE happening');
        $this->addSql('DROP TABLE happening_participation');
        $this->addSql('DROP TABLE meeting_message');
        $this->addSql('DROP TABLE meeting_request');
        $this->addSql('DROP TABLE meeting_request_from_participants');
        $this->addSql('DROP TABLE meeting_request_to_participants');
        $this->addSql('DROP TABLE meeting');
        $this->addSql('DROP TABLE meeting_from_participants');
        $this->addSql('DROP TABLE meeting_to_participants');
        $this->addSql('DROP TABLE meeting_slot');
        $this->addSql('DROP TABLE nomenclature');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE order_promotion_code');
        $this->addSql('DROP TABLE order_row');
        $this->addSql('DROP TABLE _order');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE package_group');
        $this->addSql('DROP TABLE package_group_translation');
        $this->addSql('DROP TABLE package_option');
        $this->addSql('DROP TABLE package_plan');
        $this->addSql('DROP TABLE package_translation');
        $this->addSql('DROP TABLE participant');
        $this->addSql('DROP TABLE product_feature');
        $this->addSql('DROP TABLE product_feature_translation');
        $this->addSql('DROP TABLE product_product_included');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_translation');
        $this->addSql('DROP TABLE promotion');
        $this->addSql('DROP TABLE promotion_code');
        $this->addSql('DROP TABLE promotion_code_row');
        $this->addSql('DROP TABLE promotion_code_translation');
        $this->addSql('DROP TABLE rule');
        $this->addSql('DROP TABLE sheet_comment');
        $this->addSql('DROP TABLE sheet');
        $this->addSql('DROP TABLE spot');
        $this->addSql('DROP TABLE template_registration');
        $this->addSql('DROP TABLE sheet_template');
        $this->addSql('DROP TABLE trace');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE type');
        $this->addSql('DROP TABLE type_translation');
        $this->addSql('DROP TABLE unavailability');
        $this->addSql('DROP TABLE user_activate_account_token');
        $this->addSql('DROP TABLE user_forgotten_password_token');
        $this->addSql('DROP TABLE user');
    }
}
