Proximum\Vimeet\Application\Command\Product\Plan\CreatePlan:
    properties:
        name:
            - NotBlank: ~
        unitPrice:
            - NotBlank: ~
            - Range:
                min: 0
        vat:
            - NotBlank: ~
            - Range:
                min: 0
        file:
            - Image:
                maxSize: 500k
        availabilityCurrent:
            - Range:
                min: 0
        availabilityMax:
            - Range:
                min: 0
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
                        heading:
                            - NotBlank: ~
                        description: ~
                        addon: ~
                        subjectedToValidationHelp: ~
        features:
            - All:
                - Collection:
                    fields:
                        translations:
                            - All:
                                - Collection:
                                    fields:
                                        title:
                                            - NotBlank: ~
                                        description: ~
        productIncluded:
            - All:
                - Collection:
                    fields:
                        quantity:
                            - NotBlank: ~
                            - Range:
                                min: 0
                        product:
                            - NotBlank: ~
