imports:
    # - { resource: config.yml }
    - { resource: services_test.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        handler_id: ~
    profiler:
        collect: false
    translator:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    spool:
        type: file

doctrine:
    dbal:
        dbname: "%database_name%_test"
        driver_class: Proximum\Vimeet\Behat\DBAL\Driver\PDOMySql\Driver

# hautelook_alice:
#     db_drivers:
#         orm: ~
#     locale: fr_FR
#     seed: 1
#     persist_once: false
#     loading_limit: 5
