imports:
    - { resource: config.yml }
    - { resource: services_prod.yml }
    - { resource: packages/snc_redis.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
snc_redis:
    clients:
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%redis_dsn%/2'
            logging: '%kernel.debug%'
    # doctrine:
    #     metadata_cache:
    #         client: doctrine
    #         entity_manager: default
    #         document_manager: default
    #         namespace: '%app_version%:'
    #     query_cache:
    #         client: doctrine
    #         entity_manager: default
    #         namespace: '%app_version%:'
