imports:
    - { resource: parameters.yml }
    # - { resource: security.yml }
    # - { resource: services.yml }
    - { resource: elasticsearch.yml }
    - { resource: packages/knpu_oauth2_client.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    # should be set to deployed version hash on k8s environments
    app_version: '%env(APP_VERSION)%'
    env(APP_VERSION): dev
    mailer_sender: '%env(MAILER_SENDER)%'

framework:
    # esi: { enabled: true }
    # translator:
    #     fallbacks: ["%locale%"]
    #     logging: false
    # secret:          "%secret%"
    # router:
    #     resource: "%kernel.project_dir%/app/config/routing.yml"
    #     strict_requirements: ~
    form:            ~
    # csrf_protection: ~
    validation:      { enable_annotations: false }
    serializer:      { enable_annotations: false }
    templating:
        engines: ['twig']
    # default_locale:  "%locale%"
    trusted_hosts:   ~
#    trusted_proxies: "%trusted_proxies%"
    # session:
    #     cookie_secure:   true
    #     handler_id:      snc_redis.session.handler
    #     name:            vimeet
    #     gc_probability:  ~
    #     cookie_lifetime: 86400
    #     gc_maxlifetime:  86400
    fragments: { path: /_fragment }
    # http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
    php_errors:
        log: true

sensio_framework_extra:
    router:
        annotations: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "@Ui/layout.html.twig"
    date:
        timezone: Europe/Paris
    paths:
        "%kernel.project_dir%/src/Ui/Resources/views": Ui
    globals:
        admin_menu_color: "%admin_menu_color%"
        visio_screen_sharing_chrome_extension: "%visio_screen_sharing_chrome_extension%"
        networking_template_snippet: "@Proximum\\Vimeet\\Ui\\Bundle\\EventBundle\\TemplateSnippet\\NetworkingTemplateSnippet"

# Doctrine Configuration
doctrine:
    # dbal:
    #     server_version: 5.6
    #     driver:   pdo_mysql
    #     host:     "%database_host%"
    #     port:     "%database_port%"
    #     dbname:   "%database_name%"
    #     user:     "%database_user%"
    #     password: "%database_password%"
    #     charset:  UTF8
    #     schema_filter: ~^(?!sessions)~
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            entity:
                type: yml
                prefix: Proximum\Vimeet\Domain\Model
                dir: "%kernel.project_dir%/src/Infrastructure/Bundle/InfrastructureBundle/Resources/config/doctrine/entity"
                alias: Entity
                is_bundle: false
        dql:
            string_functions:
                MD5: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Doctrine\Extension\Md5

# Sonata Intl Configuration
sonata_intl:
    timezone:
        default: Europe/Paris

# From translation
elao_form_translation:
    auto_generate: true

services:
    twig.extension.text:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

infrastructure:
    eu_countries: ['at', 'be', 'bg', 'hr', 'cy', 'cz', 'dk', 'ee', 'fi', 'fr', 'de', 'gr', 'hu', 'ie', 'it', 'lv', 'lt', 'lu', 'mt', 'nl', 'pl', 'pt', 'ro', 'sk', 'si', 'es', 'se']
    preferred_locales: ['fr', 'en', 'es', 'de', 'it', 'zh']
    default_locales: ['fr', 'en']
    supported_currencies: ['EUR', 'GBP', 'USD']
    web_asset_event_guideline_path: 'css/event'
    bundle_guideline_path: "%kernel.project_dir%/src/Ui/Bundle/EventBundle/Resources/assets/sass"
    font_path: "/assets/fonts"
    image_path: "/assets/images"
    print_planning_path: '%kernel.project_dir%/public/uploads/print_planning'
    print_sheet_path: '%kernel.project_dir%/public/uploads/print_sheet'
    export_transactions_path: '%kernel.project_dir%/public/uploads/export_transactions'
    export_order_path: '%kernel.project_dir%/public/uploads/export_orders'
    export_products_path: '%kernel.project_dir%/public/uploads/export_products'
    export_planner_path: '%kernel.project_dir%/public/uploads/export_planner'
    import_planner_path: '%kernel.project_dir%/public/uploads/import_planner'
    import_spot_path: '%kernel.project_dir%/public/uploads/import_spots/'
    import_authentication_token_path: '%shared_uploaded_files%/import_authentication_tokens/'
    encrypted_files_path: '%shared_uploaded_files%/encrypted_files/'
    export_omz_path: '%kernel.project_dir%/public/uploads/export_omz'
    common_export_path: '%shared_uploaded_files%/export/'
    export_participant_path: '%shared_uploaded_files%/export/participant/'
    export_spot_path: '%kernel.project_dir%/public/uploads/export_spot'
    export_form_template_user_data_path: '%shared_uploaded_files%/export/form-template/'
    export_rooming_list_path: '%shared_uploaded_files%/export/rooming-list/'
    print_invoices_path: '%shared_uploaded_files%/export/invoices'
    package:
        default_labels:
            plans:
                fr: Forfait
                en: Plans
            participant_and_planning:
                fr: Participant et planning
                en: Participant and Planning
            options:
                fr: Options
                en: Options

tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.doctrine_rollback_only
                - tactician.middleware.command_handler
        query:
            middleware:
                - tactician.middleware.validator
                - tactician.middleware.command_handler

#
# Liip Imagine Bundle
#
liip_imagine:
    driver: gd
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - "%liip_imagine_data_root%"
    filter_sets:
        cache: ~
        event_header_logo:
            quality: 100
            filters:
                thumbnail: { size: [250, 100], mode: inset }
        event_sheet_image:
            quality: 100
            filters:
                thumbnail: { size: [800, 320], mode: inset }
        user_avatar:
            quality: 100
            filters:
                # Use the "outbound" mode to crop the image when the size ratio of the input differs
                thumbnail: { size: [160, 160], mode: outbound }
                # fix orientation issue for example for iOS photo
                auto_rotate: ~
        upload_object:
            quality: 100
            filters:
                thumbnail: { size: [160, 160], mode: inset }
        program_company_logo:
            quality: 100
            filters:
                thumbnail:  { size: [250, 100], mode: inset }

# Doctrine migrations configuration
# doctrine_migrations:
#     dir_name: "%kernel.project_dir%/src/Infrastructure/Bundle/InfrastructureBundle/Migrations"
#     namespace: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Migrations
#     table_name: migration_versions
#     name: Application Migrations

# payum:
#     security:
#         token_storage:
#             Proximum\Vimeet\Domain\Model\Payment\PaymentToken: { doctrine: orm }
#     storages:
#         Proximum\Vimeet\Domain\Model\Payment\Payment: { doctrine: orm }
#     gateways:
#         paypal_express_checkout:
#             factory: paypal_express_checkout
#             username:  "%paypal_username%"
#             password:  "%paypal_password%"
#             signature: "%paypal_signature%"
#             sandbox:   "%paypal_sandbox%"
#             payum.action.store_notification: '@vimeet.payum.paypal.action.store_notification'
#         offline:
#             factory: offline

# Sentry configuration (Data source name)
sentry:
    dsn: "%sentry_dsn%"
    options:
        environment: "%kernel.environment%"
        error_types: E_ALL & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED & ~E_USER_NOTICE & ~E_USER_WARNING & ~E_NOTICE & ~E_COMPILE_WARNING & ~E_CORE_WARNING
        excluded_exceptions:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
            - Proximum\Vimeet\Application\Exception\Sheet\SheetNotFoundException

coop_tilleuls_ovh:
    endpoint_name:      "%ovh_endpoint_name%"
    application_key:    "%ovh_application_key%"
    application_secret: "%ovh_application_secret%"
    consumer_key:       "%ovh_consumer_key%"
