fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%", retryOnConflict: 2 }
    indexes:
        sheet:
            index_name: "app_%kernel.environment%_sheet"
            settings:
                index:
                    max_result_window: 100000
                    analysis:
                        analyzer:
                            lowercaseAnalyzer:
                                tokenizer: "keyword"
                                filter: "lowercase"
                            sheetAnalyzer:
                                tokenizer: "standard"
                                filter: ["standard", "lowercase"]
                            emailAnalyzer:
                                tokenizer: "uax_url_email"
                            autocomplete:
                                type: custom
                                tokenizer: "standard"
                                filter: ["standard", "lowercase", "autocomplete_filter", "asciifolding"]
                        filter:
                            autocomplete_filter:
                                type: edge_ngram
                                side: front
                                min_gram: 3
                                max_gram: 20
            types:
                sheet:
                    properties:
                        id:
                            type: integer
                            index: false
                        sheetName:
                            type: text
                            analyzer: "sheetAnalyzer"
                            fielddata: true
                            fields:
                                raw:
                                    type: text
                                    analyzer: "lowercaseAnalyzer"
                                    fielddata: true
                                autocomplete:
                                    type: text
                                    analyzer: "autocomplete"
                        content:
                            type: text
                        content_en:
                            type: text
                            analyzer: "english"
                        content_fr:
                            type: text
                            analyzer: "french"
                        state:
                            type: keyword
                        validationState:
                            type: keyword
                        agendaConfirmedStatus:
                            type: keyword
                        phoneValidationStatus:
                            type: keyword
                        availabilityConfirmationStatus:
                            type: keyword
                        enabled:
                            type: boolean
                        completed:
                            type: boolean
                        completeness:
                            type: integer
                        categories:
                            type: nested
                        booleanFilter:
                            type: nested
                            properties:
                                key:
                                    type: text
                        nestedTaggedData:
                            type: nested
                            properties:
                                tag:
                                    type: text
                                values:
                                    type: nested
                                    properties:
                                        tag:
                                            type: text
                                        value:
                                            type: text
                                            fielddata: true
                        filledFilter:
                            type: nested
                            properties:
                                key:
                                    type: keyword
                                status:
                                    type: keyword
                        type:
                            type: integer
                        followUp:
                            type: integer
                            null_value: 0
                        commercialStatus:
                            type: text
                        participantNumber:
                            type: integer
                        participants:
                            type: nested
                            properties:
                                lastname:
                                    type: text
                                    analyzer: "sheetAnalyzer"
                                email:
                                    type: text
                                    analyzer: "emailAnalyzer"
                                position:
                                    type: keyword
                        event:
                            type: integer
                        owner:
                            type: integer
                        ownerEmail:
                            type: text
                        lastLoginAt:
                            type: date
                        imported:
                            type: boolean
                        createdAt:
                            type: date
                        remainingToPay:
                            type: float
                        inCatalog:
                            type: boolean
                        inCatalogAt:
                            type: date
                        orderStatus:
                            type: text
                        hasCart:
                            type: boolean
                        hasHappeningParticipation:
                            type: boolean
                        hasMeetingRequest:
                            type: boolean
                        hasPendingMeetingProposition:
                            type: boolean
                        hasScheduledMeeting:
                            type: boolean
                        hasInvoice:
                            type: boolean
                        hasSpot:
                            type: boolean
                        spotReference:
                            type: text
                        attend:
                            type: boolean
                        hasGroup:
                            type: boolean
                        reminderDate:
                            type: date
                        organizationCategory:
                            type: keyword
                        nomenclatureItems:
                            type: nested
                            properties:
                                key:
                                    type: text
                        messagesReceived:
                            type: nested
                            properties:
                                key:
                                    type: integer
                        nomenclatureItemsSupply:
                            type: nested
                            properties:
                                key:
                                    type: text
                        nomenclatureItemsNeeds:
                            type: nested
                            properties:
                                key:
                                    type: text
                        zipcode:
                            type: keyword
                        countryCode:
                            type: text
                            fielddata: true
                        city:
                            type: text
                            fields:
                                city_autocomplete:
                                    analyzer: "autocomplete"
                                    type: text
                                    index: true
                            analyzer: "lowercaseAnalyzer"
                            fielddata: true
                        country:
                            type: nested
                            properties:
                                label:
                                    type: text
                                    analyzer: "lowercaseAnalyzer"
                                    fielddata: true
                                label_autocomplete:
                                    type: text
                                    analyzer: "autocomplete"
                                locale:
                                    type: keyword
                                    index: true
                        keywords:
                            type: nested
                            properties:
                                label:
                                    type: text
                                    analyzer: "lowercaseAnalyzer"
                                    fielddata: true
                                label_autocomplete:
                                    type: text
                                    analyzer: "autocomplete"
                                locale:
                                    type: keyword
                                    index: true
                        availableSlotIds:
                            type: nested
                            properties:
                                id:
                                    type: long
                    persistence:
                        elastica_to_model_transformer:
                            ignore_missing: true
                        model_to_elastica_transformer:
                            service: transformer.elastic.sheet_elastic_transformer
                        driver: orm
                        model: Proximum\Vimeet\Domain\Model\Sheet
                        provider: ~
                        listener: ~
                        finder: ~

        user_event:
            index_name: "app_%kernel.environment%_user_event"
            settings:
                index:
                    max_result_window: 100000
                    analysis:
                        analyzer:
                            lowercaseAnalyzer:
                                tokenizer: "keyword"
                                filter: "lowercase"
                            emailAnalyzer:
                                tokenizer: "uax_url_email"
                            autocomplete:
                                type: custom
                                tokenizer: "standard"
                                filter: ["standard", "lowercase", "autocomplete_filter", "asciifolding"]
                        filter:
                            autocomplete_filter:
                                type: edge_ngram
                                side: front
                                min_gram: 3
                                max_gram: 20
            types:
                user_event:
                    persistence:
                        model: Proximum\Vimeet\Domain\UserEventView\UserEventView
                        provider: ~
                        listener: ~
                        finder: ~
