default:
    path: /
    host: '%domain%'
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true
    methods: [GET]

default_event:
    path: /
    methods: [GET]

vimeet_admin:
    resource: '@VimeetAppBundle/Resources/config/routing/admin.yml'
    prefix:   /admin/{_locale}
    requirements:
        _locale: fr|en
    defaults:
        _locale: %locale%
    host:     '%domain%'

vimeet_event:
    resource: '@VimeetAppBundle/Resources/config/routing/event.yml'
    prefix:   /{_locale}
    defaults:
        _locale: %locale%
