# _errors:
#     resource: "@TwigBundle/Resources/config/routing/errors.xml"
#     prefix:   /_error

admin_login_user:
    path:     /{_locale}/login/{admin}
    host:     '%admin_domain%'
    methods:  [GET]
    defaults: { _controller: AdminBundle:Security:loginUser }

event_login_user:
    path:     /{_locale}/login/{user}
    methods:  [GET]
    defaults: { _controller: EventBundle:Security:loginUser }

_main:
    resource: routing.yml
