default:
    pattern: /
    host: "%domain%"
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true
    methods: [GET]

default_event:
    path: /
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods: [GET]

vimeet_admin:
    resource: "@VimeetAppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

vimeet_event:
    resource: "@VimeetAppBundle/Resources/config/routing/event.yml"
    prefix:   /{_locale}
    defaults:
        _locale: %locale%
