_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

event_login_user:
    path:     /{_locale}/login/{user}
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Security:loginUser }

admin_login_user:
    path:     /admin/{_locale}/login/{admin}
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Security:loginUser }

_main:
    resource: routing.yml
