# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Proximum\Vimeet\Domain\Model\User:
            algorithm: sha1
            iterations: 5
            encode_as_base64: true

    providers:
        user_provider:
            entity:
                class: Proximum\Vimeet\Domain\Model\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_provider
            form_login:
                login_path: event_login
                check_path: event_login_check
                default_target_path: event
                use_referer: true
            logout:
                path: event_logout
                target: event
