services:
    infrastructure.adapter.monolog_smssender_adapter:
        class: Proximum\Vimeet\Infrastructure\Adapter\MonologSMSSenderAdapter
        arguments:
            - '@logger'

    adapter.smssender_alias: '@infrastructure.adapter.monolog_smssender_adapter'

    adapter.sendgrid_api_adapter:
        class: Proximum\Vimeet\Infrastructure\Adapter\FakeEmailingSenderAdapter
        arguments:
            - '@logger'

    #
    # Fixture providers
    #
    vimeet_infrastructure.data_fixtures_orm.provider:
        class: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\DataFixtures\ORM\Provider
        arguments:
            - '%domain%'
        tags:
            - { name: hautelook_alice.faker.provider }
