Proximum\Vimeet\Application\Command\Type\Create:
    properties:
        template:
            - NotBlank: ~
        sheetTemplate:
            - NotBlank: ~
        registrationTemplate:
            - NotBlank:
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
