Proximum\Vimeet\Application\Command\Type\Update:
    properties:
        sheetTemplate:
            - NotBlank: ~
        registrationTemplate:
            - NotBlank: ~
        package:
            - NotBlank: ~
        numberOfMeetingsPerPlanning:
            - Type: {type: integer}
            - GreaterThanOrEqual: 0
        priorityMeetingRequestsNumber:
            - Type: {type: integer}
            - NotBlank: ~
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
                        description: ~
