Proximum\Vimeet\Application\Command\Meeting\Update:
    properties:
        meeting:
            - NotBlank: ~
        sheet:
            - NotBlank: ~
        participants:
            - Count:
                min: 1
