dependencies:
- name: mysql
  version: 1.4.0
  repository: https://storage.googleapis.com/synalabs-kubernetes-charts/
  condition: mysql.enabled
- name: elasticsearch
  version: 7.7.0-SNAPSHOT
  repository: https://storage.googleapis.com/synalabs-kubernetes-charts/
  condition: elasticsearch.enabled
- name: redis
  version: 9.4.3
  repository: https://storage.googleapis.com/synalabs-kubernetes-charts/
  condition: redis.enabled
