version: 2

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge
    environment:
      COMPOSE_FILE: "docker-compose.yaml"
    steps:
      - checkout
      - restore_cache:
          name: "[cache] restoring composer"
          keys:
            - composer-{{ .Branch }}-{{ checksum "composer.lock" }}
            - composer-master-{{ checksum "composer.lock" }}
            - composer-master
      - restore_cache:
          name: "[cache] restoring packages"
          keys:
            - package-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - package-master-{{ checksum "package-lock.json" }}
            - package-master
      - restore_cache:
          key: dockerize-{{ arch }}-v0.6.1
      - run:
          name: "install dockerize if not found in cache"
          command:
                if \[ -f /usr/local/bin/dockerize \]; then
                    echo "dockerize found; skipping installation";
                    else wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
                        && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
                        && rm dockerize-linux-amd64-v0.6.1.tar.gz;
                    fi
      - run:
          name: "[build] install the project"
          command: |
            docker network create proxy
            cp app/config/parameters_circle.yml app/config/parameters.yml
            docker-compose -p vimeet up -d
            sleep 10
            dockerize -wait tcp://localhost:3306 -timeout 1m
            docker-compose -p vimeet exec php make install-app@test
            dockerize -wait tcp://localhost:3306 -timeout 1m
            docker-compose -p vimeet exec php make install-app@test
            docker-compose -p vimeet exec php make install-db@test
            docker-compose -p vimeet exec php make install-dep
            docker-compose -p vimeet exec php make build@prod
      - run:
          name: "[test] phpunit"
          command: |
            docker-compose -p vimeet exec php bin/phpunit
      - run:
          name: "[test] behat"
          command: |
            docker-compose -p vimeet exec php php bin/console fos:elastica:reset --env=test --no-debug
            docker-compose -p vimeet exec php php -d memory_limit=-1 bin/behat --format progress --no-interaction
      - save_cache:
          name: "[cache] saving composer"
          key: composer-{{ .Branch }}-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - save_cache:
          name: "[cache] saving packages"
          key: package-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: dockerize-{{ arch }}-v0.6.0
          paths:
            - /usr/local/bin/dockerize
