#
# Event
#

admin_event_list:
    path: /event
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Event:list }

admin_event_update:
    path: /event/{id}/update
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Event:update }

#
# See
#

admin_see_list:
    path: /event/{id}/who-see-who
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/See:list }

admin_who_see_who_dont_see_what:
    path: /event/{id}/{seerIdentifier}/{seerId}/see/{seeableIdentifier}/{seeableId}/dont-see
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/See:what }
    requirements:
        seerIdentifier: category|type
        seerId: \d+
        seeableIdentifier: category|type
        seeableId: \d+

admin_see_delete:
    path: /event/{id}/who-see-who/{see_id}/delete
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/See:delete }

#
# Type
#

admin_type_list:
    path: /event/{id}/type
    requirements:
        id: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Type:list }

admin_type_create:
    path: /event/{id}/type/create
    requirements:
        id: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Type:create }

admin_type_update:
    path: /event/{id}/type/{type_id}/update
    requirements:
        id: \d+
        type_id: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Type:update }
