#
# Event
#

admin_event_list:
    path: /event
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Event:list }

admin_event_update:
    path: /event/{event}/update
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Event:update }

#
# Rule
#

admin_rule_list:
    path: /event/{event}/who-see-who
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Rule:list }

admin_who_see_who_dont_see_what:
    path: /event/{event}/{seerIdentifier}/{seerId}/see/{seeableIdentifier}/{seeableId}/dont-see
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Rule:what }
    requirements:
        event: \d+
        seerIdentifier: category|type
        seerId: \d+
        seeableIdentifier: category|type
        seeableId: \d+

admin_rule_delete:
    path: /event/{event}/who-see-who/{rule}/delete
    methods: [DELETE]
    defaults: { _controller: VimeetAppBundle:Admin/Rule:delete }

#
# Type
#

admin_type_list:
    path: /event/{event}/type
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Type:list }

admin_type_create:
    path: /event/{event}/type/create
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Type:create }

admin_type_update:
    path: /event/{event}/type/{type}/update
    requirements:
        event: \d+
        type: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Type:update }

admin_type_template_field_list:
    path: /event/{event}/type/{type}/form
    requirements:
        event: \d+
        type: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/TypeTemplateField:list }

admin_type_template_field_update:
    path: /event/{event}/type/{type}/form/field/update/{template}/{key}
    requirements:
        event: \d+
        type: \d+
        template: \w+
        key: \w+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/TypeTemplateField:fieldUpdate }

#
# Category
#

admin_category_list:
    path: /event/{event}/category
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Category:list }

admin_category_create:
    path: /event/{event}/category/create
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Category:create }

admin_category_update:
    path: /event/{event}/category/{category}/update
    requirements:
        event: \d+
        category: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Category:update }

#
# Meeting
#

admin_meeting_list:
    path: /event/{event}/meeting
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Meeting:list }

#
# Spot
#

admin_spot_list:
    path: /event/{event}/spot
    requirements:
        event: \d+
    methods: [GET,POST]
    defaults: { _controller: VimeetAppBundle:Admin/Spot:list }

admin_spot_create:
    path: /event/{event}/spot/create
    requirements:
        event: \d+
    methods: [GET , POST]
    defaults: { _controller: VimeetAppBundle:Admin/Spot:create }

admin_spot_batch_create:
    path: /event/{event}/spot/create/batch
    requirements:
        event: \d+
    methods: [GET , POST]
    defaults: { _controller: VimeetAppBundle:Admin/Spot:batchCreate }

#
# Meeting Request
#

admin_meeting_request_list:
    path: /event/{event}/meeting-request
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/MeetingRequest:list }

admin_meeting_request_position:
    path: /event/{event}/meeting-request/{meetingRequest}/position
    requirements:
        event: \d+
        meetingRequest: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/MeetingRequest:position }

admin_meeting_request_details:
    path: /event/{event}/meeting-request/{meetingRequest}/details
    requirements:
        event: \d+
        meetingRequest: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/MeetingRequest:showDetail }

admin_meeting_request_slots:
    path: /event/{event}/meeting-request/{meetingRequest}/slots
    requirements:
        event: \d+
        meetingRequest: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/MeetingRequest:slots }

#
# Sheet
#
admin_sheet:
    path: /event/{event}/sheet
    requirements:
        id: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Sheet:list }

#
# Billing
#
admin_sheet_billing:
    path: /event/{event}/sheet/{sheet}/billing
    requirements:
        event: \d+
        sheet: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Billing:list }

#
# Order
#
admin_sheet_order_edit:
    path: /order/{order}/edit
    requirements:
        order: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Order:edit }
admin_sheet_order_add_row:
    path: /order/{order}/group/{group}/row/add
    requirements:
        order: \d+
        group: '[a-zA-Z0-9\-]+'
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Order:addRow }
admin_sheet_order_remove_row:
    path: /order/{order}/group/{group}/row/{row}/remove
    requirements:
        order: \d+
        group: '[a-zA-Z0-9\-]+'
        row: '[a-zA-Z0-9\-]+'
    methods: [DELETE]
    defaults: { _controller: VimeetAppBundle:Admin/Order:removeRow }
admin_sheet_order_update_row:
    path: /order/{order}/group/{group}/row/{row}/update
    requirements:
        order: \d+
        group: '[a-zA-Z0-9\-]+'
        row: '[a-zA-Z0-9\-]+'
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Order:updateRow }

#
# Transaction
#
admin_sheet_transaction_create:
    path: /sheet/{sheet}/transaction/create
    requirements:
        sheet: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Transaction:create }
admin_sheet_transaction_update:
    path: /sheet/{sheet}/transaction/{transaction}/update
    requirements:
        sheet: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Transaction:update }
admin_sheet_transaction_remove:
    path: /sheet/{sheet}/transaction/{transaction}/remove
    requirements:
        sheet: \d+
    methods: [DELETE]
    defaults: { _controller: VimeetAppBundle:Admin/Transaction:remove }

#
# Happening
#
admin_happening_list:
    path: /event/{event}/happening
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Happening:list }
admin_happening_create:
    path: /event/{event}/happening/create
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Happening:create }
admin_happening_update:
    path: /event/{event}/happening/{happening}/update
    requirements:
        event: \d+
        happening: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Happening:update }

#
# Happening Category
#
admin_happening_category_list:
    path: /event/{event}/happening/category
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Happening:listCategory }
admin_happening_category_create:
    path: /event/{event}/happening/category/create
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Happening:createCategory }
admin_happening_category_update:
    path: /event/{event}/happening/category/{category}/update
    requirements:
        event: \d+
        category: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Happening:updateCategory }

#
# Happening Speaker
#
admin_happening_speaker_list:
    path: /event/{event}/happening/speaker
    requirements:
        event: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Speaker:list }
admin_happening_speaker_create:
    path: /event/{event}/happening/speaker/create
    requirements:
        event: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Speaker:create }
admin_happening_speaker_update:
    path: /event/{event}/happening/speaker/{speaker}/update
    requirements:
        event: \d+
        speaker: \d+
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Admin/Speaker:update }
admin_happening_speaker_read:
    path: /event/{event}/happening/speaker/{speaker}/read
    requirements:
        event: \d+
        speaker: \d+
    methods: [GET]
    defaults: { _controller: VimeetAppBundle:Admin/Speaker:read }
admin_happening_speaker_delete:
    path: /event/{event}/happening/speaker/{speaker}/delete
    requirements:
        event: \d+
        speaker: \d+
    methods: [DELETE]
    defaults: { _controller: VimeetAppBundle:Admin/Speaker:delete }
