#
# Event home
#

event:
    path: /
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Home:index }

#
# Register
#

event_register:
    path: /register/{typeView}
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Home:register }

#
# Change mail
#
event_account:
    path: /account
    methods: [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Account:update }

event_activate_new_mail:
    path: /account/change_mail/{token}
    methods: [GET]
    requirements:
        token: \w+
    defaults: { _controller: VimeetAppBundle:Event/Account:activateNewMail }

#
# Forgot password
#

event_forgotten_password:
    path: /forgotten_password
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/ForgottenPassword:forgottenPassword }

event_create_new_password:
    path: /reset_password/{token}
    methods:  [GET, POST]
    requirements:
        token: \w+
    defaults: { _controller: VimeetAppBundle:Event/ForgottenPassword:createNewPassword }

#
# Activate account
#

event_activate_account:
    path: /activate/{token}
    methods: [GET, POST]
    requirements:
        token: \w+
    defaults: { _controller: VimeetAppBundle:Event/ActivateAccount:password }

#
# Join event
#

event_participate:
    path: /participate/{typeView}
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Home:participate }

#
# Sheet
#

event_sheet:
    path:     /sheet/{sheet}
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:sheet }

event_sheet_add_participant:
    path:     /sheet/{sheet}/add_participant
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:addParticipant }

event_sheet_update_participant:
    path:     /sheet/{sheet}/update_participant/{participant}
    requirements:
        sheet: \d+
        participant: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:updateParticipant }

event_sheet_update_block:
    path:     /sheet/{sheet}/update_block/{block}
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:updateBlock }

event_sheet_delete_participant:
    path:     /sheet/{sheet}/delete_participant/{participant}
    requirements:
        sheet: \d+
        participant: \d+
    methods:  [DELETE]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:deleteParticipant }

event_sheet_package_update_step:
    path:     /sheet/{sheet}/update_step/{step}
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Package:updateStep }

event_sheet_package_products:
    path: /sheet/{sheet}/products/add
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Package:addProducts }

event_sheet_product_update:
    path: /sheet/{sheet}/products/update/{groupId}/{rowId}
    requirements:
        sheet: \w+
        groupId: \w+
        rowId: \w+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Package:updateProduct }

event_sheet_package_cart:
    path:     /sheet/{sheet}/cart
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Package:cart }

event_sheet_billing:
    path:     /sheet/{sheet}/billing
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Billing:billing }

event_sheet_package_payment_mode:
    path:     /sheet/{sheet}/payment_mode
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Billing:paymentMode }

event_sheet_list_orders:
    path:     /sheet/{sheet}/orders
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Order:listOrder }

event_sheet_summary:
    path:      /sheet/{sheet}/summary
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Order:summary }

event_sheet_order_pro_forma:
    path:     /sheet/{sheet}/pro_forma/{order}
    requirements:
        sheet: \d+
        order: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Order:proforma }

#
# Authentication
#

event_login:
    path:     /login
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Security:login }

event_login_check:
    path:     /login_check
    methods:  [POST]

event_logout_confirmation:
    path:     /logout-confirmation
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Security:logoutConfirmation }

event_logout:
    path:     /logout
    methods:  [GET]

event_change_password:
    path:     /change-password
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/ChangePassword:changePassword }

#
# Catalog
#

event_catalog:
    path: /catalog
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Catalog:categories }

event_catalog_category:
    path: /catalog/{categoryView}
    requirements:
        categoryView: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Catalog:category }

event_catalog_sheet:
    path: /catalog/{categoryView}/sheet/{sheet}
    requirements:
        categoryView: \d+
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Catalog:sheet }

event_catalog_sheet_meeting_request:
    path: /catalog/{categoryView}/sheet/{to}/meeting/request/from/{from}
    requirements:
        categoryView: \d+
        to: \d+
        from: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:createRequest }

#
# Schedule
#

event_sheet_schedule:
    path: /sheet/{sheet}/schedule
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:display }

event_sheet_schedule_add_unavailability:
    path: /sheet/{sheet}/schedule/unavailability/add
    requirements:
        sheet: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:addUnavailability }

event_sheet_schedule_update_unavailability:
    path: /sheet/{sheet}/schedule/unavailability/{unavailability}/update
    requirements:
        sheet: \d+
        unavailability: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:updateUnavailability }

event_sheet_schedule_remove_unavailability:
    path: /sheet/{sheet}/schedule/unavailability/{unavailability}/remove
    requirements:
        sheet: \d+
        unavailability: \d+
    methods:  [DELETE]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:removeUnavailability }

event_sheet_schedule_participate_happening:
    path: /sheet/{sheet}/happening/{happening}/participate
    requirements:
        sheet: \d+
        happening: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:participateHappening }

event_sheet_schedule_unparticipate_happening:
    path: /sheet/{sheet}/happening/{happening}/unparticipate/{participant}
    requirements:
        sheet: \d+
        happening: \d+
        participant: \d+
    methods:  [POST]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:unparticipateHappening }

#
# Meeting
#

event_sheet_schedule_meeting:
    path: /sheet/{sheet}/meeting/{meeting}
    requirements:
        sheet: \d+
        meeting: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Meeting:display }

event_sheet_schedule_meeting_cancel:
    path: /sheet/{sheet}/meeting/{meeting}/cancel
    requirements:
        sheet: \d+
        meeting: \d+
    methods:  [GET, DELETE]
    defaults: { _controller: VimeetAppBundle:Event/Meeting:cancel }

event_sheet_schedule_meeting_update:
    path: /sheet/{sheet}/meeting/{meeting}/update
    requirements:
        sheet: \d+
        meeting: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Meeting:update }

#
# Meeting Request
#
event_meeting_list_request:
    path: /sheet/{sheet}/meeting/request
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:listRequest }

event_meeting_list_proposition:
    path: /sheet/{sheet}/meeting/proposition
    requirements:
        sheet: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:listProposition }

event_meeting_request_approve:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/approve
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:approveRequest }

event_meeting_request_refuse:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/refuse
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:refuseRequest }

event_meeting_request_cancel:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/cancel
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:cancelRequest }

event_meeting_request_show:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:showRequest }

event_meeting_request_edit:
    path: /sheet/{sheet}/meeting/request/{meetingRequest}/edit
    requirements:
        sheet: \d+
        meetingRequest: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/MeetingRequest:editRequest }

#
# Notification
#
event_notification_list:
    path:     /notification
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Notification:list }
event_notification_read:
    path:     /notification/{notification}/read
    requirements:
        notification: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Notification:read }
