#
# Event home
#

event:
    path: /
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Home:index }

#
# Register
#

event_register:
    path: /register/{typeView}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Home:register }

#
# Forgot password
#

event_forgotten_password:
    path: /forgotten_password
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/ForgottenPassword:forgottenPassword }

event_create_new_password:
    path: /reset_password/{token}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/ForgottenPassword:createNewPassword }

#
# Join event
#

event_participate:
    path: /participate/{typeView}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Home:participate }

#
# Sheet
#

event_sheet:
    path: /sheet/{id}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:sheet }

event_sheet_add_participant:
    path: /sheet/{id}/add_participant
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:addParticipant }

event_sheet_buy_participant:
    path: /sheet/{id}/buy_participant
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:buyParticipant }

event_sheet_update_participant:
    path: /sheet/{id}/update_participant/{participant_id}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:updateParticipant }

event_sheet_update_block:
    path: /sheet/{id}/update_block/{block}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:updateBlock }

event_sheet_delete_participant:
    path: /sheet/{id}/delete_participant/{participant_id}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [DELETE]
    defaults: { _controller: VimeetAppBundle:Event/Sheet:deleteParticipant }

event_sheet_package_update_step:
    path: /sheet/{id}/update_step/{step}
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Package:updateStep }

event_sheet_package_cart:
    path: /sheet/{id}/cart
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Package:cart }

event_sheet_billing_pro_forma:
    path: /sheet/{id}/pro_forma
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Billing:proForma }

event_sheet_billing:
    path: /sheet/{id}/billing
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Billing:billing }

event_sheet_package_payment_mode:
    path: /sheet/{id}/payment_mode
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Billing:paymentMode }

event_sheet_package_final_billing_step:
    path: /sheet/{id}/final
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Billing:finalBillingStep }

#
# Authentication
#

event_login:
    path: /login
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Security:login }

event_login_check:
    path: /login_check
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [POST]

event_logout_confirmation:
    path: /logout-confirmation
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Security:logoutConfirmation }

event_logout:
    path: /logout
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]

event_change_password:
    path: /change-password
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/ChangePassword:changePassword }

#
# Catalog
#

event_catalog:
    path: /catalog
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Catalog:categories }

event_catalog_category:
    path: /catalog/{categoryView}
    host: "{subdomain}.%domain%"
    requirements:
        categoryView: \d+
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Catalog:category }

event_catalog_sheet:
    path: /catalog/{categoryView}/sheet/{id}
    host: "{subdomain}.%domain%"
    requirements:
        categoryView: \d+
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Catalog:sheet }

#
# Schedule
#

event_sheet_schedule:
    path: /sheet/{id}/schedule
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
        id: \d+
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:display }

event_sheet_schedule_add_unavailability:
    path: /sheet/{id}/schedule/{schedule_id}/add-unavailability
    host: "{subdomain}.%domain%"
    requirements:
        subdomain: "[a-zA-Z0-9\-]+"
        id: \d+
        schedule_id: \d+
    methods:  [GET, POST]
    defaults: { _controller: VimeetAppBundle:Event/Schedule:addUnavailability }

#
# Meeting
#
event_meeting_list_request:
    path: /sheet/{id}/meeting/request
    host: "{subdomain}.%domain%"
    requirements:
        id: \d+
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Meeting:listRequest }

event_meeting_list_proposition:
    path: /sheet/{id}/meeting/proposition
    host: "{subdomain}.%domain%"
    requirements:
        id: \d+
        subdomain: "[a-zA-Z0-9\-]+"
    methods:  [GET]
    defaults: { _controller: VimeetAppBundle:Event/Meeting:listProposition }
