Proximum\Vimeet\Application\Command\Package\Step\SelectOptions:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Package\OptionsConstraint: ~
