Proximum\Vimeet\Application\Command\Participant\Add:
    properties:
        email:
            - NotBlank: ~
            - Email:
                strict: true
        product:
            - Expression:
                expression: "!this.needToSelectProduct or this.product !== null"
                message: "validators.participant.mustSelectProduct"
