Proximum\Vimeet\Application\Command\Participant\Add:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                strict: true
