Proximum\Vimeet\Application\Command\Participant\ImportMapping:
    constraints:
        - Expression:
            expression: "this.isEmailInMappings() === true"
            message: "validators.participant_imported.empty_mail_mapping"
    properties:
        mappings:
            - Valid: ~
