Proximum\Vimeet\Application\Command\Participant\Import:
    properties:
        type:
            - NotBlank: ~
        file:
            - NotBlank: ~
            - File:
                mimeTypes: ['text/plain', 'text/csv', 'application/csv', 'text/*']
                maxSize: 25M
        allowMultiSheet:
            - NotNull: ~

