---

############
# Strategy #
############

manala_deploy_strategy_git_version: preprod

############
# Releases #
############

manala_deploy_releases: 3

###########
# Removed #
###########

manala_deploy_removed:
  - web/app_test.php

#########
# Tasks #
#########

manala_deploy_tasks:
  - make: composer-install
  - make: install@prod
  - make: migration-and-redis-flushdb@prod

manala_deploy_post_tasks:
  - command: sudo /usr/sbin/service php7.2-fpm reload
  - command: sudo supervisorctl restart all
  - command: bin/console redis:flushdb --client=doctrine -n #flush the doctrine metadata and query cache
  - command: bin/console vimeet:translations:schedule-update vimeet@elao.com fr --env=prod
