---

############
# Strategy #
############

manala_deploy_strategy_git_version: prod

###########
# Removed #
###########

manala_deploy_removed:
  - web/app_dev.php
  - web/app_test.php


#########
# Tasks #
#########

manala_deploy_tasks:
  - make: composer-install
  - make: install@prod
  - make: build@prod
  - make: migration-and-redis-flushdb@prod
    when: "'deploy_prod_primary' in group_names"
  - command: sudo /usr/sbin/service php7.1-fpm reload
  - command: sudo supervisorctl restart all

manala_deploy_post_tasks:
  - command: vimeet:translations:schedule-update vimeet@elao.com fr --env=prod
    when: "'deploy_prod_primary' in group_names"
