---

#######
# Dir #
#######

manala_deploy_dir: /var/www/proximum-vimeet.project.local/htdocs

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    "{{ lookup('pipe','git ls-remote --get-url origin') }}"
manala_deploy_strategy_git_version: master

##########
# Copied #
##########

manala_deploy_copied:
  - vendor
  - node_modules

##########
# Shared #
##########

manala_deploy_shared_files:
  - app/config/parameters.yml

manala_deploy_shared_dirs:
  - var/logs
  - var/sessions
  - web/uploads
  - web/media

############
# Writable #
############

manala_deploy_writable_dirs_default:
  mode:   ug=rwx,o=rx
  follow: true
  raw:    setfacl -R -m u:"www-data":rwX -m u:"ELAO":rwX %(dir)s && setfacl -dR -m u:"www-data":rwX -m u:"ELAO":rwX %(dir)s

manala_deploy_writable_dirs:
  - var/cache
  - var/logs
  - var/sessions
  - web/uploads
  - web/css
  - web/media
