---

#######
# Dir #
#######

manala_deploy_dir: /var/www/proximum-vimeet.project.local/htdocs

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    git@github.com:proximum/vimeet.git
manala_deploy_strategy_git_version: master

##########
# Copied #
##########

manala_deploy_copied:
  - vendor
  - node_modules

##########
# Shared #
##########

manala_deploy_shared_files:
  - app/config/parameters.yml

manala_deploy_shared_dirs:
  - var/logs
  - var/shared_uploaded_files
  - web/uploads
  - web/media
  - web/css

############
# Writable #
############

manala_deploy_writable_dirs_default:
  mode:   ug=rwx,o=rx
  follow: true
  # ACL managed by Synalabs

manala_deploy_writable_dirs:
  - var/cache
  - var/logs
  - var/shared_uploaded_files
  - web/uploads
  - web/css
  - web/media
