Proximum\Vimeet\Domain\Model\Template\RegistrationTemplate:
  registration_template_asd_days:
      __construct: false
      title: "Inscription Template ASD Days"
      locales: ['fr']
      createdAt: <dateTimeBetween('-10days', 'now')>
      value:
          811f6edf:
            component: "block"
            type: "12"
            config:
              -
                dded0597:
                  component: "object"
                  type: "text"
                  config:
                    content:
                      fr: "Profil"
                    type: "titre"
                541f84d4:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Prénom"
                    placeholder:
                      fr: "Prénom"
                    help:
                      fr: ""
                    length: "250"
                    required: true
                    type: "text"
                    translatable: false
                838197c7:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Nom"
                    placeholder:
                      fr: "Nom"
                    help:
                      fr: ""
                    length: "250"
                    required: true
                    type: "text"
                    translatable: false
                dd321a4f:
                  component: "object"
                  type: "nomenclature"
                  config:
                    label:
                      fr: "Service (Juridique, Informatique, ...)"
                    help:
                      fr: ""
                    nomenclature: "1"
                6c4a3a4f:
                  component: "object"
                  type: "nomenclature"
                  config:
                    label:
                      fr: "Fonction"
                    help:
                      fr: ""
                    nomenclature: "4"
                1efb9cbb:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Téléphone portable"
                    placeholder:
                      fr: "Téléphone portable"
                    help:
                      fr: ""
                    length: ""
                    required: true
                    type: "text"
                    translatable: false
                3b759fbb:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Téléphone fixe"
                    placeholder:
                      fr: "Téléphone fixe"
                    help:
                      fr: ""
                    length: "25"
                    required: true
                    type: "text"
                    translatable: false
          4bb4db28:
            component: "block"
            type: "12"
            config:
              -
                0d86b25e:
                  component: "object"
                  type: "text"
                  config:
                    content:
                      fr: "Photo"
                    type: "titre"
                cb66008e:
                  component: "object"
                  type: "image"
                  config:
                    label:
                      fr: "Photo"
                    placeholder:
                      fr: "Photo"
                    help:
                      fr: ""
                    required: false
          67019e4a:
            component: "block"
            type: "12"
            config:
              -
                0fe9cb97:
                  component: "object"
                  type: "text"
                  config:
                    content:
                      fr: "Organisme"
                    type: "titre"
                3ad4b72f:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Nom (Société / Organisme)"
                    placeholder:
                      fr: "Nom (Société / Organisme)"
                    help:
                      fr: ""
                    length: "250"
                    required: true
                    type: "text"
                    translatable: false
                0225feca:
                  component: "object"
                  type: "nomenclature"
                  config:
                    label:
                      fr: "Catégorie (Pme / Eti / Startup / ... )"
                    help:
                      fr: ""
                    nomenclature: "4"
                9ef18c06:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Site internet"
                    placeholder:
                      fr: "Site internet"
                    help:
                      fr: ""
                    length: ""
                    required: false
                    type: "text"
                    translatable: false
                93de093f:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Adresse"
                    placeholder:
                      fr: "Adresse"
                    help:
                      fr: ""
                    length: ""
                    required: false
                    type: "text"
                    translatable: false
                de66af5d:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Code postal"
                    placeholder:
                      fr: "Code postal"
                    help:
                      fr: ""
                    length: ""
                    required: false
                    type: "text"
                    translatable: false
                d224f0e7:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Ville"
                    placeholder:
                      fr: "Ville"
                    help:
                      fr: ""
                    length: ""
                    required: false
                    type: "text"
                    translatable: false
                e801edd4:
                  component: "object"
                  type: "editable-text"
                  config:
                    label:
                      fr: "Pays"
                    placeholder:
                      fr: "Pays"
                    help:
                      fr: ""
                    length: ""
                    required: false
                    type: "text"
                    translatable: false
