Proximum\Vimeet\Domain\Model\Template\SheetTemplate:
    template_asd_days:
        __construct: false
        title: "Template de présentation de base"
        locales: ['fr']
        fallback: 'fr'
        createdAt: "<dateTimeBetween('-10days', 'now')>"
        value:
            69b3cde3:
                component: "block"
                type: "8-4"
                config:
                    style: "style-1"
                children:
                    -
                        dcc42d3d:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    fr: "Titre de votre fiche"
                                    en: "Title of your sheet"
                                placeholder:
                                    fr: "Société en une phrase"
                                    en: "Your company in a sentence"
                                help:
                                    fr: ""
                                    en: ""
                                length: "200"
                                type: "title"
                                required: true
                        291c7190:
                            component: "block"
                            type: "6-6"
                            config:
                                style: "style-1"
                            children:
                                -
                                    1b9a00b3:
                                        component: "object"
                                        type: "image"
                                        config:
                                            style: "style-1"
                                            label:
                                                fr: "Logo"
                                                en: "Logo"
                                            placeholder:
                                                fr: "Ajouter un logo"
                                                en: "Add a logo"
                                            help:
                                                fr: "Télécharger un logo pour améliorer votre visibilité"
                                                en: "Upload a logo to improve your impact"
                                            length: null
                                            type: null
                                            required: false
                                    6fe62a03:
                                        component: "block"
                                        type: "6-6"
                                        config:
                                            style: "style-1"
                                        children:
                                            -
                                                fb030569:
                                                    component: "object"
                                                    type: "tag"
                                                    config:
                                                        style: "style-1"
                                                        label:
                                                            fr: "Catégorie"
                                                            en: "Category"
                                                        tag: "sheet_organization_category"
                                            -
                                                90713a3d:
                                                    component: "object"
                                                    type: "tag"
                                                    config:
                                                        style: "style-1"
                                                        label:
                                                            fr: "Site internet"
                                                            en: "Website"
                                                        help:
                                                            fr: ""
                                                            en: ""
                                                        tag: "participant_website"
                                -
                                    d691d21c:
                                        component: "object"
                                        type: "editable-text"
                                        config:
                                            style: "style-1"
                                            label:
                                                fr: "Description d'activité"
                                                en: "Description of activity"
                                            placeholder:
                                                fr: ""
                                                en: ""
                                            help:
                                                fr: ""
                                                en: ""
                                            maxLength: 300
                                            type: "text"
                                            required: false
                        e438c993:
                            component: "object"
                            type: "nomenclature"
                            config:
                                style: "style-3"
                                label:
                                    fr: "Compétences"
                                    en: "Competency"
                                placeholder:
                                    fr: ""
                                    en: ""
                                help:
                                    fr: ""
                                    en: ""
                                mode: checkboxes
                                required: false
                                default: 1
                                nomenclature: "@nomenclature_competences->id"
                        75adad94:
                            component: "block"
                            type: "6-6"
                            config:
                                style: "style-1"
                            children:
                                -
                                    1adc1873:
                                        component: "object"
                                        type: "collection"
                                        config:
                                            style: "style-3"
                                            label:
                                                fr: "Clients de référence"
                                                en: "References"
                                            placeholder:
                                                fr: "Vos clients de référence"
                                                en: "Your references"
                                            help:
                                                fr: ""
                                                en: ""
                                            required: true
                                            default: "1"
                                -
                                    46663c1d:
                                        component: "object"
                                        type: "collection"
                                        config:
                                            style: "style-3"
                                            label:
                                                fr: "Projets innovant"
                                                en: "Innovative projects"
                                            placeholder:
                                                fr: "Vos projets innovant"
                                                en: "Your innovative projects"
                                            help:
                                                fr: ""
                                                en: ""
                                            required: false
                                            default: "3"
                        097ab5e8:
                            component: "object"
                            type: "collection"
                            config:
                                style: "style-3"
                                label:
                                    fr: "Equipements, technologies et process"
                                    en: "Equipements, technologies et process"
                                placeholder:
                                    fr: ""
                                    en: ""
                                help:
                                    fr: ""
                                    en: ""
                                required: false
                                default: "3"
                    -
                        d6fa1ac7:
                            component: "object"
                            type: "tags"
                            config:
                                style: "style-1"
                                label:
                                    fr: "Repères"
                                    en: "Landmarks"
                                placeholder:
                                    fr: "Saisissez un repère"
                                    en: ""
                                help:
                                    fr: ""
                                    en: ""
                                tags:
                                    -
                                        tag: "sheet_organization_turnover"
                                        label:
                                            fr: "Chiffre d'affaires"
                                            en: "Turnover"
                                    -
                                        tag: "sheet_organization_staff"
                                        label:
                                            fr: "Effectifs"
                                            en: "Staff"
                                required: false
                                collection: true
                                default: 3
                                translatable: true
                        a9271999:
                            component: "object"
                            type: "collection"
                            config:
                                style: "style-1"
                                label:
                                    fr: "Groupe / Membre"
                                    en: "Group / Member of"
                                placeholder:
                                    fr: ""
                                    en: ""
                                help:
                                    fr: ""
                                    en: ""
                                required: false
                                default: "3"
                        a23a2f5d:
                            component: "object"
                            type: "collection"
                            config:
                                style: "style-2"
                                label:
                                    fr: "Certifications"
                                    en: "Certifications"
                                placeholder:
                                    fr: "vos certifications"
                                    fr: "Your certifications"
                                help:
                                    fr: ""
                                    en: ""
                                required: false
                                default: "3"
                        bef61d39:
                            component: "object"
                            type: "participant"
                            config:
                                style: "style-1"
                                label:
                                    fr: "Participants"
                                    en: "Participants"
                                numberOfParticipantShown: "3"
                        211efd1f:
                            component: "object"
                            type: "media"
                            config:
                                style: "style-1"
                                label:
                                    fr: "Médias"
                                    en: "Medias"
                                titlePlaceholder:
                                    fr: "Titre de votre média"
                                    en: "Title of your medias"
                                linkPlaceholder:
                                    fr: "Lien de votre média"
                                    en: "Link of your medias"
                                help:
                                    fr: ""
                                    en: ""
                                required: false
                                default: "3"
            69962d34:
                component: "block"
                type: "12"
                config:
                    style: "style-1"
                children:
                    -
                        27db4a35:
                            component: "object"
                            type: "text"
                            config:
                                style: "style-2"
                                content:
                                    fr: "Objectifs de participation"
                                    en: "Objectives"
                                type: "title"
                        37db4a33:
                            component: "block"
                            type: "4-8"
                            config:
                                style: "style-2"
                            children:
                                -
                                    d927a04b:
                                        component: "object"
                                        type: "editable-text"
                                        config:
                                            style: "style-1"
                                            label:
                                                fr: "Description"
                                                en: "Description"
                                            placeholder:
                                                fr: "Description"
                                                en: "Description"
                                            help:
                                                fr: "Description"
                                                en: "Description"
                                            maxLength: 300
                                            type: "text"
                                            required: false
                                -
                                    03b394ac:
                                        component: "object"
                                        type: "nomenclature"
                                        config:
                                            style: "style-1"
                                            label:
                                                fr: "Offres"
                                                fr: "Offer"
                                            placeholder:
                                                fr: "Vos offres"
                                                en: "Your offers"
                                            help:
                                                fr: "Vos offres"
                                                en: "Your offers"
                                            required: true
                                            mode: checkboxes
                                            nomenclature: "@nomenclature_offre_besoins->id"
                                    63ccc105:
                                        component: "object"
                                        type: "nomenclature"
                                        config:
                                            style: "style-1"
                                            label:
                                                fr: "Besoins"
                                                en: "Needs"
                                            placeholder:
                                                fr: "Vos besoins"
                                                en: "Your needs"
                                            help:
                                                fr: "Vos besoins"
                                                en: "Your needs"
                                            required: true
                                            mode: checkboxes
                                            nomenclature: "@nomenclature_offre_besoins->id"
