services:
    Proximum\Vimeet\Application\Components\Happening\Participation\DisableEnableParticipation:
        arguments:
            - '@vimeet_infrastructure.repository.happening_participation_repository'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@adapter.job_queue_adapter'

    Proximum\Vimeet\Application\Components\Happening\Participation\UserParticipantAvailabilityReAggregator:
        arguments:
            - '@vimeet_infrastructure.repository.happening_participation_repository'
            - '@adapter.job_queue_adapter'
            - '@vimeet_infrastructure.repository.sheet_repository'

    Proximum\Vimeet\Application\Command\Encryption\EncryptHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Encryption\SheetEncryptFileAdapter'
            - '@Proximum\Vimeet\Infrastructure\Encryption\UserEventEncryptFileAdapter'

    Proximum\Vimeet\Application\Command\Encryption\DecryptHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Encryption\SheetDecryptFileAdapter'
            - '@Proximum\Vimeet\Infrastructure\Encryption\UserEventDecryptFileAdapter'

    #
    # Transactional
    #
    ### Mail
    #### Substitution
    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\ParticipantFullNameSubstitution:
        arguments:
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\EventSubstitution: ~

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\UserFirstNameSubstitution:
        arguments:
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\UserLastNameSubstitution:
        arguments:
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\TypeTitleSubstitution: ~

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\Link\ParticipantAccountLinkSubstitution:
        arguments:
            - '@adapter.event_url_generator'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\CTA\ParticipantAccountCTASubstitution:
        arguments:
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\Link\ParticipantAccountLinkSubstitution'
            - '@Proximum\Vimeet\Infrastructure\Adapter\EngineAdapter'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\Link\ActivateAccountLinkSubstitution:
        arguments:
            - '@adapter.event_url_generator'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\CTA\ActivateAccountCTASubstitution:
        arguments:
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\Link\ActivateAccountLinkSubstitution'
            - '@Proximum\Vimeet\Infrastructure\Adapter\EngineAdapter'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\SubstitutionsProviders:
        calls:
        - ['registerSubstitution', ['%%event%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\EventSubstitution']]
        - ['registerSubstitution', ['%%firstname%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\UserFirstNameSubstitution']]
        - ['registerSubstitution', ['%%firstName%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\UserFirstNameSubstitution']]
        - ['registerSubstitution', ['%%lastname%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\UserLastNameSubstitution']]
        - ['registerSubstitution', ['%%lastName%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\UserLastNameSubstitution']]
        - ['registerSubstitution', ['%%participant%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\ParticipantFullNameSubstitution']]
        - ['registerSubstitution', ['%%participationType%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\TypeTitleSubstitution']]
        - ['registerSubstitution', ['%%urlEventAccountParticipant%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\Link\ParticipantAccountLinkSubstitution']]
        - ['registerSubstitution', ['%%urlEventAccountParticipantWithCTA%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\CTA\ParticipantAccountCTASubstitution']]
        - ['registerSubstitution', ['%%urlEventActivateAccount%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\Link\ActivateAccountLinkSubstitution']]
        - ['registerSubstitution', ['%%urlEventActivateAccountWithCTA%%', '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\CTA\ActivateAccountCTASubstitution']]

    Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\SubstitutionHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\SubstitutionsProviders'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Prepare\PrepareRegisterAccountMail:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Transactional\Mail\MessageRepository'
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\SubstitutionHandler'
            - '@event_sender'
            - '@query.mail.participant_mail_view_query_handler'

    Proximum\Vimeet\Application\Components\Transactional\Mail\Prepare\PrepareActivateAccountMail:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Transactional\Mail\MessageRepository'
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Substitution\SubstitutionHandler'
            - '@event_sender'
            - '@query.mail.participant_mail_view_query_handler'

    Proximum\Vimeet\Application\Components\Transactional\Mail\PrepareHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Prepare\PrepareRegisterAccountMail'
            - '@Proximum\Vimeet\Application\Components\Transactional\Mail\Prepare\PrepareActivateAccountMail'
