Proximum\Vimeet\Application\Command\Product\Create:
    properties:
        name:
            - NotBlank: ~
        unitPrice:
            - NotBlank: ~
            - Range:
                min: 0
        file:
            - Image: ~
        quantityMin:
            - Expression:
                expression: "this.quantityMin <= this.quantityMax"
                message: validators.product.quantity.greaterOrEqual
            - Expression:
                expression: "this.quantityMin === null and this.quantityMax === null or this.quantityMin !== null and this.quantityMax !== null"
                message: validators.product.quantity.minRequired
            - Range:
                min: 0
        quantityMax:
            - Expression:
                expression: "this.quantityMin === null and this.quantityMax === null or this.quantityMin !== null and this.quantityMax !== null"
                message: validators.product.quantity.maxRequired
            - Range:
                min: 0
        availabilityCurrent:
            - Range:
                min: 0
        availabilityMax:
            - Range:
                min: 0
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
                        description: ~
                        optionalPriceText: ~
