Proximum\Vimeet\Application\Command\StaticFormulation\Create:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
        types:
            - NotBlank: ~

