server {
    listen 80;
    server_name vimeet.proximum *.vimeet.proximum;
    root /srv/public;
    client_max_body_size 8M;
    include conf.d/app_gzip;
    location / {
        try_files $uri /app.php$is_args$args;
    }
    location ~ ^/(app(_[-\w]+)?)\.php(/|$) {
        include conf.d/app_php_fpm;
    }
}
