Proximum\Vimeet\Application\Command\Happening\Create:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
                        description: ~
        allowQuestion:
            - NotNull: ~
        limitParticipant:
            - Type: int
            - Range:
                min: 0
