Proximum\Vimeet\Application\Command\Happening\Update:
    properties:
        category:
            - NotNull: ~
        webinar:
            - Type: bool
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
                        description: ~
                        webinarHeaderImage:
                            - Image:
                                  maxSize: 500k
                                  mimeTypes: !php/const Proximum\Vimeet\Domain\Event\Image::SUPPORTED_MIME_TYPE
                                  minHeight: 125
                                  maxHeight: 125
                        currentWebinarHeaderImage: ~
        begin:
            - NotNull: ~
        end:
            - NotNull: ~
            - Expression:
                expression: "this.begin < this.end"
                message: "validators.happening.startTimeMustBeBeforeEndTime"
        questionAllowed:
            - NotNull: ~
        limitParticipant:
            - Type: int
            - Range:
                min: 0
        invitationCode:
            - Length:
                min: 4
                minMessage: "validators.invitationCode.length.min"
        talkings:
            - All:
                - Collection:
                    fields:
                        speaker:
                            - NotNull: ~
                        position:
                            - NotNull: ~
