services:
    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Event\Sheet\IndexSheetsByEventCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Event\IndexFromScratchCommand:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Event\Index\IndexHandler'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\OMZ\ExportUserCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.admin_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }
