services:
    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Event\Sheet\IndexSheetsByEventCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Event\IndexFromScratchCommand:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Event\Index\IndexHandler'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\OMZ\ExportUserCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.admin_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Participant\Export\ExportParticipantCommand:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Participant\Export\ExportHandler'
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Event\ExtraDataRepository'
            - '@repository.admin_repository'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Participant\ParticipantProduct\SetProductToParticipantWithPackageParticipantAndPlanningDisabledCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@Proximum\Vimeet\Domain\Participant\ParticipantOfSheetWithPackageParticipantAndPlanningDisabled'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Event\User\Agenda\Version\GenerateVersionsForEventsCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@command.event.user.agenda.version.generate_versions_handler'
            - '@datetime'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Clean\RemovePastAvailableSlotCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.repository.meeting_slot_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\AvailableSlotRepository'
            - '@datetime'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Aggregate\Event\AvailableSlotCalculatorForCurrentEventCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@adapter.job_queue_adapter'
            - '@datetime'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\User\Agenda\Version\CleanOldVersionsCommand:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\User\Agenda\Version\NotifyVersionDiffCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Application\Command\User\Agenda\Version\Notification\RecurrentNotificationOfChangedInVersionCommandHandler'
            - '@datetime'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\User\Agenda\Version\NotifyVersionDiffDDayCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Application\Command\User\Agenda\Version\Notification\RecurrentNotificationOfChangedInVersionCommandHandler'
            - '@datetime'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Template\Form\ExportFormTemplateDataByUsersCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Template\FormTemplateRepository'
            - '@repository.admin_repository'
            - '@vimeet_infrastructure.repository.user_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Event\ExtraDataRepository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Rooming\Export\ExportRoomingListCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.admin_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }


    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Rooming\CleanUserNotPresentCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Meeting\Request\AssignAllParticipantsToRequestCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.repository.type_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'
            - '@event_dispatcher'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Product\ExportCommand:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Product\Export\ExportProductsHandler'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Invoice\FixInvoiceDataCommand:
        arguments:
            - '@adapter.serializer_adapter'
            - '@vimeet_infrastructure.repository.event_repository'
            - '@query.invoice.invoice_data_query_handler'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@repository.invoice.invoice_repository'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Happening\ExportParticipantsCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.admin_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Happening\Webinar\Record\ReconciliationCommand:
        arguments:
            - '@vimeet_infrastructure.repository.happening_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Happening\Webinar\Record\ForceZipRecordArchiveCommand:
        arguments:
            - '@vimeet_infrastructure.repository.happening_repository'
            - '@repository.admin_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
            - '@event_dispatcher'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\MediaResourceCountCommand:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Happening\Webinar\Record\CreateZipRecordArchiveCommand:
        arguments:
            - '@vimeet_infrastructure.repository.happening_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
            - '@event_dispatcher'
            - '@datetime'
        tags:
            - { name: console.command }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Sheet\Export\ExportSheetCommand:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Sheet\Export\ExportHandler'
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Event\ExtraDataRepository'
            - '@repository.admin_repository'
        tags:
            - { name: console.command }
