services:
    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Command\Event\Sheet\IndexSheetsByEventCommand:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: console.command }
