Proximum\Vimeet\Application\Command\User\ChangeMail:
    properties:
        mail:
            - NotBlank: ~
            - Email:
                message: validators.email
                strict: true
