Proximum\Vimeet\Application\Command\User\ChangeMail:
    properties:
        mail:
            - NotBlank: ~
            - Email:
                message: validators.email
                strict: true
        password:
            - NotBlank: ~
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: validators.currentPassword
