Proximum\Vimeet\Application\Command\Happening\Speaker\Create:
    properties:
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        translations:
            - All:
                - Collection:
                    fields:
                        position:
                            - NotBlank: ~
        organization:
            - NotBlank: ~
        logo:
            - Image:
                maxSize: 500k
        photo:
            - Image:
                maxSize: 500k
