Proximum\Vimeet\Application\Command\Happening\Category\Create:
    properties:
        titleTranslations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
