Proximum\Vimeet\Domain\Model\Admin:
    type:  entity
    table: admin
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            unique: true
        password:
            type: string
        salt:
            type: string
        locale:
            type: string
        firstname:
            type: string
        lastname:
            type: string
        role:
            type: string
        createdAt:
            type: datetime
        lastLoginAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true
        failedAuthentication:
            type: integer
            options:
                default: 0
        lastFailedAuthentication:
            type: datetime
            nullable: true
            options:
                default: null
    manyToMany:
        events:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            inversedBy: admins
