Proximum\Vimeet\Domain\Model\Admin\ForgottenPasswordToken:
    type:  entity
    table: admin_forgotten_password_token
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            unique: true
        expireDate:
            type: datetime
    oneToOne:
        admin:
            targetEntity: Proximum\Vimeet\Domain\Model\Admin
            joinColumn:
                onDelete: CASCADE
