Proximum\Vimeet\Domain\Model\BillingInfo:
    type:  entity
    table: billing_info
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        lastname:
            type: string
        firstname:
            type: string
        function:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        mobile:
            type: string
            nullable: true
        email:
            type: string
        company:
            type: string
        vatNumber:
            type: string
            nullable: true
        gender:
            type: string
            nullable: true
        reference:
            type: string
            nullable: true
    embedded:
        address:
            class: Proximum\Vimeet\Domain\Model\Address
    oneToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
