Proximum\Vimeet\Domain\Model\Cart:
    type:  entity
    table: cart
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        data:
            type: json_array
        template:
            type: json_array
        createdAt:
            type: datetime
    oneToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: "cascade"
