Proximum\Vimeet\Domain\Model\Catalog\External\CatalogVisibility:
    type:  entity
    table: catalog_visibility
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            mappedBy: types
            joinColumn:
                onDelete: SET NULL
        categories:
            targetEntity: Proximum\Vimeet\Domain\Model\Category
            mappedBy: categories
            joinColumn:
                onDelete: SET NULL
    uniqueConstraints:
        catalog_visibility_event:
            columns: [id, event_id]
