Proximum\Vimeet\Domain\Model\Category:
    type:  entity
    table: category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\CategoryTranslation
            mappedBy: category
            indexBy: locale
            cascade: ["persist"]
    manyToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            inversedBy: categories
            cascade: ["persist"]
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE

