Proximum\Vimeet\Domain\Model\Event\Configuration:
    type:  embeddable
    fields:
        headerLeftColor:
            type: string
        headerRightColor:
            type: string
        leftColor:
            type: string
        rightColor:
            type: string
        textColor:
            type: string
        headerButtonLeftColor:
            type: string
            options:
                default: '#2F2F2F'
        headerButtonRightColor:
            type: string
            options:
                default: '#2F2F2F'
        headerButtonTextColor:
            type: string
            options:
                default: '#FFFFFF'
        scheduleScale:
            type: integer
        catalogOnlineDate:
            type: datetime
            nullable: true
        enableBadgeForParticipantDate:
            type: datetime
            nullable: true
        happeningsOpenDate:
            type: datetime
            nullable: true
        schedulePublishDate:
            type: datetime
            nullable: true
        closeMeetingRequestDate:
            type: datetime
            nullable: true
        closeAnsweringMeetingRequestDate:
            type: datetime
            nullable: true
        smsActivationDate:
            type: datetime
            nullable: true
        agendaOnlineDate:
            type: datetime
            nullable: true
        registrationOpenDate:
            type: datetime
            nullable: true
        registrationCloseDate:
            type: datetime
            nullable: true
        enableVisioTestMenuButtonDate:
            type: datetime
            nullable: true
        meetingRequestUpdateLocked:
            type: boolean
            options:
                default: false
        legalInfo:
            type: string
            nullable: true
        contactFirstName:
            type: string
            nullable: true
        contactLastName:
            type: string
            nullable: true
        organiserPhone:
            type: string
            nullable: true
        organiserWebsite:
            type: string
            nullable: true
        allowDeposit:
            type: boolean
        depositUntil:
            type: datetime
            nullable: true
        minimumForDeposit:
            type: float
            nullable: true
        deposit:
            type: integer
            nullable: true
        paymentModes:
            type: json_array
        analyticsCode:
            type: string
            nullable: true
        backgroundImage:
            type: string
            nullable: true
        backgroundColor:
            type: string
            options:
                default: '#ffffff'
        displayParticipantNameOnPlanning:
            type: boolean
            options:
                default: false
        displayParticipantPositionOnPlanning:
            type: boolean
            options:
                default: false
        visio:
            type: boolean
            options:
                default: false
        networkingOpenDate:
            type: datetime
            nullable: true
        networkingCloseDate:
            type: datetime
            nullable: true
