Proximum\Vimeet\Domain\Model\Event\Configuration:
    type:  embeddable
    fields:
        leftColor:
            type: string
        rightColor:
            type: string
        textColor:
            type: string
        scheduleScale:
            type: integer
        contactFirstName:
            type: string
            nullable: true
        contactLastName:
            type: string
            nullable: true
        organiserPhone:
            type: string
            nullable: true
        organiserWebsite:
            type: string
            nullable: true
        allowDeposit:
            type: boolean
        depositUntil:
            type: datetime
            nullable: true
        minimumForDeposit:
            type: float
            nullable: true
        deposit:
            type: integer
        catalogOnlineDate:
            type: datetime
            nullable: true
        happeningsOpenDate:
            type: datetime
            nullable: true
        schedulePublishDate:
            type: datetime
            nullable: true
