Proximum\Vimeet\Domain\Model\EventTranslation:
    type:  entity
    table: event_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
        locale:
            type: string
        bankInfo:
            type: text
            nullable: true
        billingAddress:
            type: text
            nullable: true
        paymentCondition:
            type: text
            nullable: true
        paymentFooter:
            type: text
            nullable: true
        logo:
            type: string
            nullable: true
        logoExtension:
            type: string
            nullable: true
        mobileLogo:
            type: string
            nullable: true
        mobileLogoExtension:
            type: string
            nullable: true
        notificationImage:
            type: string
            nullable: true
        notificationImageExtension:
            type: string
            nullable: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            inversedBy: translations
            joinColumn:
                onDelete: CASCADE
