Proximum\Vimeet\Domain\Model\Event\Configuration:
    type:  embeddable
    fields:
        leftColor:
            type: string
        rightColor:
            type: string
        textColor:
            type: string
        scheduleScale:
            type: integer
        contactFirstName:
            type: string
            nullable: true
        contactLastName:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        website:
            type: string
            nullable: true
