Proximum\Vimeet\Domain\Model\Event\ExtraParameter:
    type:  entity
    table: event_extra_parameter
    id:
        event:
            associationKey: true
        type:
            type: string
    fields:
        value:
            type: string
        name:
            type: string
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
