Proximum\Vimeet\Domain\Model\Event\ExtraParameter:
    type:  entity
    table: event_extra_parameter
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    uniqueConstraints:
        unique_event_extra_parameter:
            columns:
                - event_id
                - type
    fields:
        type:
            type: string
        value:
            type: text
        name:
            type: string
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
