Proximum\Vimeet\Domain\Model\Event:
    type:  entity
    table: event
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        domain:
            type: string
        timeZone:
            type: string
        invoiceLogo:
            type: string
            nullable: true
        invoiceLogoExtension:
            type: string
            nullable: true
        locales:
            type: json_array
        fallback:
            type: string
        organiserName:
            type: string
            nullable: true
        organiserEmail:
            type: string
            nullable: true
        legalInformation:
            type: string
            nullable: true
        mode:
            type: string
        vat:
            type: float
        elementToJoinWithInvoice:
            type: string
            nullable: true
        assetPath:
            type: string
        country:
            type: string
        currency:
            type: string
        emailTeam:
            type: string
            nullable: true
        externalCatalogEnabled:
            type: boolean
            options:
                default: false
        userAgendaVersionsGenerated:
            type: boolean
            options:
                default: false
        visible:
            type: boolean
            options:
                default: true
        archived:
            type: boolean
            options:
                default: false
        welcomeEnabled:
            type: boolean
            options:
                default: true
        disabledEmailChanging:
            type: boolean
            options:
                default: false
        disabledPasswordChanging:
            type: boolean
            options:
                default: false
        googleLoginEnabled:
            type: boolean
            options:
                default: false
        linkedinLoginEnabled:
            type: boolean
            options:
                default: false
        accessControlEnabled:
            type: boolean
            options:
                default: false
        showCheckinStatus:
            type: boolean
            options:
                default: false
        autoArchiveWebinar:
            type: boolean
            options:
                default: false
        apiKey:
            type: string
            nullable: true
    embedded:
        paymentAddress:
            class: Proximum\Vimeet\Domain\Model\Address
        configuration:
            class: Proximum\Vimeet\Domain\Model\Event\Configuration
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\EventTranslation
            mappedBy: event
            indexBy: locale
            cascade: ["all"]
            orphanRemoval: true
        days:
            targetEntity: Proximum\Vimeet\Domain\Model\Event\Day
            mappedBy: event
            cascade: ["all"]
            orphanRemoval: true
    manyToOne:
        invoicePrefix:
            targetEntity: Proximum\Vimeet\Domain\Model\Invoice\Prefix
            cascade: ["persist"]
            joinColumn:
                nullable: false
        duplicatedFrom:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: true
