Proximum\Vimeet\Domain\Model\Event:
    type:  entity
    table: event
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        domain:
            type: string
        timeZone:
            type: string
        locales:
            type: json_array
        fallback:
            type: string
        billingTemplate:
            type: json_array
        organiserName:
            type: string
        organiserEmail:
            type: string
        bankInfo:
            type: string
        legalInformation:
            type: string
        mode:
            type: string
        vat:
            type: float
        elementToJoinWithInvoice:
            type: string
        assetPath:
            type: string
        country:
            type: string
        currency:
            type: string
    embedded:
        paymentAddress:
            class: Proximum\Vimeet\Domain\Model\Address
        configuration:
            class: Proximum\Vimeet\Domain\Model\Event\Configuration
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\EventTranslation
            mappedBy: event
            indexBy: locale
            cascade: ["all"]
            orphanRemoval: true
