Proximum\Vimeet\Domain\Model\File:
    type: entity
    table: file
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
        type:
            type: string
            nullable: true
        createdAt:
            type: datetime
