Proximum\Vimeet\Domain\Model\Happening\Speaker:
    type:  entity
    table: happening_speaker
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
        lastname:
            type: string
        organization:
            type: string
        logo:
            type: string
            nullable: true
        photo:
            type: string
            nullable: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: true
    oneToMany:
        talkings:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\Talking
            mappedBy: speaker
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\SpeakerTranslation
            mappedBy: speaker
            indexBy: locale
            cascade: ["persist"]
