Proximum\Vimeet\Domain\Model\Happening:
    type:  entity
    table: happening
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
        end:
            type: datetime
        questionAllowed:
            type: boolean
            options:
                default: false
        limitParticipant:
            type: integer
            nullable: true
        invitationCode:
            type: string
            nullable: true
        webinar:
            type: boolean
            options:
                default: false
        interactiveWebinar:
            type: boolean
            options:
                default: false
        webinarSessionId:
            type: string
            nullable: true
        liveUrl:
            type: string
            length: 5000
            nullable: true
        sidebarAllowed:
            type: boolean
            options:
                default: true            
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\HappeningTranslation
            mappedBy: happening
            indexBy: locale
            cascade: ['persist']
        talkings:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\Talking
            mappedBy: happening
            cascade: ['persist', 'remove']
            orphanRemoval: true
        participations:
            targetEntity: Proximum\Vimeet\Domain\Model\HappeningParticipation
            mappedBy: happening
        questions:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\Question
            mappedBy: happening
            joinColumn:
                onDelete: CASCADE
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        category:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\Category
            joinColumn:
                onDelete: CASCADE
    manyToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
        products:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
            inversedBy: happenings
            joinTable:
                name: happenings_products
