Proximum\Vimeet\Domain\Model\Happening\Talking:
    type:  entity
    table: happening_talking
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
    manyToOne:
        speaker:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening\Speaker
            inversedBy: talkings
            joinColumn:
                onDelete: CASCADE
        happening:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening
            inversedBy: talkings
            joinColumn:
                onDelete: CASCADE
