Proximum\Vimeet\Domain\Model\Happening\Webinar\RecordArchive:
    type:  entity
    table: happening_webinar_record_archive
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        archiveId:
            type: string
        status:
            type: string
        createdAt:
            type: datetime
    manyToOne:
        happening:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening
            joinColumn:
                onDelete: CASCADE
