Proximum\Vimeet\Domain\Model\Happening\HappeningTranslation:
    type:  entity
    table: happening_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        description:
            type: text
            nullable: true
        webinarHeaderImage:
            type: string
            nullable: true
        locale:
            type: string
    manyToOne:
        happening:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening
            inversedBy: translations
            joinColumn:
                onDelete: CASCADE
