Proximum\Vimeet\Domain\Model\Happening\Question:
    type:  entity
    table: happening_question
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
        createdAt:
            type: datetime
        askedDuringWebinar:
            type: boolean
            options:
                default: false
    manyToOne:
        happening:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening
            inversedBy: questions
            joinColumn:
                onDelete: CASCADE
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        createdBy:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
