Proximum\Vimeet\Domain\Model\Invoice\Invoice:
    type: entity
    table: invoice
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        total:
            type: float
        totalWithVat:
            type: float
        vatAmount:
            type: float
        invoicePrefix:
            type: string
        invoiceYear:
            type: string
        invoiceIncrement:
            type: string
        createdAt:
            type: datetime

    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
        prefix:
            targetEntity: Proximum\Vimeet\Domain\Model\Invoice\Prefix
    uniqueConstraints:
        invoice_number:
            columns: invoice_prefix, invoice_year, invoice_increment
