Proximum\Vimeet\Domain\Model\Invoice\Invoice:
    type: entity
    table: invoice
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        vatApplicable:
            type: boolean
        vatMode:
            type: string
        vatRate:
            type: float
        total:
            type: integer
        totalWithVat:
            type: integer
        vatAmount:
            type: integer
        invoicePrefix:
            type: string
            column: invoice_prefix
        invoiceYear:
            type: integer
            column: invoice_year
        invoiceIncrement:
            type: integer
            column: invoice_increment
        currency:
            type: string
        createdAt:
            type: datetime
        data:
            type: json_array
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
        prefix:
            targetEntity: Proximum\Vimeet\Domain\Model\Invoice\Prefix
    oneToMany:
        orders:
            targetEntity: Proximum\Vimeet\Domain\Model\Order
            mappedBy: invoice
    uniqueConstraints:
        invoice_number:
            columns: prefix_id, invoice_prefix, invoice_year, invoice_increment
