Proximum\Vimeet\Domain\Model\MeetingSlot:
    type:  entity
    table: meeting_slot
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
        end:
            type: datetime
        locked:
            type: boolean
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
