Proximum\Vimeet\Domain\Model\Meeting:
    type: entity
    table: meeting
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        state:
            type: string
        status:
            type: string
            options:
                default: 'not_confirmed'
        createdAt:
            type: datetime
        blockedSpot:
            type: boolean
            options:
                default: false
        blockedSlot:
            type: boolean
            options:
                default: false
        createdType:
            type: string
            nullable: false
        followupSentSheetIds:
            type: simple_array
            nullable: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
        request:
            targetEntity: Proximum\Vimeet\Domain\Model\Meeting\Request
            inversedBy: meeting
            joinColumn:
                nullable: false
                unique: true
                onDelete: CASCADE
        slot:
            targetEntity: Proximum\Vimeet\Domain\Model\MeetingSlot
            joinColumn:
                onDelete: CASCADE
        fromSheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        toSheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        spot:
            targetEntity: Proximum\Vimeet\Domain\Model\Spot
            joinColumn:
                onDelete: CASCADE
    manyToMany:
        fromParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_from_participants
        toParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_to_participants
