Proximum\Vimeet\Domain\Model\Meeting:
    type: entity
    table: meeting
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        state:
            type: string
        createdAt:
            type: datetime
    oneToOne:
        request:
          targetEntity: Proximum\Vimeet\Domain\Model\Meeting\Request
          inversedBy: meeting
    manyToOne:
        slot:
            targetEntity: Proximum\Vimeet\Domain\Model\MeetingSlot
            joinColumn:
                onDelete: CASCADE
        fromSheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        toSheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
    manyToMany:
        fromParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_from_participants
        toParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_to_participants
        spot:
            targetEntity: Proximum\Vimeet\Domain\Model\Spot
            joinTable:
                name: meeting_spot
