Proximum\Vimeet\Domain\Model\Meeting\Message:
    type: entity
    table: meeting_message
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        from:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        meeting:
            targetEntity: Proximum\Vimeet\Domain\Model\Meeting
            joinColumn:
                onDelete: CASCADE
        request:
            targetEntity: Proximum\Vimeet\Domain\Model\Meeting\Request
            joinColumn:
                onDelete: CASCADE
