Proximum\Vimeet\Domain\Model\Meeting\Request:
    type: entity
    table: meeting_request
    indexes:
        state:
            columns: [ state ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        state:
            type: string
        createdAt:
            type: datetime
        stateUpdatedAt:
            type: datetime
        disabled:
            type: boolean
            options:
                default: false
        hasMessage:
            type: boolean
            options:
                default: false
        toPriority:
            type: boolean
            options:
                default: false
        fromPriority:
            type: boolean
            options:
                default: false
    oneToMany:
        meeting:
            targetEntity: Proximum\Vimeet\Domain\Model\Meeting
            mappedBy: request
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
        from:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        to:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        creator:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
        updateOrDeleteReasonMessage:
            targetEntity: Proximum\Vimeet\Domain\Model\Meeting\Message
            joinColumn:
                onDelete: SET NULL
    manyToMany:
        fromParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_request_from_participants
        toParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_request_to_participants
