Proximum\Vimeet\Domain\Model\Messaging\Message:
    type:  entity
    table: messaging_message
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        createdAt:
            type: datetime
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\Messaging\MessageTranslation
            mappedBy: message
            indexBy: locale
            cascade: ['persist', 'remove']
