Proximum\Vimeet\Domain\Model\Nomenclature:
    type:  entity
    table: nomenclature
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        depth:
            type: integer
        value:
            type: json_array
        sort:
            type: boolean
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        original:
            targetEntity: Proximum\Vimeet\Domain\Model\Nomenclature
            joinColumn:
                onDelete: SET NULL
