Proximum\Vimeet\Domain\Model\NomenclatureTranslation:
    type:  entity
    table: nomenclature_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        locale:
            type: string
    manyToOne:
        nomenclature:
            targetEntity: Proximum\Vimeet\Domain\Model\Nomenclature
            inversedBy: translations
