Proximum\Vimeet\Domain\Model\Notification:
    type: entity
    table: notification
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            nullable: false
    manyToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
