Proximum\Vimeet\Domain\Model\Order:
    type: entity
    table: _order
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        vatMode:
            type: string
        groupsData:
            type: json_array
        vatApplicable:
            type: boolean
        vatRate:
            type: float
        currency:
            type: string
        cancelled:
            type: boolean
    manyToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            inversedBy: orders
    oneToMany:
        rows:
            targetEntity: Proximum\Vimeet\Domain\Model\Order\Row
            mappedBy: order
            cascade:
                - persist
        promotionCodes:
            targetEntity: Proximum\Vimeet\Domain\Model\Order\PromotionCode
            mappedBy: order
            cascade:
                - persist
    embedded:
        billingInfo:
            class: Proximum\Vimeet\Domain\Model\Order\BillingInfo
