Proximum\Vimeet\Domain\Model\Order\PromotionCode:
    type:  entity
    table: order_promotion_code
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        data:
            type: json_array
        price:
            type: float
        vatRate:
            type: float
    manyToOne:
        product:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
            joinColumn:
                onDelete: SET NULL
        order:
            targetEntity: Proximum\Vimeet\Domain\Model\Order
            inversedBy: promotionCodes
            joinColumn:
                onDelete: CASCADE
        promotionCode:
            targetEntity: Proximum\Vimeet\Domain\Model\PromotionCode
            joinColumn:
                onDelete: SET NULL
