Proximum\Vimeet\Domain\Model\Package:
    type:  entity
    table: package
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        image:
            type: string
            nullable: true
        unitPrice:
            type: float
        availabilityCurrent:
            type: integer
            nullable: true
        availabilityMax:
            type: integer
            nullable: true
        participantIncluded:
            type: integer
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\PackageTranslation
            mappedBy: package
            indexBy: locale
            cascade: ["persist"]
        features:
            targetEntity: Proximum\Vimeet\Domain\Model\Package\Feature
            mappedBy: package
            cascade: ["persist"]
        productIncluded:
            targetEntity: Proximum\Vimeet\Domain\Model\Package\ProductIncluded
            mappedBy: package
            cascade: ["persist"]
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
