Proximum\Vimeet\Domain\Model\PackageTranslation:
    type:  entity
    table: package_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        descriptionTitle:
            type: string
        descriptionContent:
            type: text
            nullable: true
        optionalPriceText:
            type: text
            nullable: true
        locale:
            type: string
    manyToOne:
        package:
            targetEntity: Proximum\Vimeet\Domain\Model\Package
            inversedBy: translations
