Proximum\Vimeet\Domain\Model\PackagePlanRank:
    type:  entity
    table: package_plan
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        rank:
            type: integer
    manyToOne:
        package:
            targetEntity: Proximum\Vimeet\Domain\Model\Package
            inversedBy: planRanks
            joinColumn:
                onDelete: CASCADE
        plan:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
            joinColumn:
                onDelete: CASCADE
