Proximum\Vimeet\Domain\Model\Package\Feature:
    type:  entity
    table: package_feature
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\Package\FeatureTranslation
            mappedBy: feature
            indexBy: locale
            cascade: ["persist"]
    manyToOne:
        package:
            targetEntity: Proximum\Vimeet\Domain\Model\Package
