Proximum\Vimeet\Domain\Model\Package:
    type:  entity
    table: package
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        plansEnabled:
            type: boolean
        participantAndPlanningEnabled:
            type: boolean
        optionsEnabled:
            type: boolean
        createdAt:
            type: datetime
        maxParticipant:
            type: integer
            nullable: true
        planningSelectable:
            type: boolean
            options:
                default: true
        participantWithPlanning:
            type: boolean
            options:
                default: false
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        planning:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
            joinColumn:
                onDelete: SET NULL
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\PackageTranslation
            mappedBy: package
            cascade: ["persist"]
            indexBy: locale
            orphanRemoval: true
        planRanks:
            targetEntity: Proximum\Vimeet\Domain\Model\PackagePlanRank
            mappedBy: package
            cascade: ["persist"]
            orderBy: { rank: ASC }
            orphanRemoval: true
        participantRanks:
            targetEntity: Proximum\Vimeet\Domain\Model\PackageParticipantRank
            mappedBy: package
            cascade: ["persist"]
            orderBy: { rank: ASC }
            orphanRemoval: true
        groups:
            targetEntity: Proximum\Vimeet\Domain\Model\PackageGroup
            mappedBy: package
            cascade: ["persist"]
            orderBy: { rank: ASC }
            orphanRemoval: true
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            mappedBy: package
