Proximum\Vimeet\Domain\Model\Participant:
    type:  entity
    table: participant
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        data:
            type: json_array
        active:
            type: boolean
        registrationStep:
            type: integer
            nullable: true
        registrationComplete:
            type: boolean
        imported:
            type: boolean
        hasRequestAssigned:
            type: boolean
            options:
                default: false
        isFullyUnavailable:
            type: boolean
            options:
                default: false
        timezone:
            type: string
            nullable: true
        registrationDate:
            type: datetime
        rank:
            type: integer
            options:
                default: 0
    manyToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            inversedBy: participants
            joinColumn:
                onDelete: CASCADE
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
        participantProduct:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
    uniqueConstraints:
        unique_user_sheet_idx:
            columns: [sheet_id, user_id]
