Proximum\Vimeet\Domain\Model\ParticipantImport:
    type:  entity
    table: participant_import
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        result:
            type: json_array
        createdAt:
            type: datetime
    manyToOne:
        type:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            joinColumn:
                onDelete: CASCADE
