Proximum\Vimeet\Domain\Model\Payment\Payment:
    type:  entity
    table: payment
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        transaction:
            targetEntity: Proximum\Vimeet\Domain\Model\Transaction
            joinColumn:
                onDelete: CASCADE
            inversedBy: payment
