Proximum\Vimeet\Domain\Model\Product:
    type:  entity
    table: product
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
        name:
            type: string
        image:
            type: string
            nullable: true
        unitPrice:
            type: float
        vat:
            type: float
        quantityMax:
            type: integer
            nullable: true
        availabilityCurrent:
            type: integer
            nullable: true
        availabilityMax:
            type: integer
            nullable: true
        updatable:
            type: boolean
        deletableUntil:
            type: datetime
            nullable: true
        buyableUntil:
            type: datetime
            nullable: true
        subjectedToValidation:
            type: boolean
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\ProductTranslation
            mappedBy: product
            indexBy: locale
            cascade: ["persist"]
        features:
            targetEntity: Proximum\Vimeet\Domain\Model\Product\Feature
            mappedBy: product
            cascade: ["persist"]
            orphanRemoval: true
            orderBy: { id: ASC }
        productIncluded:
            targetEntity: Proximum\Vimeet\Domain\Model\Product\ProductIncluded
            mappedBy: product
            cascade: ["persist"]
            orphanRemoval: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
