Proximum\Vimeet\Domain\Model\Promotion:
    type:  entity
    table: promotion
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
        value:
            type: float
    manyToOne:
        promotionCode:
            targetEntity: Proximum\Vimeet\Domain\Model\PromotionCode
            joinColumn:
                onDelete: CASCADE
        product:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
            joinColumn:
                onDelete: CASCADE
    uniqueConstraints:
        unique_promotion_product:
            columns: [promotion_code_id, product_id]
