Proximum\Vimeet\Domain\Model\PurchasingFunnelPlan:
    type:  entity
    table: purchasing_funnel_plan
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        rank:
            type: integer
    manyToOne:
        purchasingFunnel:
            targetEntity: Proximum\Vimeet\Domain\Model\PurchasingFunnel
            inversedBy: plans
        plan:
            targetEntity: Proximum\Vimeet\Domain\Model\Product
