Proximum\Vimeet\Domain\Model\Rooming\Accommodation:
    type:  entity
    table: rooming_accommodation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
    oneToMany:
        overnightCapacities:
            targetEntity: Proximum\Vimeet\Domain\Model\Rooming\AccommodationOvernightCapacity
            mappedBy: accommodation
            cascade: ["persist"]
            orphanRemoval: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
