Proximum\Vimeet\Domain\Model\Rule:
    type:  entity
    table: rule
    uniqueConstraints:
        unique_idx_1:
            columns:
                - seer_type_id
                - seeable_type_id
        unique_idx_2:
            columns:
                - seer_type_id
                - seeable_category_id
        unique_idx_3:
            columns:
                - seer_category_id
                - seeable_type_id
        unique_idx_4:
            columns:
                - seer_category_id
                - seeable_category_id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        what:
            type: json_array
        priority:
            type: integer
            options:
                default: 0
        phoneAccessMinEvaluation:
            type: smallint
            nullable: true
        emailAccessMinEvaluation:
            type: smallint
            nullable: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        seerType:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            joinColumn:
                onDelete: CASCADE
        seerCategory:
            targetEntity: Proximum\Vimeet\Domain\Model\Category
            joinColumn:
                onDelete: CASCADE
        seeableType:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            joinColumn:
                onDelete: CASCADE
        seeableCategory:
            targetEntity: Proximum\Vimeet\Domain\Model\Category
            joinColumn:
                onDelete: CASCADE
