Proximum\Vimeet\Domain\Model\Sheet\Template:
    type:  entity
    table: sheet_template
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        value:
            type: json_array
        createdAt:
            type: datetime
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
    oneToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            mappedBy: sheetTemplate
