Proximum\Vimeet\Domain\Model\Sheet\Comment:
    type: entity
    table: sheet_comment
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
            nullable: true
        createdAt:
            type: datetime
        commercialStatus:
            type: string
            nullable: true
    manyToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        author:
            targetEntity: Proximum\Vimeet\Domain\Model\Admin
            joinColumn:
                onDelete: CASCADE
