Proximum\Vimeet\Domain\Model\Sheet\Group:
    type: entity
    table: sheet_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        createdAt:
            type: datetime
        sheetTitleForced:
            type: boolean
            option:
                default: false
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
        manager:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: false
                onDelete: CASCADE
        duplicatedFrom:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet\Group
            joinColumn:
                nullable: true
                onDelete: SET NULL
    oneToMany:
        sheets:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            mappedBy: group
    uniqueConstraints:
        unique_manager_event:
            columns:
                - event_id
                - manager_id
        unique_duplicated_group_event:
            columns:
                - event_id
                - duplicated_from_id
