Proximum\Vimeet\Domain\Model\Sheet:
    type:  entity
    table: sheet
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        data:
            type: json_array
            nullable: true
        registrationData:
            type: json_array
            nullable: true
        createdAt:
            type: datetime
        lastLoginAt:
            type: datetime
            nullable: true
        state:
            type: string
        validationState:
            type: string
            options:
                default: 'draft'
        completeness:
            type: integer
        enable:
            type: boolean
        inCatalog:
            type: boolean
        inCatalogAt:
            type: datetime
            nullable: true
        imported:
            type: boolean
        attend:
            type: boolean
            options:
                default: true
        title:
            type: string
            nullable: true
        agendaConfirmedStatus:
            type: string
            options:
                default: 'agenda_not_concerned'
        phoneValidationStatus:
            type: string
            options:
                default: 'phone_not_concerned'
        availabilityConfirmationStatus:
            type: string
            options:
                default: 'none_confirmed'
        commercialStatus:
            type: string
            options:
                default: 'none'
        reminderDate:
            type: datetime
            nullable: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        owner:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: SET NULL
        type:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            joinColumn:
                onDelete: SET NULL
        follower:
            targetEntity: Proximum\Vimeet\Domain\Model\Admin
            joinColumn:
                onDelete: SET NULL
        spot:
            targetEntity: Proximum\Vimeet\Domain\Model\Spot
            inversedBy: sheets
            joinColumn:
                onDelete: SET NULL
        group:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet\Group
            inversedBy: sheets
            joinColumn:
                onDelete: SET NULL
        duplicatedFrom:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: SET NULL
        linkedSheets:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet\LinkedSheets
            inversedBy: sheets
            joinColumn:
                onDelete: SET NULL
    oneToMany:
        participants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            cascade: ['persist']
            mappedBy: sheet
            orderBy: { rank: DESC }
        orders:
            targetEntity: Proximum\Vimeet\Domain\Model\Order
            mappedBy: sheet
        availableSlots:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet\AvailableSlot
            cascade: ['persist', 'remove']
            mappedBy: sheet
            orphanRemoval: true
