Proximum\Vimeet\Domain\Model\Sheet\SheetViewed:
    type: entity
    table: sheet_viewed
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: false
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                nullable: false
    uniqueConstraints:
        unique_user_sheet:
            columns:
                - user_id
                - sheet_id
