Proximum\Vimeet\Domain\Model\Template\SheetTemplate:
    type:  entity
    table: sheet_template
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        locales:
            type: json_array
        fallback:
            type: string
            length: 5
        value:
            type: json_array
        printValue:
            type: json_array
            nullable: true
        preview:
            type: json_array
            nullable: true
        createdAt:
            type: datetime
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            mappedBy: sheetTemplate
