Proximum\Vimeet\Domain\Model\Tip\Tip:
    type:  entity
    table: tip
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        onMeetingManagement:
            type: boolean
            options:
                default: false
        onCatalog:
            type: boolean
            options:
                default: false
        onPrintPlanning:
            type: boolean
            options:
                default: false
        onSheet:
            type: boolean
            options:
                default: false
        onProgram:
            type: boolean
            options:
                default: false
        onAgenda:
            type: boolean
            options:
                default: false
        onPackage:
            type: boolean
            options:
                default: false
        onContacts:
            type: boolean
            options:
                default: false
        onConfirmationPhone:
            type: boolean
            options:
                default: false
        onNetworking:
            type: boolean
            options:
                default: false
        display:
            type: string
            options:
                default: 'default'
        conditionHasCart:
            type: boolean
            nullable: true
        conditionHasRemainingToPay:
            type: boolean
            nullable: true
        conditionIsPhoneConfirmed:
            type: boolean
            nullable: true
        conditionIsCompleteSheet:
            type: boolean
            nullable: true
        conditionHasPendingMeetingProposition:
            type: boolean
            nullable: true
        conditionOnOrders:
            type: json_array
            nullable: true
        createdAt:
            type: datetime
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\Tip\TipTranslation
            mappedBy: tip
            indexBy: locale
            orphanRemoval: true
            cascade: ['persist', 'remove']
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: true
                onDelete: CASCADE
    manyToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
