Proximum\Vimeet\Domain\Model\Tip\TipTranslation:
    type:  entity
    table: tip_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        lang:
            type: string
        content:
            type: text
    manyToOne:
        tip:
            targetEntity: Proximum\Vimeet\Domain\Model\Tip\Tip
            inversedBy: translations

