Proximum\Vimeet\Domain\Model\Token\UserEventToken:
    type:  entity
    table: user_event_token
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            unique: true
        type:
            type: string
        createdAt:
            type: datetime
        confirmed:
            type: boolean
            options:
                default: false
        confirmedAt:
            type: datetime
            nullable: true
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
    uniqueConstraints:
        user_event_token_unique_idx:
            columns: [event_id, user_id, type]
