Proximum\Vimeet\Domain\Model\Trace:
    type:  entity
    table: trace
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        objectType:
            type: string
        objectId:
            type: integer
        action:
            type: string
        date:
            type: datetime
        comment:
            type: text
            nullable: true
    indexes:
        object_index:
            columns: [object_type, object_id]

    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: SET NULL
        admin:
            targetEntity: Proximum\Vimeet\Domain\Model\Admin
            joinColumn:
                onDelete: SET NULL
