Proximum\Vimeet\Domain\Model\Transaction:
    type:  entity
    table: transaction
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        amount:
            type: float
        date:
            type: datetime
        mode:
            type: string
        reference:
            type: string
            nullable: true
        internalReference:
            type: string
            length: 20000
            default: ''
        state:
            type: string
        currency:
            type: string
        hidden:
            type: boolean
            options:
                default: false
    manyToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            joinColumn:
                onDelete: CASCADE
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: SET NULL
    oneToOne:
        payment:
            targetEntity: Proximum\Vimeet\Domain\Model\Payment\Payment
            mappedBy: transaction
