Proximum\Vimeet\Domain\Model\Type:
    type:  entity
    table: type
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
            nullable: true
        previewTemplate:
            type: text
        viewTemplate:
            type: text
        hidden:
            type: boolean
        numberOfMeetingsPerPlanning:
            type: integer
            nullable: true
        disableUnavailabilityManagement:
            type: boolean
            options:
                default: false
        canUpdateMeeting:
            type: boolean
            options:
                default: false
        canRemoveMeeting:
            type: boolean
            options:
                default: false
        availabilityType:
            type: string
        areAllSheetParticipantsAssignedToMeeting:
            type: string
            options:
                default: false
        canScanParticipant:
            type: boolean
            options:
                default: false
        isPackageRequired:
            type: boolean
            options:
                default: false
        isPaymentRequired:
            type: boolean
            options:
                default: false
        priorityMeetingRequestsNumber:
            type: integer
            nullable: true
            options:
                default: 0
        numberMaxOfHappeningsPerUser:
            type: integer
            nullable: true
            options:
                default: null
        numberMaxOfMeetingsPerSheet:
            type: integer
            nullable: true
            options:
                default: null
        canEvaluateMeeting:
            type: boolean
            options:
                default: true
        mustEvaluateMeeting:
            type: boolean
            options:
                default: false
        canSubmitValidation:
            type: boolean
            options:
                default: true
        displayAnalyticsOnSheet:
            type: boolean
            options:
                default: false
        displayAnalyticsOnCatalog:
            type: boolean
            options:
                default: false
    embedded:
        validationCriteria:
            class: Proximum\Vimeet\Domain\Model\ValidationCriteria
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\TypeTranslation
            mappedBy: type
            indexBy: locale
            cascade: ["persist", "remove"]
        paymentConditions:
            targetEntity: Proximum\Vimeet\Domain\Model\Type\PaymentConditions
            mappedBy: type
            cascade: ["remove"]
    manyToMany:
        categories:
            targetEntity: Proximum\Vimeet\Domain\Model\Category
            mappedBy: types
        admins:
            targetEntity: Proximum\Vimeet\Domain\Model\Admin
            mappedBy: types
        formTemplates:
            targetEntity: Proximum\Vimeet\Domain\Model\Template\FormTemplate
            cascade: ["persist", "remove"]
            inversedBy: types
            orphanRemoval: true
            joinTable:
                name: template_form_type
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                onDelete: CASCADE
        sheetTemplate:
            targetEntity: Proximum\Vimeet\Domain\Model\Template\SheetTemplate
            inversedBy: types
            cascade:
                - persist
            joinColumn:
                onDelete: SET NULL
        registrationTemplate:
            targetEntity: Proximum\Vimeet\Domain\Model\Template\RegistrationTemplate
            inversedBy: types
            cascade:
                - persist
            joinColumn:
                onDelete: SET NULL
        package:
            targetEntity: Proximum\Vimeet\Domain\Model\Package
            inversedBy: types
            cascade:
                - persist
            joinColumn:
                onDelete: SET NULL
