Proximum\Vimeet\Domain\Model\Unavailability\MassAssignment:
    type:  entity
    table: mass_unavailability_assignment
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
            column: from_date
        end:
            type: datetime
            column: to_date
        enabled:
            type: boolean
            options:
                default: true
    manyToOne:
        mass:
            targetEntity: Proximum\Vimeet\Domain\Model\Unavailability\Mass
            joinColumn:
                onDelete: CASCADE
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
