Proximum\Vimeet\Domain\Model\Unavailability:
    type:  entity
    table: unavailability
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
        end:
            type: datetime
        message:
            type: string
            nullable: true
        createdBy:
            type: string
            nullable: false
            options:
                default: 'user'
    indexes:
        createdByIndex:
            columns: [ created_by ]
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: false
                onDelete: CASCADE
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
