Proximum\Vimeet\Domain\Model\Unavailability:
    type:  entity
    table: unavailability
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
        end:
            type: datetime
    manyToOne:
        participant:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinColumn:
                onDelete: CASCADE
