Proximum\Vimeet\Domain\Model\User\FormData:
    type:  entity
    table: user_form_data
    id:
        user:
            associationKey: true
        formTemplate:
            associationKey: true
    fields:
        data:
            type: json_array
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
                nullable: false
        formTemplate:
            targetEntity: Proximum\Vimeet\Domain\Model\Template\FormTemplate
            joinColumn:
                onDelete: CASCADE
                nullable: false
