Proximum\Vimeet\Domain\Model\User\ForgottenPasswordToken:
    type:  entity
    table: user_forgotten_password_token
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            unique: true
        expireDate:
            type: datetime
    oneToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
