Proximum\Vimeet\Domain\Model\User\Event\ExtraData:
    type:  entity
    table: user_event_extra_data
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        value:
            type: text
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: false
                onDelete: CASCADE
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
