Proximum\Vimeet\Domain\Model\User\Event\PresenceDate:
    type:  entity
    table: user_event_presence_date
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        arrival:
            type: datetime
            nullable: true
        departure:
            type: datetime
            nullable: true
        hasArrivalHours:
            type: boolean
            options:
                default: true
        hasDepartureHours:
            type: boolean
            options:
                default: true
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: false
                onDelete: CASCADE
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
