Proximum\Vimeet\Domain\Model\User\Event\Scan:
    type:  entity
    table: user_event_scan
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            options:
                default: 'event_entrance'
        objectId:
            type: integer
            nullable: true
        scannedAt:
            type: datetime
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                nullable: false
                onDelete: CASCADE
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
            joinColumn:
                nullable: false
                onDelete: CASCADE
