Proximum\Vimeet\Domain\Model\VideoConferenceToken:
    type:  entity
    table: video_conference_token
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: text
        streamId:
            type: text
            nullable: true
    manyToOne:
        videoConference:
            targetEntity: Proximum\Vimeet\Domain\Model\VideoConference
            joinColumn:
                onDelete: CASCADE
                nullable: false
            cascade: ["persist"]
            inversedBy: tokens
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
            joinColumn:
                onDelete: CASCADE
                nullable: false
                cascade: ["persist"]
