Proximum\Vimeet\Domain\Model\Happening\Category:
    category_conference:
        __construct: ['@event_rdv_carnot_2016', 'Dejeuner', 1, '#59a4aa', '#59a4bb']
    category_flash:
        __construct: ['@event_rdv_carnot_2016', 'Conference', 2, '#59a4cc', '#59a4ff']
    category_workshop:
        __construct: ['@event_rdv_carnot_2016', 'Cafe_1', 3, '#59a4dd', '#59a4cf']
    category_cocktail:
        __construct: ['@event_rdv_carnot_2016', 'RDV', 4, '#59a4aa', '#59a4ff']
    category_meeting:
        __construct: ['@event_rdv_carnot_2016', 'Cocktail', 5, '#59a4aa', '#59a4aa']
    category_round_table:
        __construct: ['@event_rdv_carnot_2016', 'PresFlash_2', 6, '#59a4aa', '#59a4aa']

Proximum\Vimeet\Domain\Model\Happening\CategoryTranslation:
    category_conference_fr:
        __construct: ['@category_conference', "fr", "Conférence"]
    category_conference_en:
        __construct: ['@category_conference', "en", "Conference"]
    category_flash_fr:
        __construct: ['@category_flash', "fr", "Présentation flash"]
    category_flash_en:
        __construct: ['@category_flash', "en", "Flash"]
    category_workshop_fr:
        __construct: ['@category_workshop', "fr", "Atelier"]
    category_workshop_en:
        __construct: ['@category_workshop', "en", "Workshop"]
    category_cocktail_fr:
        __construct: ['@category_cocktail', "fr", "Cocktail"]
    category_cocktail_en:
        __construct: ['@category_cocktail', "en", "Cocktail"]
    category_meeting_fr:
        __construct: ['@category_meeting', "fr", "Réunion"]
    category_meeting_en:
        __construct: ['@category_meeting', "en", "Meeting"]
    category_round_table_fr:
        __construct: ['@category_round_table', "fr", "Table ronde"]
    category_round_table_en:
        __construct: ['@category_round_table', "en", "Round table"]
