Proximum\Vimeet\Application\Command\Operator\Create:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: validators.email
        lastname:
            - NotBlank: ~
        firstname:
            - NotBlank: ~
