Proximum\Vimeet\Application\Command\Operator\Update:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: validators.email
                strict: true
        lastname:
            - NotBlank: ~
        firstname:
            - NotBlank: ~
