# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $dateTime: '@datetime'
            $scheme: '%scheme%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Proximum\Vimeet\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Bundle/InfrastructureBundle/InfrastructureBundle.php'
            - '../src/Infrastructure/Bundle/InfrastructureBundle/DependencyInjection/'
            - '../src/Infrastructure/Bundle/InfrastructureBundle/DataFixtures/'
            - '../src/Domain/Model'
            - '../src/Application/View'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    # Proximum\Vimeet\Controller\:
    #     resource: '../src/Controller/'
    #     tags: ['controller.service_arguments']

    Proximum\Vimeet\Infrastructure\Adapter\Elasticsearch\Sheet\TagFilterAggregator:
        arguments:
            $searchable: '@fos_elastica.index.app.sheet'

    Proximum\Vimeet\Application\Command\File\PersistContentHandler:
        arguments:
            $pathToExport: '%infrastructure.common_export_path%'

    Proximum\Vimeet\Application\Command\OMZ\PersistContentHandler:
        arguments:
            $pathToOmzExport: '%infrastructure.export_omz_path%'

    # explicit aliases for interfaces
    Proximum\Vimeet\Domain\Sheet\Aggregate\AvailableSlotCalculatorInterface:
        alias: Proximum\Vimeet\Domain\Sheet\Aggregate\AvailableSlotCalculatorDecorator
    Proximum\Vimeet\Application\Adapter\BatchJobQueueInterface:
        alias: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Adapter\BatchJobQueue\BatchCatalogJobQueue

    # for compatibility with sf3 legacy (to be migrated)
    Doctrine\ORM\EntityManager:
        alias: Doctrine\ORM\EntityManagerInterface
    adapter.event_url_generator:
        alias: Proximum\Vimeet\Infrastructure\Adapter\EventUrlGenerator
    Proximum\Vimeet\Domain\Model\Event\EventUrlGeneratorInterface:
        alias: adapter.event_url_generator
