Proximum\Vimeet\Application\Command\Unavailability\Create:
    properties:
        day:
            - NotNull: ~
        time:
            - Collection:
                begin:
                    - Collection:
                        hour:
                            - NotNull: ~
                        minute:
                            - NotNull: ~
                end:
                    - Collection:
                        hour:
                            - NotNull: ~
                        minute:
                            - NotNull: ~
            - Expression:
                expression: "this.time['begin']['hour'] < this.time['end']['hour'] || (this.time['begin']['hour'] === this.time['end']['hour'] && this.time['begin']['minute'] < this.time['end']['minute'])"
                message: "validators.unavailability.startTimeMustBeBeforeEndTime"
        participants:
            - Count:
                min: 1
                minMessage: validators.unavailability.participantsNotSelected

