services:
    #
    # Product
    #
    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductAttributedToParticipantSetter:
        arguments:
            - '@Proximum\Vimeet\Domain\ProductAttributedToParticipant\ParticipantWithAttributedProductUpdated'
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@datetime'

    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ParticipantWithAttributedProductGetter:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipant\ParticipantWithAttributedProductToRepository'
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ParticipantWithAttributedProductUpdated: ~

    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductsAttributedToParticipantRemoveAllBySheet:
        arguments:
            - '@Proximum\Vimeet\Domain\Happening\ParticipateToHappeningsByProduct'
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductAttributedToParticipantSetter'

    domain.product.duplicator:
        class: Proximum\Vimeet\Domain\Product\Duplicator
        arguments:
            - '@adapter.local_file_storage'

    domain.package.duplicator:
        class: Proximum\Vimeet\Domain\Package\Duplicator
        arguments:
            - '@datetime'

    Proximum\Vimeet\Domain\Sheet\Participant\AddParticipantChecker: ~

    Proximum\Vimeet\Domain\Order\DiscountCalculator: ~

    #
    # System Unavailability
    #
    Proximum\Vimeet\Domain\Unavailability\SystemGenerator\OverlappedTimeRangeTruncater: ~
    Proximum\Vimeet\Domain\Unavailability\SystemGenerator\OverlappedTimeRangeMerger: ~

    Proximum\Vimeet\Domain\Unavailability\SystemGenerator\Generator:
        arguments:
            - '@vimeet_infrastructure.repository.unavailability_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\AvailabilityTimeRangeRepository'
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@Proximum\Vimeet\Domain\Unavailability\SystemGenerator\OverlappedTimeRangeMerger'
            - '@Proximum\Vimeet\Domain\Unavailability\SystemGenerator\OverlappedTimeRangeTruncater'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@Proximum\Vimeet\Infrastructure\Repository\CartRowParticipantRepository'

    #
    # Participant
    #
    Proximum\Vimeet\Domain\Participant\ParticipantProductSetter:
        arguments:
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'

    #
    # Availability Time Range
    #
    Proximum\Vimeet\Domain\AvailabilityTimeRange\Product\ParticipantProductWithAvailabilityTimeRangeChecker:
        arguments:
            - '@Proximum\Vimeet\Domain\Unavailability\SystemGenerator\OverlappedTimeRangeMerger'
            - '@Proximum\Vimeet\Domain\Unavailability\SystemGenerator\OverlappedTimeRangeTruncater'
            - '@vimeet_infrastructure.repository.participant_repository'

    #
    # Sheet
    #
    Proximum\Vimeet\Domain\Sheet\HasRemainingToPay:
        arguments:
            - '@order.balance'
