services:
    domain.product.duplicator:
        class: Proximum\Vimeet\Domain\Product\Duplicator
        arguments:
            - '@adapter.local_file_storage'

    domain.package.duplicator:
        class: Proximum\Vimeet\Domain\Package\Duplicator
        arguments:
            - '@datetime'

    Proximum\Vimeet\Domain\Sheet\Participant\AddParticipantChecker:

    Proximum\Vimeet\Domain\Order\DiscountCalculator:
