services:
    #
    # Product
    #
    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductAttributedToParticipantSetter:
        arguments:
            - '@Proximum\Vimeet\Domain\ProductAttributedToParticipant\ParticipantWithAttributedProductUpdated'
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@datetime'

    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ParticipantWithAttributedProductGetter:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipant\ParticipantWithAttributedProductToRepository'
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ParticipantWithAttributedProductUpdated: ~

    Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductsAttributedToParticipantRemoveAllBySheet:
        arguments:
            - '@Proximum\Vimeet\Domain\Happening\ParticipateToHappeningsByProduct'
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductAttributedToParticipantSetter'

    domain.product.duplicator:
        class: Proximum\Vimeet\Domain\Product\Duplicator
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Adapter\LocalFileStorageAdapter'

    domain.package.duplicator:
        class: Proximum\Vimeet\Domain\Package\Duplicator
        arguments:
            - '@datetime'

    Proximum\Vimeet\Domain\Package\IsValidatedRequiredPackageMissing:
        arguments:
            - '@vimeet_infrastructure.repository.order_repository'

    Proximum\Vimeet\Domain\Transaction\IsValidatedTransactionMissing:
        arguments:
            - '@vimeet_infrastructure.repository.order_repository'
            - '@query.order.order_vat_view_query_handler'
            - '@order.balance'

    Proximum\Vimeet\Domain\Sheet\Participant\AddParticipantChecker: ~

    Proximum\Vimeet\Domain\Order\DiscountCalculator: ~

    #
    # System Unavailability
    #
    Proximum\Vimeet\Domain\Time\OverlappedTimeRangeTruncater: ~
    Proximum\Vimeet\Domain\Time\OverlappedTimeRangeMerger: ~

    Proximum\Vimeet\Domain\Unavailability\SystemGenerator\Generator:
        arguments:
            - '@vimeet_infrastructure.repository.unavailability_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\AvailabilityTimeRangeRepository'
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@Proximum\Vimeet\Domain\Time\OverlappedTimeRangeMerger'
            - '@Proximum\Vimeet\Domain\Time\OverlappedTimeRangeTruncater'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@Proximum\Vimeet\Infrastructure\Repository\CartRowParticipantRepository'

    Proximum\Vimeet\Domain\Unavailability\SystemGenerator\GenerateParticipantProductSystemUnavailabilities:
        arguments:
            - '@vimeet_infrastructure.repository.user_repository'
            - '@Proximum\Vimeet\Domain\Unavailability\SystemGenerator\Generator'

    #
    # Participant
    #
    Proximum\Vimeet\Domain\Participant\ParticipantProductSetter:
        arguments:
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@event_dispatcher'

    Proximum\Vimeet\Domain\Participant\IsParticipantVisio:
        arguments:
            - '@repository.user.event.extra_data_repository'

    Proximum\Vimeet\Domain\Participant\GetParticipantTypes:
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'

    #
    # Availability Time Range
    #
    Proximum\Vimeet\Domain\AvailabilityTimeRange\Product\ParticipantProductWithAvailabilityTimeRangeChecker:
        arguments:
            - '@Proximum\Vimeet\Domain\Time\OverlappedTimeRangeMerger'
            - '@Proximum\Vimeet\Domain\Time\OverlappedTimeRangeTruncater'
            - '@vimeet_infrastructure.repository.participant_repository'

    #
    # Sheet
    #
    Proximum\Vimeet\Domain\Sheet\HasRemainingToPay:
        arguments:
            - '@order.balance'
    Proximum\Vimeet\Domain\Sheet\Product\SelectedProductAssigner:
        arguments:
            - '@template.template_data_factory'
            - '@order.merger'
            - '@vimeet_infrastructure.repository.sheet_repository'
    Proximum\Vimeet\Domain\Sheet\CanSeeSheet:
        arguments:
            - '@repository.rule_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'

    Proximum\Vimeet\Domain\Helper\LinkedSheetsTitle:
        arguments:
            - '@vimeet_infrastructure.repository.meeting.request_repository'

    #
    # Template
    #
    Proximum\Vimeet\Domain\Template\ObjectsCollectionBlock\BlockToArray: ~
    Proximum\Vimeet\Domain\Template\ObjectsCollectionBlock\SetArrayContentToBlock: ~

    #
    # Key Dates
    #
    Proximum\Vimeet\Domain\KeyDates\Checker\EnableBadgeForParticipantDateAccessChecker:
        arguments:
            - '@datetime'

    #
    # Template
    #
    Proximum\Vimeet\Domain\Template\Form\FormTemplateValidator: ~

    #
    # Badge
    #
    Proximum\Vimeet\Domain\Badge\AvailableChecker:
        arguments:
            - '@Proximum\Vimeet\Domain\KeyDates\Checker\EnableBadgeForParticipantDateAccessChecker'
            - '@Proximum\Vimeet\Infrastructure\Repository\BadgeRepository'
            - '@Proximum\Vimeet\Domain\Sheet\HasRemainingToPay'

    #
    # Leni badge link
    #

    Proximum\Vimeet\Application\Leni\BadgeLink\AvailableChecker:
        arguments:
            - '@Proximum\Vimeet\Application\ThirdParty\LENI\Common\Query\BadgeLink\LeniBadgeLinkParametersQueryHandler'

    #
    # File
    #
    Proximum\Vimeet\Domain\File\FileFactory:
        arguments:
            - '@repository.file_repository'
            - '@datetime'

    #
    # Rooming
    #
    Proximum\Vimeet\Domain\Rooming\Accommodation\HasRemainingOvernight:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository'

    Proximum\Vimeet\Domain\Rooming\Stay\HasStayForPeriod:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository'

    #
    # User
    #
    Proximum\Vimeet\Domain\User\Sheet\HasAccessToSheet:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'

    Proximum\Vimeet\Domain\User\Sheet\FirstParticipantSheetOfUserGetter: ~

    Proximum\Vimeet\Domain\Sheet\Catalog\CanSeeOtherSheets:
        arguments:
            - '@repository.rule_repository'

    Proximum\Vimeet\Application\Components\Order\FixProductPromotionCodes\ProductPromotionCodesFixStrategyGuesser:
        arguments:
            - '@Proximum\Vimeet\Application\Components\Order\OrderHelper'

    Proximum\Vimeet\Domain\User\Security\CanPasswordBeDefinedWithActivationEmail:
        arguments:
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@vimeet_infrastructure.repository.user_repository'
            - '@repository.event.extra_parameter_repository'

    #
    # Networking
    #
    Proximum\Vimeet\Domain\Networking\Sheet\CanAccessToNetworking: ~
