Proximum\Vimeet\Application\Command\Partner\Update:
    properties:
        email:
            - NotBlank: ~
            - Email:
                  message: validators.email
                  strict: true
        password:
            - Length:
                  min: 12
                  minMessage: validators.password.min
            - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Password\ContainsAtLeastOneNumber: ~
            - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Password\ContainsAtLeastOneUppercase: ~
            - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Password\ContainsAtLeastOneLowercase: ~
        lastname:
            - NotBlank: ~
        firstname:
            - NotBlank: ~
        types:
            - NotBlank: ~
