Proximum\Vimeet\Application\Command\Messaging\Message\Create:
    properties:
        name:
            - NotBlank: ~
        translations:
            - All:
                - Collection:
                    fields:
                        locale:
                            - NotBlank: ~
                        subject:
                            - NotBlank: ~
                        content:
                            - NotBlank: ~
