Proximum\Vimeet\Application\Command\Messaging\Message\Create:
    properties:
        name:
            - NotBlank: ~
        subject:
            - NotBlank: ~
        content:
            - NotBlank: ~
