Proximum\Vimeet\Application\Command\User\ChangePassword:
    properties:
        currentPassword:
            - NotBlank: ~
        plainPassword:
            - NotBlank: ~
            - Length:
                min: 8
                minMessage: validators.password
