Proximum\Vimeet\Application\Command\User\Register:
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Length: { min: 8 }
