Proximum\Vimeet\Application\Command\User\Register:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: validators.email
        password:
            - NotBlank: ~
            - Length:
                min: 8
                minMessage: validators.password
