Proximum\Vimeet\Application\Command\Happening\Category\Create:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
        position:
            - NotNull: ~
        leftColor:
            - NotBlank: ~
        rightColor:
            - NotBlank: ~
