Proximum\Vimeet\Application\Command\Happening\Category\Create:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
        rank:
            - NotNull: ~
        leftColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        rightColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
