Proximum\Vimeet\Application\Command\Unavailability\Mass\Create:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        title:
                            - NotBlank: ~
                        description: ~
        blocking:
            - NotNull: ~
        category:
            - NotNull: ~
        name:
            - NotBlank: ~
        begin:
            - NotNull: ~
        end:
            - NotNull: ~
            - Expression:
                expression: "this.begin < this.end"
                message: "validators.unavailability.startTimeMustBeBeforeEndTime"
        dispatch:
            - Type: { type: boolean }
        timeSlots:
            - Expression:
                expression: "this.areTimeSlotsValid()"
                message: "validators.unavailability.timeSlotsExceedRange"
        types:
            - Count:
                  min: 1
