Proximum\Vimeet\Application\Command\Package\Model\ParticipantAndPlanning:
    properties:
        labels:
            - NotBlank: ~
            - All:
                constraints:
                    - NotBlank: ~
                    - Type: { type: string }
        enabled:
            - Type: { type: boolean }
        participants:
            - Valid: ~
            - Type: { type: array }
            - Count: { min: 1 }
            - All:
                - NotBlank: ~
        planning:
            - Expression:
                expression: "!this.enabled || this.enabled && null !== this.planning"
