Proximum\Vimeet\Application\Command\Package\Model\Plans:
    properties:
        labels:
            - NotBlank: ~
            - All:
                constraints:
                    - NotBlank: ~
                    - Type: { type: string }
        enabled:
            - Type: { type: boolean }
        plans:
            - Valid: ~
            - Type: { type: array }
            - Count: { min: 0 }
            - All:
                - NotBlank: ~
