default:
    extensions:
        Behat\Symfony2Extension:
            kernel:
               env: test
        Behat\MinkExtension:
            base_url:  'http://vimeet.proximum.dev/app_test.php'
            sessions:
                default:
                    symfony2: ~
                javascript:
                    selenium2: ~
            files_path: %paths.base%/src/Behat/Resources/fixtures/Files
        Fidry\AliceBundleExtension\Extension:
            fixtures_base_path: %paths.base%/src/Behat/Resources/fixtures
        Sanpi\Behatch\Extension: ~
        FriendsOfBehat\PerformanceExtension: ~
    suites:
        default:
            contexts:
                - Fidry\AliceBundleExtension\Context\Doctrine\AliceORMContext:
                    basePath: %paths.base%/src/Behat/Resources/fixtures
                - Proximum\Vimeet\Behat\Context\DoctrineORMContext: ~
                - Proximum\Vimeet\Behat\Context\FeatureContext: ~
                - Proximum\Vimeet\Behat\Context\Domain\EventContext:
                    - '@behat_storage'
                    - '@vimeet_infrastructure.repository.event_repository'
                - Proximum\Vimeet\Behat\Context\Domain\SlotContext:
                    - '@behat_storage'
                    - '@vimeet_infrastructure.repository.meeting_slot_repository'
                    - '@domain.meeting.slot.slot_generator'
                - Proximum\Vimeet\Behat\Context\Domain\SpotContext:
                    - '@behat_storage'
                    - '@vimeet_infrastructure.repository.spot_repository'
                    - '@vimeet_infrastructure.repository.sheet_repository'
                - behatch:json
                - behatch:rest
#                - behatch:browser
#                - behatch:debug
#                - behatch:system
#                - behatch:table
#                - behatch:xml
