default:
    extensions:
        Behat\Symfony2Extension:
            kernel:
               env: test
               bootstrap: 'vendor/autoload.php'
        Behat\MinkExtension:
            base_url: 'http://admin.vimeet.proximum'
            sessions:
                default:
                    symfony2: ~
                javascript:
                    selenium2: ~
            files_path: %paths.base%/src/Behat/Resources/fixtures/Files
        Fidry\AliceBundleExtension\Extension:
            fixtures_base_path: %paths.base%/src/Behat/Resources/fixtures
        Behatch\Extension: ~
    suites:
        default:
            contexts:
                - Fidry\AliceBundleExtension\Context\Doctrine\AliceORMContext:
                    basePath: %paths.base%/src/Behat/Resources/fixtures
                - Proximum\Vimeet\Behat\Context\DoctrineORMContext: ~
                - Proximum\Vimeet\Behat\Context\FeatureContext:
                    - '@behat_proxy.feature_context'
                - Proximum\Vimeet\Behat\Context\Domain\EventContext:
                    - '@behat_proxy.event_context'
                - Proximum\Vimeet\Behat\Context\Domain\UserContext:
                    - '@behat_proxy.user_context'
                - Proximum\Vimeet\Behat\Context\Domain\AdminContext:
                    - '@behat_proxy.admin_context'
                - Proximum\Vimeet\Behat\Context\Domain\TypeContext:
                    - '@behat_proxy.type_context'
                - Proximum\Vimeet\Behat\Context\Domain\SheetContext:
                    - '@behat_proxy.sheet_context'
                - Proximum\Vimeet\Behat\Context\Domain\GroupContext:
                    - '@behat_proxy.group_context'
                - Proximum\Vimeet\Behat\Context\Domain\InvoiceContext:
                    - '@behat_proxy.invoice_context'
                - Proximum\Vimeet\Behat\Context\Domain\ParticipantContext:
                    - '@behat_proxy.participant_context'
                - Proximum\Vimeet\Behat\Context\Domain\SlotContext:
                    - '@behat_proxy.slot_context'
                - Proximum\Vimeet\Behat\Context\Domain\SpotContext:
                    - '@behat_proxy.spot_context'
                - Proximum\Vimeet\Behat\Context\Domain\MeetingContext:
                    - '@behat_proxy.meeting_context'
                - Proximum\Vimeet\Behat\Context\Domain\OrderContext:
                    - '@behat_proxy.order_context'
                - Proximum\Vimeet\Behat\Context\Domain\TipContext:
                    - '@behat_proxy.tip_context'
                - Proximum\Vimeet\Behat\Context\Domain\LoginContext:
                    - '@behat_proxy.login_context'
                - Proximum\Vimeet\Behat\Context\Domain\Event\DayContext:
                    - '@behat_proxy.event.day_context'
                - Proximum\Vimeet\Behat\Context\Domain\CatalogVisibilityContext:
                    - '@behat.proxy.catalog_visibility_context_proxy'
                - Proximum\Vimeet\Behat\Context\Domain\Meeting\RequestContext:
                    - '@behat_proxy.meeting_context'
                    - '@behat_proxy.sheet_context'
                    - '@behat_proxy.user_context'
                - Proximum\Vimeet\Behat\Context\Domain\Token\UserEventTokenContext:
                    - '@behat_proxy.token.user_event_token_context'
                - Proximum\Vimeet\Behat\Context\Domain\User\Event\AuthenticationTokenContext:
                    - '@behat_proxy.user.event.authentication_token_context'
                - Proximum\Vimeet\Behat\Context\Domain\Invoice\PrefixContext:
                    - '@behat_proxy.invoice.prefix_context'
                - Proximum\Vimeet\Behat\Context\Domain\Event\ContentContext:
                    - '@behat_proxy.event.content_context'
                - Proximum\Vimeet\Behat\Context\Domain\RuleContext:
                    - '@behat.proxy.rule_context'
                - Proximum\Vimeet\Behat\Context\Domain\Package\PackageContext:
                    - '@Proximum\Vimeet\Behat\Proxy\PackageContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Product\ProductContext:
                    - '@Proximum\Vimeet\Behat\Proxy\ProductContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\AvailabilityTimeRangeContext:
                    - '@Proximum\Vimeet\Behat\Proxy\AvailabilityTimeRangeContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\BillingInfoContext:
                    - '@Proximum\Vimeet\Behat\Proxy\BillingInfoContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Happening\CategoryContext:
                    - '@Proximum\Vimeet\Behat\Proxy\Happening\CategoryContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Unavailability\CategoryContext:
                    - '@Proximum\Vimeet\Behat\Proxy\Unavailability\CategoryContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Messaging\MessageContext:
                    - '@Proximum\Vimeet\Behat\Proxy\Messaging\MessageContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Notification\NotificationContext:
                    - '@Proximum\Vimeet\Behat\Proxy\Notification\NotificationContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Sheet\SheetCompletenessContext:
                    - '@Proximum\Vimeet\Behat\Proxy\Sheet\SheetCompletenessContextProxy'
                - Proximum\Vimeet\Behat\Context\Domain\Transaction\TransactionContext:
                    - '@Proximum\Vimeet\Behat\Proxy\Transaction\TransactionContextProxy'
                - behatch:context:json
                - behatch:context:rest
