Proximum\Vimeet\Application\Command\Admin\ForgottenPassword:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: validators.email
                strict: true
