Proximum\Vimeet\Application\Command\Admin\Update:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: validators.email
                strict: true
        password:
            - Length:
                min: 8
                minMessage: validators.password.min
        lastname:
            - NotBlank: ~
        firstname:
            - NotBlank: ~
