Proximum\Vimeet\Domain\Model\Category:
    type:  entity
    table: category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        filters:
            type: json_array
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\CategoryTranslation
            mappedBy: category
            indexBy: locale
    manyToMany:
        types:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
            inversedBy: categories
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
