Proximum\Vimeet\Domain\Model\Event:
    type:  entity
    table: event
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        domain:
            type: string
        locales:
            type: json_array
        fallback:
            type: string
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\EventTranslation
            mappedBy: event
