Proximum\Vimeet\Domain\Model\Form:
    type:  entity
    table: form
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        template:
            type: text
    manyToOne:
        type:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
