Proximum\Vimeet\Domain\Model\Happening:
    type:  entity
    table: happening
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
        end:
            type: datetime
        title:
            type: string
        description:
            type: string
        blocking:
            type: boolean
    manyToOne:
        schedule:
            targetEntity: Proximum\Vimeet\Domain\Model\Schedule
            inversedBy: happenings
