Proximum\Vimeet\Domain\Model\Happening\Speaker:
    type:  entity
    table: happening_speaker
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        function:
            type: string
        organization:
            type: string
        logo:
            type: string
        photo:
            type: string
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
