Proximum\Vimeet\Domain\Model\Happening\DescriptionTranslation:
    type:  entity
    table: happening_description_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
        locale:
            type: string
    manyToOne:
        happening:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening
            inversedBy: descriptionTranslations
