Proximum\Vimeet\Domain\Model\Meeting\Request:
    type: entity
    table: meeting_request
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
        state:
            type: string
        createdAt:
            type: datetime
        refuseMessage:
            type: text
            nullable: true
    manyToOne:
        from:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
        to:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
    manyToMany:
        fromParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_request_from_participants
        toParticipants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            joinTable:
                name: meeting_request_to_participants
