Proximum\Vimeet\Domain\Model\NomenclatureItemTranslation:
    type:  entity
    table: nomenclature_item_translation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        locale:
            type: string
    manyToOne:
        nomenclatureItem:
            targetEntity: Proximum\Vimeet\Domain\Model\NomenclatureItem
            inversedBy: translations
