Proximum\Vimeet\Domain\Model\Participant:
    type:  entity
    table: participant
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        data:
            type: text

    manyToOne:
        sheet:
            targetEntity: Proximum\Vimeet\Domain\Model\Sheet
            inversedBy: participants
        user:
            targetEntity: Proximum\Vimeet\Domain\Model\User
