Proximum\Vimeet\Domain\Model\Schedule:
    type:  entity
    table: schedule
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
    oneToMany:
        meetingSlots:
            targetEntity: Proximum\Vimeet\Domain\Model\MeetingSlot
            mappedBy: schedule
        happenings:
            targetEntity: Proximum\Vimeet\Domain\Model\Happening
            mappedBy: schedule
