Proximum\Vimeet\Domain\Model\Sheet:
    type:  entity
    table: sheet
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        data:
            type: text
            nullable: true
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
        type:
            targetEntity: Proximum\Vimeet\Domain\Model\Type
    oneToMany:
        participants:
            targetEntity: Proximum\Vimeet\Domain\Model\Participant
            mappedBy: sheet
