Proximum\Vimeet\Domain\Model\Template:
    type:  entity
    table: template
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        participant:
            type: json_array
        sheet:
            type: json_array
        package:
            type: json_array
        preview:
            type: string
        view:
            type: string
