Proximum\Vimeet\Domain\Model\Template:
    type:  entity
    table: template
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        type:
            type: string
        data:
            type: json_array
