Proximum\Vimeet\Domain\Model\Type:
    type:  entity
    table: type
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
        participantTemplate:
            type: json_array
        sheetTemplate:
            type: json_array
        packageTemplate:
            type: json_array
        maxParticipant:
            type: integer
        freeParticipant:
            type: integer
    oneToMany:
        translations:
            targetEntity: Proximum\Vimeet\Domain\Model\TypeTranslation
            mappedBy: type
    manyToOne:
        event:
            targetEntity: Proximum\Vimeet\Domain\Model\Event
