services:
    adapter.http_adapter:
        class: Proximum\Vimeet\Infrastructure\Adapter\HttpAdapter

    Proximum\Vimeet\Infrastructure\Adapter\CommandBus:
        arguments:
            $commandBus: '@tactician.commandbus'

    Proximum\Vimeet\Application\Adapter\CommandBusInterface: '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'

    Proximum\Vimeet\Infrastructure\Adapter\QueryBus:
        arguments:
            $commandBus: '@tactician.commandbus.query'

    Proximum\Vimeet\Application\Adapter\QueryBusInterface: '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
