services:
    repository.analytic.meeting_solution_repository:
        class: Proximum\Vimeet\Infrastructure\Repository\Analytic\MeetingSolutionRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    repository.event.extra_parameter_repository:
        class: Proximum\Vimeet\Infrastructure\Repository\Event\ExtraParameterRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    repository.user.event.extra_data_repository:
        class: Proximum\Vimeet\Infrastructure\Repository\User\Event\ExtraDataRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Type\PaymentConditionsRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Domain\Repository\Type\PaymentConditionsRepositoryInterface: '@Proximum\Vimeet\Infrastructure\Repository\Type\PaymentConditionsRepository'

    Proximum\Vimeet\Infrastructure\Repository\CartRowParticipantRepository:
        arguments:
            - '@doctrine.orm.entity_manager'
