services:
    repository.analytic.meeting_solution_repository:
        class: Proximum\Vimeet\Infrastructure\Repository\Analytic\MeetingSolutionRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    repository.event.extra_parameter_repository:
        class: Proximum\Vimeet\Infrastructure\Repository\Event\ExtraParameterRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    repository.user.event.extra_data_repository:
        class: Proximum\Vimeet\Infrastructure\Repository\User\Event\ExtraDataRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    Proximum\Vimeet\Infrastructure\Repository\User\Event\PresenceDateRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Type\ContentRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Type\PaymentConditionsRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Domain\Repository\Type\PaymentConditionsRepositoryInterface: '@Proximum\Vimeet\Infrastructure\Repository\Type\PaymentConditionsRepository'

    Proximum\Vimeet\Infrastructure\Repository\CartRowParticipantRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\User\Event\AuthenticationTokenRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\BadgeRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Domain\Repository\BadgeRepositoryInterface: '@Proximum\Vimeet\Infrastructure\Repository\BadgeRepository'

    Proximum\Vimeet\Infrastructure\Repository\AvailableSlotRepository:
        arguments:
           - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Domain\Repository\AvailableSlotRepositoryInterface: '@Proximum\Vimeet\Infrastructure\Repository\AvailableSlotRepository'

    Proximum\Vimeet\Infrastructure\Repository\Meeting\ParticipantExtraDataRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Transactional\Mail\MessageRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\StaticFormulation\StaticFormulationRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Domain\Repository\StaticFormulation\StaticFormulationRepositoryInterface: '@Proximum\Vimeet\Infrastructure\Repository\StaticFormulation\StaticFormulationRepository'

    Proximum\Vimeet\Infrastructure\Repository\Template\FormTemplateRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Sheet\FormDataRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\User\FormDataRepository:
        arguments:
            - '@doctrine.orm.entity_manager'
    Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\ContactRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\RegistrationPath\QuestionRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\RegistrationPath\AnswerRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Visio\VisioSettingsRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Sheet\ImportMappingRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\ChatMessageRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\ChatMessageVoteRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    Proximum\Vimeet\Infrastructure\Repository\Happening\Webinar\RecordArchiveRepository:
        arguments:
            - '@doctrine.orm.entity_manager'
