Proximum\Vimeet\Application\Command\Event\Content\UpdateTermsOfSale:
    properties:
        translations:
            - All:
                - Collection:
                    fields:
                        value:
                            - NotBlank: ~
