services:
    #
    # Form type
    #
    vimeet_app.form_type.who_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\WhoType
        arguments:
            - '@vimeet_infrastructure.repository.category_repository'
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: 'form.type' }
    vimeet_app.form_type_spot.spot_create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Spot\SpotCreateType
        tags:
            - { name: 'form.type' }
    vimeet_app.form_type.category_create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Category\CategoryCreateType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: 'form.type' }
    vimeet_app.form_type.category_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Category\CategoryUpdateType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: 'form.type' }
    form_type.category_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\CategoryChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.category_repository'
        tags:
            - { name: form.type }
    form_type.type_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\TypeChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: form.type }
    form_type_.sheet.follower_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\FollowerChoiceType
        arguments:
            - '@repository.admin_repository'
        tags:
            - { name: form.type }
    form_type.event_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Event\EventChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
        tags:
            - { name: form.type }
    vimeet_app.form_type_package.update_product_type:
        class: Proximum\Vimeet\Ui\Bundle\EventBundle\Form\Type\Package\UpdateProductType
        arguments:
            -
                lib_option: 'Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Library\OptionType'
        tags:
            - { name: form.type }
    form_type_template.sheet_template_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Template\SheetTemplateChoiceType
        arguments:
            - '@repository.sheet.template_repository'
        tags:
            - { name: form.type }
    form_type_sheet_template.organizer_create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\Template\CreateForEventType
        tags:
            - { name: form.type }
    form_type_sheet_template.organizer_duplicate_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\Template\DuplicateForEventType
        tags:
            - { name: form.type }
#
    # Admin library form type
    #
    vimeet_app.form_type_admin.library.type_factory:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Library\Admin\TypeFactory
        arguments:
            -
                lib_text:   'Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Library\Admin\TextType'
                lib_choice: 'Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Library\Admin\ChoiceType'
