services:
    #
    # Form type
    #
    vimeet_app.form_type.who_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\WhoType
        arguments:
            - '@vimeet_infrastructure.repository.category_repository'
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: 'form.type' }
    vimeet_app.form_type_spot.spot_create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Spot\SpotCreateType
        tags:
            - { name: 'form.type' }
    vimeet_app.form_type.category_create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Category\CategoryCreateType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: 'form.type' }
    vimeet_app.form_type.category_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Category\CategoryUpdateType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: 'form.type' }
    form_type.category_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\CategoryChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.category_repository'
        tags:
            - { name: form.type }
    form_type.type_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\TypeChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: form.type }
    form_type.sheet.follower_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\FollowerChoiceType
        arguments:
            - '@repository.admin_repository'
        tags:
            - { name: form.type }
    form_type.sheet.change_type_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\ChangeTypeType
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: form.type }
    form_type.event_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Event\EventChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
        tags:
            - { name: form.type }
    form_type.admin_event_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Event\AdminEventChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
        tags:
            - { name: form.type }
    form_type_template.sheet_template_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Template\SheetTemplateChoiceType
        arguments:
            - '@repository.template.sheet_template_repository'
        tags:
            - { name: form.type }
    form_type_sheet_template.organizer_create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\Template\CreateForEventType
        tags:
            - { name: form.type }
    form_type_sheet_template.organizer_duplicate_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\Template\DuplicateForEventType
        tags:
            - { name: form.type }
    form_type_template_registration.update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Template\Registration\UpdateType
        tags:
            - { name: form.type }
    form_type_library_admin.json_array_textarea_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Template\Registration\JsonArrayTextareaType
        tags:
            - { name: form.type }
    form_type_template.registration_template_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Template\RegistrationTemplateChoiceType
        arguments:
            - '@repository.template.registration_template_repository'
        tags:
            - { name: form.type }
    vimeet_app.form_type_meeting_request.meeting_request:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\MeetingRequest\PositionMeetingType
        arguments:
            - '@template.participant_info_guesser'
        tags:
            - { name: form.type }
    form_type_product.product_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Product\ProductChoiceType
        arguments:
            - '@vimeet_infrastructure.repository.product_repository'
            - '@ui.helper.currency_formatter'
        tags:
            - { name: form.type }
    form_type_package.package_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Package\PackageChoiceType
        arguments:
            - '@repository.package_repository'
        tags:
            - { name: form.type }
    form_type_event.event_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Event\UpdateType
        arguments:
            - '%infrastructure.supported_currencies%'
        tags:
            - { name: form.type }
    form_type_event.create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Event\CreateType
        arguments:
            - '%infrastructure.supported_currencies%'
        tags:
            - { name: form.type }
    form_type_type.type_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Type\TypeUpdateType
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
        tags:
            - { name: form.type }
    form_type_rule.see_what_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Rule\SeeWhatType
        arguments:
            - '@domain.rule.tag_identifier'
            - '@vimeet_infrastructure.adapter.translator_adapter'
        tags:
            - { name: form.type }

    form_type_product.abstract_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Product\AbstractUpdateType
        abstract: true
        arguments:
            - '@domain.product.update_price_resolver'
        tags:
            - { name: form.type }
    form_type_product.option_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Product\Option\UpdateOptionType
        parent: form_type_product.abstract_update_type
        tags:
            - { name: form.type }
    form_type_product.plan_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Product\Plan\UpdatePlanType
        parent: form_type_product.abstract_update_type
        tags:
            - { name: form.type }
    form_type_product.planning_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Product\Planning\UpdatePlanningType
        parent: form_type_product.abstract_update_type
        tags:
            - { name: form.type }
    form_type_product.participant_update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Product\Participant\UpdateParticipantType
        parent: form_type_product.abstract_update_type
        tags:
            - { name: form.type }
    form_type_partner.partner_type:
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        abstract: true
        tags:
            - { name: form.type }
    form_type_partner.create_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Partner\CreateType
        parent: form_type_partner.partner_type
        tags:
            - { name: form.type }
    form_type_partner.update_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Partner\UpdateType
        parent: form_type_partner.partner_type
        tags:
            - { name: form.type }
    form_type_sheet.batch_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\BatchType
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: form.type }

    form_type_sheet.predefined_filters_choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Sheet\PredefinedFiltersChoiceType
        arguments:
            - '@infrastructure.service.boolean_filters_builder'
        tags:
            - { name: form.type }
    form_type_unavailability_category.choice_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Unavailability\Category\ChoiceType
        arguments:
            - '@repository.unavailability.category_repository'
        tags:
            - { name: form.type }
    form_type_sheet.message_campaign_filters_type:
        class: Proximum\Vimeet\Ui\Bundle\AdminBundle\Form\Type\Messaging\Campaign\TargetFilterType
        arguments:
            - '@vimeet_infrastructure.repository.category_repository'
            - '@infrastructure.service.boolean_filters_builder'
        tags:
            - { name: form.type }

    #
    # Helper
    #
    ui.helper.currency_formatter:
        class: Proximum\Vimeet\Ui\Helper\CurrencyFormatter
        arguments:
            - '@twig.extension.intl'

    #
    # Subscriber
    #
    event_listener.locale_changed_event_subscriber:
        class: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\EventListener\LocaleChangedEventSubscriber
        arguments:
            - '@repository.template.sheet_template_repository'
            - '@repository.template.registration_template_repository'
        tags:
            - { name: kernel.event_subscriber }
    event_listener.registration_template_updated_event_subscriber:
        class: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\EventListener\Template\Registration\RegistrationTemplateUpdatedEventSubscriber
        arguments:
            - '@repository.template.registration_template_repository'
            - '@repository.filter.boolean_template_filter_repository'
            - '@repository.filter.tagged_nomenclature_filter_repository'
            - '@template.template_data_factory'
        tags:
            - { name: kernel.event_subscriber }
