services:
    Proximum\Vimeet\Ui\Bundle\AdminBundle\Controller\RegistrationTemplate\BuildAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@templating'
            - '@template.template_data_factory'
