services:
    command.sheet.aggregate.sheets_available_slot_aggregator_handler:
        class: Proximum\Vimeet\Application\Command\Sheet\Aggregate\SheetsAvailableSlotAggregatorHandler
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@command.sheet.aggregate.available_slot_aggregator_handler'
            - '@adapter.sheet_indexer'
    command.sheet.aggregate.available_slot_aggregator_handler:
        class: Proximum\Vimeet\Application\Command\Sheet\Aggregate\AvailableSlotAggregatorHandler
        arguments:
            - '@Proximum\Vimeet\Domain\Sheet\Aggregate\AvailableSlotCalculator'
    command.analytic.meeting_solution.create_handler:
        class: Proximum\Vimeet\Application\Command\Analytic\MeetingSolution\CreateHandler
        arguments:
            - '@adapter.serializer_adapter'
            - '@repository.analytic.meeting_solution_repository'
            - '@vimeet_infrastructure.repository.meeting_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'
            - '@vimeet_infrastructure.repository.spot_repository'
            - '@vimeet_infrastructure.repository.meeting_slot_repository'
            - '@query.analytic.meeting_solution.sheet.sheet_satisfaction_list_query_handler'
            - '@query.analytic.meeting_solution.spot.spot_satisfaction_list_query_handler'
            - '@query.analytic.meeting_solution.spot_filling_rate.spot_filling_rate_query_handler'
            - '@query.analytic.meeting_solution.filling_rate_query_handler'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Analytic\MeetingSolution\Create }

    #
    # Meeting
    #
    Proximum\Vimeet\Application\Command\Meeting\Admin\UpdateStatusHandler:
        arguments:
            - '@vimeet_infrastructure.repository.meeting_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Meeting\Admin\UpdateStatus }


    #
    # Extra Parameter
    #
    command.event.extra_parameter.create_handler:
        class: Proximum\Vimeet\Application\Command\Event\ExtraParameter\CreateHandler
        arguments:
            - '@repository.event.extra_parameter_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\ExtraParameter\Create }

    command.event.extra_parameter.update_handler:
        class: Proximum\Vimeet\Application\Command\Event\ExtraParameter\UpdateHandler
        arguments:
            - '@repository.event.extra_parameter_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\ExtraParameter\Update }
    command.event.extra_parameter.remove_handler:
        class: Proximum\Vimeet\Application\Command\Event\ExtraParameter\RemoveHandler
        arguments:
            - '@repository.event.extra_parameter_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\ExtraParameter\Remove }

    #
    # Sheet Phone
    #
    command.sheet.phone.update_phone_validation_status_handler:
        class: Proximum\Vimeet\Application\Command\Sheet\Phone\UpdatePhoneValidationStatusHandler
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@domain.sheet.phone.validation_calculator'

    #
    # User Event Token
    #
    command.user.event.token.update_agenda_confirmation_handler:
        class: Proximum\Vimeet\Application\Command\User\Event\Token\UpdateAgendaConfirmationHandler
        arguments:
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@repository.token.user_event_token_repository'
            - '@domain.token.user_event_token_generator'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\Event\Token\UpdateAgendaConfirmation }

    Proximum\Vimeet\Application\Command\User\Event\ActivateAccountTokenByUserAndSheetGuesserHandler:
        arguments:
            - '@components.token.user.activate_account_token_generator'
            - '@sheet.sheet_guesser'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\Event\ActivateAccountTokenByUserAndSheetGuesser }

    #
    # User Phone Ignore Confirmation
    #
    command.user.event.phone.ignore_confirmation:
        class: Proximum\Vimeet\Application\Command\User\Phone\IgnoreConfirmationHandler
        arguments:
            - '@repository.user.event.extra_data_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\Phone\IgnoreConfirmation }

    #
    # Type Badge
    #
    Proximum\Vimeet\Application\Command\Type\Badge\ConfigureHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\BadgeRepository'
            - '@adapter.local_file_storage'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Type\Badge\Configure }

    #
    # Type Payment Conditions
    #
    Proximum\Vimeet\Application\Command\Type\PaymentConditions\UpdateHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Type\PaymentConditionsRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Type\PaymentConditions\Update }

    #
    # Type Content
    #
    Proximum\Vimeet\Application\Command\Type\Content\DefineTermsOfSaleHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Type\ContentRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Type\Content\DefineTermsOfSale }

    #
    # Tip
    #
    command.tip.event.create_handler:
        class: Proximum\Vimeet\Application\Command\Tip\Event\CreateHandler
        arguments:
            - '@repository.tip.repository'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Tip\Event\Create }

    command.tip.event.update_handler:
        class: Proximum\Vimeet\Application\Command\Tip\Event\UpdateHandler
        arguments:
            - '@repository.tip.repository'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Tip\Event\Update }

    #
    # Event
    #
    Proximum\Vimeet\Application\Command\Event\Index\IndexHandler:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@adapter.job_queue_adapter'

    Proximum\Vimeet\Application\Command\Event\PrepareIndexHandler:
        arguments:
            - '@adapter.job_queue_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\PrepareIndex }

    Proximum\Vimeet\Application\Command\Event\UpdateHandler:
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\Update }

    Proximum\Vimeet\Application\Command\Event\CreateHandler:
        arguments:
            - '@repository.admin_repository'
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.event.content_repository'
            - '@guideline.generator'
            - '@domain.event.duplicator'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\Create }

    Proximum\Vimeet\Application\Command\Event\Design\UpdateDesignHandler:
        arguments:
             - '@vimeet_infrastructure.repository.event_repository'
             - '@adapter.local_file_storage'
             - '@command.event.configuration.background.remove_image_handler'
             - '@guideline.generator'
        tags:
             - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\Design\UpdateDesign }

    #
    # Event / Sheet
    #
    Proximum\Vimeet\Application\Command\Event\Sheet\IndexHandler:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@adapter.sheet_indexer'
            - '@adapter.sheet_search_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\Sheet\Index }

    Proximum\Vimeet\Application\Command\Event\Sheet\PrepareSheetsIndexHandler:
        arguments:
            - '@adapter.job_queue_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\Sheet\PrepareSheetsIndex }

    Proximum\Vimeet\Application\Command\Sheet\ChangeOwnerHandler:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@template.participant_info_guesser'
            - '@vimeet_infrastructure.adapter.translator_adapter'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Sheet\ChangeOwner }

    #
    # Availability Time Range
    #
    Proximum\Vimeet\Application\Command\AvailabilityTimeRange\CreateHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\AvailabilityTimeRangeRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\AvailabilityTimeRange\Create }

    #
    # Sheet change Type
    #
    Proximum\Vimeet\Application\Command\Sheet\ChangeType\CancelPackageHandler:
        arguments:
            - '@vimeet_infrastructure.repository.order_repository'
            - '@cart_manager'
            - '@Proximum\Vimeet\Domain\Participant\ParticipantProductSetter'
            - '@Proximum\Vimeet\Domain\ProductAttributedToParticipant\ProductsAttributedToParticipantRemoveAllBySheet'

    #
    # Export OMZ
    #
    Proximum\Vimeet\Application\Command\OMZ\ScheduleExportHandler:
        arguments:
            - '@adapter.job_queue_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\OMZ\ScheduleExport }

    Proximum\Vimeet\Application\Command\OMZ\PrepareContentHandler:
        arguments:
            - '@vimeet_infrastructure.repository.user_repository'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@domain.service.sheets_group.group_name_resolver'
            - '@domain.service.sheets_group.type_name_resolver'
            - '@components.user.user_info_guesser'
            - '@planning.formatter.participant_planning_formatter'
            - '@Proximum\Vimeet\Application\Query\Badge\QRCode\QRCodeIdentifierQueryHandler'
            - '@adapter.serializer_adapter'

    Proximum\Vimeet\Application\Command\OMZ\NotifyHandler:
        arguments:
            - '@adapter.mailer_adapter'
            - '%mailer_sender%'

    Proximum\Vimeet\Application\Command\OMZ\PersistContentHandler:
        arguments:
            - '@adapter.local_file_storage'
            - '@repository.file_repository'
            - '%infrastructure.export_omz_path%'
            - '@datetime'

    Proximum\Vimeet\Application\Command\OMZ\ExportHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Command\OMZ\PrepareContentHandler'
            - '@Proximum\Vimeet\Application\Command\OMZ\PersistContentHandler'
            - '@Proximum\Vimeet\Application\Command\OMZ\NotifyHandler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\OMZ\Export }

    #
    # Group
    #
    Proximum\Vimeet\Application\Command\Group\DuplicateToEventHandler:
        arguments:
            - '@repository.sheet.group_repository'
            - '@user_to_group_manager_checker'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Group\DuplicateToEvent }

    #
    # Participant
    #
    Proximum\Vimeet\Application\Command\Participant\Export\PrepareExportHandler:
        arguments:
            - '@adapter.sheet_search_adapter'
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Event\ExtraDataRepository'
            - '@adapter.job_queue_adapter'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Participant\Export\PrepareExport }

    Proximum\Vimeet\Application\Command\Participant\Export\ExportHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Query\Participant\Export\ExportQueryHandler'
            - '@adapter.serializer_adapter'
            - '@repository.file_repository'
            - '@adapter.local_file_storage'
            - '@adapter.mailer_adapter'
            - '%infrastructure.export_participant_path%'
            - '%mailer_sender%'
            - '@datetime'

    #
    # RegistrationTemplate
    #
    Proximum\Vimeet\Application\Command\Template\Registration\DuplicateHandler:
        arguments:
            - '@template.registration.registration_template_cloner'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Template\Registration\Duplicate }

    Proximum\Vimeet\Application\Command\Template\Registration\CreateHandler:
        arguments:
            - '@repository.template.registration_template_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Template\Registration\Create }

    #
    # Form Template
    #
    Proximum\Vimeet\Application\Command\Template\Form\CreateHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Template\FormTemplateRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Template\Form\Create }

    #
    # Order
    #
    Proximum\Vimeet\Application\Command\Order\CancelAllHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Sheet\ChangeType\CancelPackageHandler'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Order\CancelAll }

    #
    # Transactional
    #
    #### Mail
    Proximum\Vimeet\Application\Command\Transactional\Mail\CustomizeHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Transactional\Mail\MessageRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Transactional\Mail\Customize }

    Proximum\Vimeet\Application\Command\Transactional\Mail\UpdateCustomizedHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Transactional\Mail\MessageRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Transactional\Mail\UpdateCustomized }

    #
    # Scan
    #
    Proximum\Vimeet\Application\Command\User\Event\ScanEventEntranceCommandHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ScanRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\Event\ScanEventEntranceCommand }

    Proximum\Vimeet\Application\Command\Scan\Happening\ScanHappeningHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ScanRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Scan\Happening\ScanHappening }

    #
    # Static Formulation
    #
    Proximum\Vimeet\Application\Command\StaticFormulation\CreateHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\StaticFormulation\StaticFormulationRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\StaticFormulation\Create }

    Proximum\Vimeet\Application\Command\StaticFormulation\UpdateHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\StaticFormulation\StaticFormulationRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\StaticFormulation\Update }
