services:
    command.sheet.aggregate.available_slot_aggregator_handler:
        class: Proximum\Vimeet\Application\Command\Sheet\Aggregate\AvailableSlotAggregatorHandler
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@domain.sheet.aggregate.available_slot_calculator'
    command.analytic.meeting_solution.create_handler:
        class: Proximum\Vimeet\Application\Command\Analytic\MeetingSolution\CreateHandler
        arguments:
            - '@adapter.serializer_adapter'
            - '@repository.analytic.meeting_solution_repository'
            - '@vimeet_infrastructure.repository.meeting_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'
            - '@vimeet_infrastructure.repository.spot_repository'
            - '@vimeet_infrastructure.repository.meeting_slot_repository'
            - '@query.analytic.meeting_solution.sheet.sheet_satisfaction_list_query_handler'
            - '@query.analytic.meeting_solution.spot.spot_satisfaction_list_query_handler'
            - '@query.analytic.meeting_solution.spot_filling_rate.spot_filling_rate_query_handler'
            - '@query.analytic.meeting_solution.filling_rate_query_handler'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Analytic\MeetingSolution\Create }

    #
    # Extra Parameter
    #
    command.event.extra_parameter.create_handler:
        class: Proximum\Vimeet\Application\Command\Event\ExtraParameter\CreateHandler
        arguments:
            - '@repository.event.extra_parameter_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\ExtraParameter\Create }

    command.event.extra_parameter.update_handler:
        class: Proximum\Vimeet\Application\Command\Event\ExtraParameter\UpdateHandler
        arguments:
            - '@repository.event.extra_parameter_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\ExtraParameter\Update }
    command.event.extra_parameter.remove_handler:
        class: Proximum\Vimeet\Application\Command\Event\ExtraParameter\RemoveHandler
        arguments:
            - '@repository.event.extra_parameter_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Event\ExtraParameter\Remove }

    #
    # THIRD PARTY
    #
    command.third_party.leni.prepare_leni_api_handler:
        class: Proximum\Vimeet\Application\ThirdParty\LENI\Command\PrepareLeniApiCallHandler
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.event.extra_parameter_repository'
            - '@repository.user.event.extra_data_repository'
            - '@vimeet_infrastructure.repository.user_repository'
            - '@planning.formatter.participant_planning_formatter'
            - '@query.api.leni.leni_user_view_query_handler'
            - '@command.third_party.leni.leni_api_call_handler'
            - '@adapter.serializer_adapter'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\ThirdParty\LENI\PrepareLeniApiCall }

    command.third_party.leni.leni_api_call_handler:
        class: Proximum\Vimeet\Application\ThirdParty\LENI\Command\LeniApiCallHandler
        arguments:
            - '@adapter.http_adapter'
