services:

    #
    # Spot importer component
    #
    components.spot.spot_importer:
        class: Proximum\Vimeet\Application\Components\Spot\SpotImporter
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@adapter.validator_adapter'
            - '@vimeet_infrastructure.adapter.translator_adapter'
            - '@adapter.serializer_adapter'
            - '%infrastructure.import_spot_path%'


    #
    # Group
    #
    Proximum\Vimeet\Application\Components\Group\GroupDuplicator:
        arguments:
            - '@Proximum\Vimeet\Application\Command\Group\DuplicateToEventHandler'
