services:
    query.analytic.meeting_solution.spot.spot_satisfaction_view_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\Spot\SpotSatisfactionViewQueryHandler

    query.analytic.meeting_solution.spot.spot_satisfaction_list_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\Spot\SpotSatisfactionListQueryHandler
        arguments:
            - '@vimeet_infrastructure.repository.spot_repository'
            - '@vimeet_infrastructure.repository.meeting_repository'
            - '@query.analytic.meeting_solution.spot.spot_satisfaction_view_query_handler'

    query.analytic.meeting_solution.sheet.sheet_satisfaction_view_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\Sheet\SheetSatisfactionViewQueryHandler

    query.analytic.meeting_solution.sheet.sheet_satisfaction_list_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\Sheet\SheetSatisfactionListQueryHandler
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'
            - '@vimeet_infrastructure.repository.meeting_repository'
            - '@query.analytic.meeting_solution.sheet.sheet_satisfaction_view_query_handler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\Sheet\SheetSatisfactionListQuery }

    query.analytic.meeting_solution.spot_filling_rate.spot_filling_rate_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\SpotFillingRate\SpotFillingRateQueryHandler
        arguments:
            - '@vimeet_infrastructure.repository.meeting_repository'

    query.analytic.meeting_solution.meeting_solution_list_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\MeetingSolutionListQueryHandler
        arguments:
            - '@repository.analytic.meeting_solution_repository'
            - '@adapter.serializer_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\MeetingSolutionListQuery }

    query.analytic.meeting_solution.filling_rate_query_handler:
        class: Proximum\Vimeet\Application\Query\Analytic\MeetingSolution\FillingRateQueryHandler
        arguments:
            - '@vimeet_infrastructure.repository.meeting_repository'

    #
    # Meeting Request Export
    #
    query.meeting_request.export.sheet_view_query_handler:
        class: Proximum\Vimeet\Application\Query\MeetingRequest\Export\SheetViewQueryHandler
        arguments:
            - '@command.planning.participant_info_guesser_cache'

    query.meeting_request.export.meeting_request_view_query_handler:
        class: Proximum\Vimeet\Application\Query\MeetingRequest\Export\MeetingRequestViewQueryHandler
        arguments:
            - '@query.meeting_request.export.sheet_view_query_handler'

    query.meeting_request.export.meeting_request_list_view_query_handler:
        class: Proximum\Vimeet\Application\Query\MeetingRequest\Export\MeetingRequestListViewQueryHandler
        arguments:
            - '@vimeet_infrastructure.repository.meeting.request_repository'
            - '@query.meeting_request.export.meeting_request_view_query_handler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\MeetingRequest\Export\MeetingRequestListViewQuery }

    #
    # Meeting Slot
    #
    Proximum\Vimeet\Application\Query\MeetingSlot\GetAvailableSlotsQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.spot_repository'
            - '@vimeet_infrastructure.repository.meeting_slot_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\MeetingSlot\GetAvailableSlotsQuery }

    #
    # Sheet Details
    #
    query.sheet.detail.participant.phone_validation_status_query_handler:
        class: Proximum\Vimeet\Application\Query\Sheet\Detail\Participant\PhoneValidationStatusQueryHandler
        arguments:
            - '@domain.user_event.user_event_phone_checker'

    query.sheet.detail.participant.availability_confirmation_status_query_handler:
        class: Proximum\Vimeet\Application\Query\Sheet\Detail\Participant\AvailabilityConfirmationStatusQueryHandler
        arguments:
            - '@repository.user.event.extra_data_repository'

    #
    # Type
    #
    Proximum\Vimeet\Application\Query\Type\TypesWithPaymentConditionsViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Type\TypesWithPaymentConditionsViewQuery }

    #
    # Availability Time Range
    #
    Proximum\Vimeet\Application\Query\AvailabilityTimeRange\ListViewQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\AvailabilityTimeRangeRepository'
            - '@Proximum\Vimeet\Application\Query\AvailabilityTimeRange\AvailabilityTimeRangeViewQueryHandler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\AvailabilityTimeRange\ListViewQuery }

    Proximum\Vimeet\Application\Query\AvailabilityTimeRange\AvailabilityTimeRangeViewQueryHandler: ~

    #
    # Participant Export
    #
    Proximum\Vimeet\Application\Query\Participant\Export\ParticipantViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.happening_participation_repository'
            - '@template.template_data_factory'
            - '@Proximum\Vimeet\Domain\Sheet\HasRemainingToPay'
            - '@vimeet_infrastructure.adapter.translator_adapter'
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@Proximum\Vimeet\Infrastructure\Repository\ScanRepository'
            - '@vimeet_infrastructure.repository.happening_repository'

    #
    # Meeting
    #
    Proximum\Vimeet\Application\Query\Meeting\Admin\ListMeeting\ParticipantViewQueryHandler:
        arguments:
            - '@template.participant_info_guesser'
            - '@Proximum\Vimeet\Infrastructure\Repository\ScanRepository'
            - '@Proximum\Vimeet\Domain\Meeting\IsParticipantPresentToMeeting'
            - '@Proximum\Vimeet\Domain\Participant\IsParticipantVisio'

    Proximum\Vimeet\Application\Query\Meeting\Admin\ListMeeting\MeetingViewQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Query\Meeting\Admin\ListMeeting\ParticipantViewQueryHandler'

    Proximum\Vimeet\Application\Query\Meeting\Admin\ListMeeting\MeetingListViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.meeting_repository'
            - '@Proximum\Vimeet\Application\Query\Meeting\Admin\ListMeeting\MeetingViewQueryHandler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Meeting\Admin\ListMeeting\MeetingListViewQuery }

    #
    # Transactional
    #
    ### Mail
    Proximum\Vimeet\Application\Query\Transactional\Mail\Customize\CustomizedMailViewQueryHandler: ~

    Proximum\Vimeet\Application\Query\Transactional\Mail\Generic\GenericMailViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.adapter.translator_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Transactional\Mail\Generic\GenericMailViewQuery }

    Proximum\Vimeet\Application\Query\Transactional\Mail\TransactionalMailListViewQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Query\Transactional\Mail\Generic\GenericMailViewQueryHandler'
            - '@Proximum\Vimeet\Application\Query\Transactional\Mail\Customize\CustomizedMailViewQueryHandler'
            - '@vimeet_infrastructure.repository.type_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Transactional\Mail\MessageRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Transactional\Mail\TransactionalMailListViewQuery }

    #
    # Scan
    #
    #### Happening
    Proximum\Vimeet\Application\Query\Scan\Happening\ListViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.happening_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Scan\Happening\ListViewQuery }

    #
    # Static Formulation
    #
    Proximum\Vimeet\Application\Query\StaticFormulation\StaticFormulationListViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.type_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\StaticFormulation\StaticFormulationRepository'
            - '@vimeet_infrastructure.adapter.translator_adapter'
            - '@Proximum\Vimeet\Application\Query\StaticFormulation\Customized\CustomizedStaticFormulationViewQueryHandler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\StaticFormulation\StaticFormulationListViewQuery }

    Proximum\Vimeet\Application\Query\StaticFormulation\Customized\CustomizedStaticFormulationViewQueryHandler: ~

    #
    # Form Template
    #
    Proximum\Vimeet\Application\Query\Template\Form\FormTemplateListViewQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Template\FormTemplateRepository'
            - '@adapter.event_url_generator'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Template\Form\FormTemplateListViewQuery }

    #
    # Admin
    #
    Proximum\Vimeet\Application\Query\Admin\AdminListViewQueryHandler:
        arguments:
            - '@repository.admin_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Admin\AdminListViewQuery }

    Proximum\Vimeet\Application\Query\Operator\OperatorListViewQueryHandler:
        arguments:
            - '@repository.admin_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Operator\OperatorListViewQuery }

    #
    # Rooming
    #
    Proximum\Vimeet\Application\Query\Rooming\RoomingList\ListViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.user_repository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository'
            - '@repository.user.event.extra_data_repository'
            - '@Proximum\Vimeet\Domain\Time\OverlappedTimeRangeTruncater'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Rooming\RoomingList\ListViewQuery }

    Proximum\Vimeet\Application\Query\Rooming\Accommodation\AccommodationListByPeriodQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\AccommodationRepository'
            - '@Proximum\Vimeet\Domain\Rooming\Accommodation\HasRemainingOvernight'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Rooming\Accommodation\AccommodationListByPeriodQuery }

    Proximum\Vimeet\Application\Query\Rooming\Stay\GetRoommatesHandler:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Rooming\Stay\GetRoommates }

    Proximum\Vimeet\Application\Query\Rooming\Accommodation\AccommodationListViewQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\AccommodationRepository'
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Rooming\Accommodation\AccommodationListViewQuery }

    Proximum\Vimeet\Application\Query\Template\Form\ExportFormTemplateData\FormTemplateDataForUserHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Query\Template\Form\FormTemplateDataQueryHandler'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@template.participant_info_guesser'
            - '@vimeet_infrastructure.application.components.sheet.sheet_info_guesser'
            - '@Proximum\Vimeet\Domain\User\Sheet\FirstParticipantSheetOfUserGetter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Template\Form\ExportFormTemplateData\FormTemplateDataForUser }

    Proximum\Vimeet\Application\Query\Template\Form\ExportFormTemplateData\FormTemplateDataUserListViewQueryHandler:
        arguments:
            - '@template.template_data_factory'
            - '@Proximum\Vimeet\Application\Query\Template\Form\ExportFormTemplateData\FormTemplateDataForUserHandler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Template\Form\ExportFormTemplateData\FormTemplateDataUserListViewQuery }

    Proximum\Vimeet\Application\Query\Rooming\RoomingList\Export\UserViewQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@repository.user.event.extra_data_repository'
            - '@order.merger'

    Proximum\Vimeet\Application\Query\Rooming\RoomingList\Export\RoomingListViewQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Rooming\StayRepository'
            - '@Proximum\Vimeet\Application\Query\Rooming\RoomingList\Export\UserViewQueryHandler'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Rooming\RoomingList\Export\RoomingListViewQuery }

    Proximum\Vimeet\Application\Query\Rooming\Stay\GetSheetsByEventQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Rooming\Stay\GetSheetsByEventQuery }

    Proximum\Vimeet\Application\Query\PromotionCode\Batch\PromotionCodeGroupList\GetListViewHandler:
        arguments:
            - '@Proximum\Vimeet\Application\Query\PromotionCode\Batch\CanBeUpdatable'
            - '@Proximum\Vimeet\Infrastructure\Repository\PromotionCodeGroupRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\PromotionCode\Batch\PromotionCodeGroupList\GetListView }

    Proximum\Vimeet\Application\Query\PromotionCode\Batch\CanBeUpdatable:
        arguments:
            - '@vimeet_infrastructure.repository.order_repository'

    #
    # RegistrationPath
    #
    Proximum\Vimeet\Application\Query\RegistrationPath\EventRegistrationPathQueryHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\RegistrationPath\QuestionRepository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\RegistrationPath\EventRegistrationPathQuery }

    #
    # Visio
    #
    Proximum\Vimeet\Application\Query\Visio\UpdateVisioSettingsViewQueryHandler:
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Query\Visio\UpdateVisioSettingsViewQuery }
