services:
    normalizer.analytic.meeting_solution.spot_filling_rate_slot_view_normalizer:
        class: Proximum\Vimeet\Application\Serializer\Normalizer\Analytic\MeetingSolution\SpotFillingRateSlotViewNormalizer
        tags:
            - { name: serializer.normalizer }

    normalizer.analytic.meeting_solution.spot_filling_rate_day_view_normalizer:
        class: Proximum\Vimeet\Application\Serializer\Normalizer\Analytic\MeetingSolution\SpotFillingRateDayViewNormalizer
        tags:
            - { name: serializer.normalizer }

    normalizer.analytic.meeting_solution.spot_satisfaction_view_normalizer:
        class: Proximum\Vimeet\Application\Serializer\Normalizer\Analytic\MeetingSolution\SpotSatisfactionViewNormalizer
        tags:
            - { name: serializer.normalizer }

    normalizer.analytic.meeting_solution.sheet_satisfaction_view_normalizer:
        class: Proximum\Vimeet\Application\Serializer\Normalizer\Analytic\MeetingSolution\SheetSatisfactionViewNormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.sheet_satisfaction_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SheetSatisfactionViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.spot_filling_rate_day_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SpotFillingRateDayViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.spot_filling_rate_slot_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SpotFillingRateSlotViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.spot_satisfaction_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SpotSatisfactionViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.spot_satisfaction_list_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SpotSatisfactionListViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.spot_filling_rate_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SpotFillingRateViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    denormalizer.analytic.meeting_solution.sheet_satisfaction_list_view_denormalizer:
        class: Proximum\Vimeet\Application\Serializer\Denormalizer\Analytic\MeetingSolution\SheetSatisfactionListViewDenormalizer
        tags:
            - { name: serializer.normalizer }

    serializer.normalizer.meeting_request.meeting_request_list_view_normalizer:
        class: Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Serializer\Normalizer\MeetingRequest\MeetingRequestListViewNormalizer
        arguments:
            - '@vimeet_infrastructure.adapter.translator_adapter'
        tags:
            - { name: serializer.normalizer }

    Proximum\Vimeet\Application\Components\Meeting\RequestImportDenormalizer:
        tags:
            - { name: serializer.normalizer }

    Proximum\Vimeet\Application\Serializer\Normalizer\Participant\Export\ParticipantListViewNormalizer:
        arguments:
            - '@vimeet_infrastructure.adapter.translator_adapter'
        tags:
            - { name: serializer.normalizer }

    Proximum\Vimeet\Application\Query\Participant\Export\ExportQueryHandler:
        arguments:
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@Proximum\Vimeet\Application\Query\Participant\Export\ParticipantViewQueryHandler'
            - '@template.template_data_factory'
            - '@vimeet_infrastructure.repository.product_repository'
            - '@vimeet_infrastructure.repository.happening_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'
            - '@vimeet_infrastructure.repository.meeting_repository'

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Serializer\Normalizer\Template\Form\ExportData\UserListViewNormalizer:
        arguments:
            - '@translator'
        tags:
            - { name: serializer.normalizer }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Serializer\Normalizer\Product\ProductsExportNormalizer:
        arguments:
            - '@vimeet_infrastructure.adapter.translator_adapter'
        tags:
            - { name: serializer.normalizer }

    Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Serializer\Normalizer\Rooming\ExportList\RoomingListViewNormalizer:
        arguments:
           - '@translator'
        tags:
            - { name: serializer.normalizer }
