Proximum\Vimeet\Domain\Template\TemplateData:
    constraints:
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\ProfileDataConstraint: { groups: [profile] }
        - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Template\CompanyDataConstraint: { groups: [company] }

