services:
    #
    # Sheet
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Sheet\ObjectsCollectionUpdateAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@templating'
            - '@template.template_data_factory'
            - '@form.factory'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
            - '@Proximum\Vimeet\Domain\Template\ObjectsCollectionBlock\BlockToArray'
            - '@Proximum\Vimeet\Domain\Template\ObjectsCollectionBlock\SetArrayContentToBlock'
            - '@adapter.router'

    #
    # Package
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Package\SummaryAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@cart_cleaner'
            - '@package.funnel.funnel_factory'
            - '@adapter.router'
            - '@repository.billing_info_repository'
            - '@session.flash_bag'
            - '@form.factory'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
            - '@templating'

    #
    # Order
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Order\SummaryTotalAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@order.merger'
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
            - '@templating'

    #
    # Happening
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Happening\HappeningParticipateAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@Proximum\Vimeet\Ui\Bundle\EventBundle\Handler\Happening\ParticipateHandler'

    #
    # Download file
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\DownloadFileAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@template.template_data_factory'
            - '@Proximum\Vimeet\Application\Command\Encryption\DecryptHandler'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@serializer.normalizer.data_uri'
            - '@templating.engine.twig'
            - '%infrastructure.encrypted_files_path%'
            - '%kernel.project_dir%/web'

    #
    # Visio
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Visio\Test\CreateTestNetworkSessionAction:
        arguments:
            - '@adapter.video_conference_adapter'
            - '@adapter.router'
            - '@adapter.authorization_checker'

    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Visio\Test\TestNetworkSessionAction:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
            - '@templating'
            - '@adapter.authorization_checker'

    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Visio\Test\VisioTestedAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'

    #
    # Package Payment
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Package\Payment\PayRemainingAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
            - '@repository.transaction'
            - '@router'
            - '@order.balance'
            - '@datetime'

    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Package\Payment\InfoAction:
        arguments:
            - '@adapter.authorization_checker'
            - '@templating'
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'

    #
    # Agenda
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\ParticipantTimezoneAction:
        arguments:
            - '@templating.engine.twig'
            - '@form.factory'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
            - '@router'
            - '@Proximum\Vimeet\Application\Adapter\AuthorizationCheckerAdapterInterface'
            - '@Proximum\Vimeet\Domain\Event\GetTimezoneHelper'

    #
    # Badge
    #
    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Badge\ShowAction:
        arguments:
            - '@Proximum\Vimeet\Domain\Badge\AvailableChecker'
            - '@adapter.authorization_checker'
            - '@templating'
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'

    Proximum\Vimeet\Ui\Bundle\EventBundle\Controller\Badge\DownloadAction:
        arguments:
            - '@repository.token.user_event_token_repository'
            - '@templating'
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
            - '@Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Printer\EBadgePdfPrinter'
