services:
    command.meeting_request.reminder_handler:
        class: Proximum\Vimeet\Application\Command\MeetingRequest\ReminderHandler
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@repository.user.event.extra_data_repository'
            - '@repository.user.user_event_phone_repository'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@datetime'
            - '@adapter.smssender_alias'
            - '@service.smsfactory'
            - '@command.meeting_request.counter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\MeetingRequest\Remind }

    command.meeting_request.counter:
        class: Proximum\Vimeet\Application\Command\MeetingRequest\Counter
        arguments:
            - '@query.agenda.available_sheets.available_slots_by_participant_query_handler'
            - '@vimeet_infrastructure.repository.meeting.request_repository'

    command.user.availability.confirmation_handler:
        class: Proximum\Vimeet\Application\Command\User\Availability\ConfirmationHandler
        arguments:
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@repository.user.event.extra_data_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\Availability\Confirmation }

    Proximum\Vimeet\Application\Command\Meeting\ParticipantPresenceCommandHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\Meeting\ParticipantExtraDataRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Meeting\ParticipantPresenceCommand }

    Proximum\Vimeet\Application\Command\Template\Form\FillStepCommandHandler:
        arguments:
              - '@adapter.authorization_checker'
              - '@Proximum\Vimeet\Infrastructure\Repository\User\FormDataRepository'
              - '@Proximum\Vimeet\Infrastructure\Repository\Sheet\FormDataRepository'
              - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Template\Form\FillStepCommand }

    Proximum\Vimeet\Application\Command\User\ActivateAccount\SendActivateAccountFromLoginTokenHandler:
        arguments:
            - '@components.token.user.activate_account_token_generator'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\ActivateAccount\SendActivateAccountFromLoginToken }

    Proximum\Vimeet\Application\Command\Happening\Webinar\StartWebinarSessionCommandHandler:
        arguments:
            - '@adapter.video_conference_adapter'
            - '@vimeet_infrastructure.repository.happening_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Happening\Webinar\StartWebinarSessionCommand }

    Proximum\Vimeet\Application\Command\Happening\Webinar\Question\AddHappeningQuestionHandler:
        arguments:
            - '@vimeet_infrastructure.repository.happening_question_repository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Happening\Webinar\Question\AddHappeningQuestion }

    Proximum\Vimeet\Application\Command\Happening\Webinar\Question\VoteHappeningQuestionHandler:
        arguments:
            - '@vimeet_infrastructure.repository.happening_question_repository'
            - '@vimeet_infrastructure.repository.happening_question_vote_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Happening\Webinar\Question\VoteHappeningQuestion }

    Proximum\Vimeet\Application\Command\Sheet\SortParticipantsHandler:
        arguments:
            - '@vimeet_infrastructure.repository.participant_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Sheet\SortParticipants }

    Proximum\Vimeet\Application\Command\Happening\Export\ExportHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
            - '@Proximum\Vimeet\Infrastructure\Adapter\CommandBus'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Happening\Export\Export }

    Proximum\Vimeet\Application\Command\Happening\Export\ScheduleExportHandler:
        arguments:
            - '@vimeet_infrastructure.repository.happening_participation_repository'
            - '@adapter.job_queue_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Happening\Export\ScheduleExport }

    Proximum\Vimeet\Application\Command\File\PersistContentHandler:
        arguments:
            - '@Proximum\Vimeet\Domain\File\FileFactory'
            - '@adapter.local_file_storage'
            - '%infrastructure.common_export_path%'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\File\PersistContent }

    Proximum\Vimeet\Application\Command\Happening\Export\NotifyHandler:
        arguments:
            - '@adapter.mailer_adapter'
            - '@adapter.router'
            - '@vimeet_infrastructure.adapter.translator_adapter'
            - '%mailer_sender%'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Happening\Export\Notify }

    #
    # Unavailabilities
    #
    Proximum\Vimeet\Application\Command\Unavailability\RemoveUserUnavailabilitiesHandler:
        arguments:
            - '@vimeet_infrastructure.repository.unavailability_repository'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Unavailability\RemoveUserUnavailabilities }

    #
    # Contact
    #
    Proximum\Vimeet\Application\Command\Contact\AddHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ContactRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Contact\Add }

    #
    # Meeting
    #
    Proximum\Vimeet\Application\Command\Meeting\EvaluateMeetingHandler:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ContactRepository'
            - '@datetime'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Meeting\EvaluateMeeting }

    Proximum\Vimeet\Application\Command\Meeting\AddParticipantToMeetingHandler:
        arguments:
            - '@vimeet_infrastructure.repository.meeting_repository'
            - '@vimeet_infrastructure.repository.participant_repository'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Meeting\AddParticipantToMeeting }

    #
    # Account
    #
    Proximum\Vimeet\Application\Command\User\ChangeMailHandler:
        arguments:
            - '@vimeet_infrastructure.repository.user_repository'
            - '@repository.change_mail_token_repository'
            - '@components.token.change_mail_token_generator'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@vimeet_infrastructure.adapter.encoder_adapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\ChangeMail }
    Proximum\Vimeet\Application\Command\User\ChangeMailActivationHandler:
        arguments:
            - '@vimeet_infrastructure.repository.user_repository'
            - '@repository.change_mail_token_repository'
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\User\ChangeMailActivation }


    #
    # Sheet object
    #
    Proximum\Vimeet\Application\Command\Sheet\TemplateObject\Video\RemoveVideoHandler:
        arguments:
            - '@command.sheet.remove_data_handler'
            - '@Proximum\Vimeet\Infrastructure\Adapter\VideoStorageAdapter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\Sheet\TemplateObject\Video\RemoveVideo }
