services:
    command.meeting_request.reminder_handler:
        class: Proximum\Vimeet\Application\Command\MeetingRequest\ReminderHandler
        arguments:
            - '@vimeet_infrastructure.repository.event_repository'
            - '@vimeet_infrastructure.repository.user_repository'
            - '@repository.user.event.extra_data_repository'
            - '@vimeet_infrastructure.repository.sheet_repository'
            - '@datetime'
            - '@command.meeting_request.sms_notification'
            - '@command.meeting_request.counter'
        tags:
            - { name: tactician.handler, command: Proximum\Vimeet\Application\Command\MeetingRequest\Remind }

    command.meeting_request.sms_notification:
        class: Proximum\Vimeet\Application\Command\MeetingRequest\SmsNotification
        arguments:
            - '@adapter.smssender_alias'
            - '@vimeet_infrastructure.adapter.translator_adapter'
            - '@adapter.event_url_generator'

    command.meeting_request.counter:
        class: Proximum\Vimeet\Application\Command\MeetingRequest\Counter
        arguments:
            - '@vimeet_infrastructure.repository.meeting_slot_repository'
            - '@vimeet_infrastructure.repository.meeting.request_repository'
