services:
    Proximum\Vimeet\Application\Components\Participant\Remove\ProductAttributedToParticipantConflictChecker:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@Proximum\Vimeet\Infrastructure\Repository\CartRowParticipantRepository'
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Application\Components\Template\Object\UploadObjectDownloadPathGetter:
        arguments:
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@Proximum\Vimeet\Application\Command\Encryption\DecryptHandler'
            - '@adapter.file_system_adapter'
            - '%kernel.project_dir%/web'
            - '%infrastructure.encrypted_files_path%'

    Proximum\Vimeet\Application\Components\Type\HasUnavailabilityManagementDisabled:
        arguments:
            - '@adapter.authorization_checker'
