services:
    Proximum\Vimeet\Application\Components\Participant\Remove\ProductAttributedToParticipantConflictChecker:
        arguments:
            - '@Proximum\Vimeet\Infrastructure\Repository\ProductAttributedToParticipantRepository'
            - '@Proximum\Vimeet\Infrastructure\Repository\CartRowParticipantRepository'
            - '@template.participant_info_guesser'

    Proximum\Vimeet\Application\Components\Participant\ParticipantGuesser:
        arguments:
            - '@vimeet_infrastructure.repository.sheet_repository'

    Proximum\Vimeet\Application\Components\Template\Object\UploadObjectDownloadPathGetter:
        arguments:
            - '@vimeet_infrastructure.adapter.delayed_event_dispatcher'
            - '@Proximum\Vimeet\Application\Command\Encryption\DecryptHandler'
            - '@adapter.file_system_adapter'
            - '%kernel.project_dir%/web'
            - '%infrastructure.encrypted_files_path%'

    Proximum\Vimeet\Application\Components\Type\HasUnavailabilityManagementDisabled:
        arguments:
            - '@adapter.authorization_checker'

    Proximum\Vimeet\Application\Components\Type\HasAvailabilityManagementEnabled:

    Proximum\Vimeet\Application\Components\Contact\CanParticipantSeeContact:
        arguments:
            - '@Proximum\Vimeet\Application\Query\Contact\GetContactListUsersViewQueryHandler'

    Proximum\Vimeet\Application\Query\Happening\Webinar\CanAccessToWebinar:
        arguments:
            - '@vimeet_infrastructure.repository.happening_participation_repository'
            - '@datetime'
            - '%feature_video_conference_date_security_enabled%'
            - '%feature_video_conference_enabled%'

    Proximum\Vimeet\Application\Components\Catalog\GetViewedSheetsFromFilters:
        arguments:
            - '@repository.sheet.sheet_viewed_repository'

    Proximum\Vimeet\Application\Components\Contact\CanAccessToContacts:
        arguments:
            - '@domain.key_dates.checker.event_open_access_checker'
            - '@Proximum\Vimeet\Domain\Scan\CanScanParticipant'
            - '@Proximum\Vimeet\Infrastructure\Repository\ChatSessionRepository'
