services:
    Proximum\Vimeet\Application\Serializer\Normalizer\Catalog\Export\SheetViewNormalizer:
        tags:
            - { name: serializer.normalizer }
    Proximum\Vimeet\Application\Serializer\Normalizer\Catalog\Export\SheetListViewNormalizer:
        tags:
            - { name: serializer.normalizer }
