services:
  #
  # Networking
  #
  Proximum\Vimeet\Ui\Bundle\EventBundle\TemplateSnippet\NetworkingTemplateSnippet:
    arguments:
      - '@templating'
      - '@Proximum\Vimeet\Infrastructure\Adapter\QueryBus'
