snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn: '%redis_dsn%/1'
            logging: '%kernel.debug%'
    session:
        client: session
        prefix: session
        ttl: 86400
