services:
    #
    # Repositories
    #
    vimeet_infrastructure.repository.event_repository:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\Repository\EventRepository
        arguments:
            - @doctrine.orm.entity_manager
            - @knp_paginator
    vimeet_infrastructure.repository.type_repository:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\Repository\TypeRepository
        arguments:
            - @doctrine.orm.entity_manager
    vimeet_infrastructure.repository.user_repository:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\Repository\UserRepository
        arguments:
            - @doctrine.orm.entity_manager
    vimeet_infrastructure.repository.participant_repository:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\Repository\ParticipantRepository
        arguments:
            - @doctrine.orm.entity_manager
    vimeet_infrastructure.repository.sheet_repository:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\Repository\SheetRepository
        arguments:
            - @doctrine.orm.entity_manager

    #
    # Fixture providers
    #
    vimeet_infrastructure.data_fixtures_orm.provider:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\DataFixtures\ORM\Provider
        arguments:
            - %domain%
        tags:
            - { name: hautelook_alice.faker.provider }

    #
    # Handlers
    #
    vimeet_infrastructure.application.command.user.register_handler:
        class: Proximum\Vimeet\Application\Command\User\RegisterHandler
        arguments:
            - @vimeet_infrastructure.repository.user_repository
            - @vimeet_infrastructure.adapter.encoder_adapter
            - @vimeet_infrastructure.adapter.salt_generator
    vimeet_infrastructure.application.command.user.change_password:
        class: Proximum\Vimeet\Application\Command\User\ChangePasswordHandler
        arguments:
            - @vimeet_infrastructure.repository.user_repository
            - @vimeet_infrastructure.adapter.encoder_adapter
            - @vimeet_infrastructure.adapter.salt_generator
    vimeet_infrastructure.application.command.user.participate_handler:
        class: Proximum\Vimeet\Application\Command\User\ParticipateHandler
        arguments:
            - @vimeet_infrastructure.repository.sheet_repository
            - @vimeet_infrastructure.repository.participant_repository
    vimeet_infrastructure.vimeet.application.command.participant.update_handler:
        class: Proximum\Vimeet\Application\Command\Participant\UpdateHandler
        arguments:
            - @vimeet_infrastructure.repository.participant_repository
    vimeet_infrastructure.vimeet.application.command.participant.add_handler:
        class: Proximum\Vimeet\Application\Command\Participant\AddHandler
        arguments:
            - @vimeet_infrastructure.repository.user_repository
            - @vimeet_infrastructure.repository.participant_repository
    vimeet_infrastructure.vimeet.application.command.sheet.update_block_handler:
        class: Proximum\Vimeet\Application\Command\Sheet\UpdateBlockHandler
        arguments:
            - @vimeet_infrastructure.repository.sheet_repository
    vimeet_infrastructure.vimeet.application.command.participant.delete_handler:
        class: Proximum\Vimeet\Application\Command\Participant\DeleteHandler
        arguments:
            - @vimeet_infrastructure.repository.participant_repository
    vimeet_infrastructure.vimeet.application.command.package.update_step_handler:
        class: Proximum\Vimeet\Application\Command\Package\UpdateStepHandler
        arguments:
            - @vimeet_infrastructure.repository.sheet_repository
    vimeet_infrastructure.vimeet.application.command.update_handler:
        class: Proximum\Vimeet\Application\Command\Event\UpdateHandler
        arguments:
            - @vimeet_infrastructure.repository.event_repository

    #
    # Security
    #
    vimeet_infrastructure.security.user_password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ["@security.encoder_factory", getEncoder]
        arguments:
            - Proximum\Vimeet\Domain\Model\User
    vimeet_infrastructure.adapter.salt_generator:
        class: Proximum\Vimeet\Application\Adapter\SaltGenerator
    vimeet_infrastructure.adapter.encoder_adapter:
        class: Proximum\Vimeet\Bundle\InfrastructureBundle\Adapter\EncoderAdapter
        arguments:
            - @vimeet_infrastructure.security.user_password_encoder

