services:
  vimeet_infrastructure.repository.event_repository:
      class: Proximum\Vimeet\Bundle\InfrastructureBundle\Repository\EventRepository
      arguments:
          - @doctrine.orm.entity_manager
