Proximum\Vimeet\Application\Command\Event\Update:
    properties:
        title:
            - NotBlank: ~
        mode:
            - NotBlank: ~
        domain:
            - NotBlank: ~
            - Length:
                max: 63
            - Regex:
                pattern: !php/const Proximum\Vimeet\Domain\Model\Event::DOMAIN_VALIDATION_REGEX
        timeZone:
            - NotBlank: ~
        locales:
            - NotBlank: ~
        fallback:
            - NotBlank: ~
            - Expression:
                expression: "this.fallback in this.locales"
                message: "validators.fallbackInLocales"
        country:
            - NotBlank: ~
        vat:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        organiserName:
            - NotBlank: ~
        invoicePrefix:
            - NotBlank: ~
            - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Event\UpdateInvoicePrefixConstraint: ~
        translations:
            - All:
                - Collection:
                    fields:
                        description:
                            - NotBlank: ~
