Proximum\Vimeet\Application\Command\Event\Update:
    properties:
        title:
            - NotBlank: ~
        mode:
            - NotBlank: ~
        domain:
            - NotBlank: ~
            - Length:
                max: 63
            - Regex:
                pattern: '/^[a-z0-9-]+$/'
        timeZone:
            - NotBlank: ~
        locales:
            - NotBlank: ~
        fallback:
            - NotBlank: ~
            - Expression:
                expression: "this.fallback in this.locales"
                message: "validators.fallbackInLocales"
        country:
            - NotBlank: ~
        vat:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        logo:
            - Image:
                mimeTypes: !php/const:Proximum\Vimeet\Domain\Event\Image::SUPPORTED_MIME_TYPE
        textColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        leftColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        rightColor:
            - NotBlank: ~
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        organiserName:
            - NotBlank: ~
        invoicePrefix:
            - NotBlank: ~
            - Proximum\Vimeet\Infrastructure\Bundle\InfrastructureBundle\Validator\Constraint\Event\UpdateInvoicePrefixConstraint: ~
        translations:
            - All:
                - Collection:
                    fields:
                        description:
                            - NotBlank: ~
        backgroundColor:
            - Regex:
                pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
                message: validators.hexadecimal
        backgroundImage:
            - Image:
                mimeTypes: !php/const:Proximum\Vimeet\Domain\Event\Image::SUPPORTED_MIME_TYPE
