Proximum\Vimeet\Application\Command\Sheet\AddComment:
    constraints:
        - Expression:
            expression: "this.commercialStatusChangeOrCommentNotEmptyOrReminderDateNotEmpty()"
            message: "validators.sheet.commentCommercialStatus"
