Proximum\Vimeet\Application\Command\Happening\Speaker\Create:
    properties:
        name:
            - NotBlank: ~
        function:
            - NotBlank: ~
        organization:
            - NotBlank: ~
        logo:
            - Image: ~
        photo:
            - Image: ~
