Proximum\Vimeet\Application\Command\Transaction\Create:
    properties:
        sheet:
            - NotBlank: ~
        amount:
            - NotBlank: ~
            - Type: { type: float }
        date:
            - NotBlank: ~
            - DateTime: ~
        mode:
            - NotBlank: ~
        reference:
            - Type: { type: string }
