Proximum\Vimeet\Domain\Model\Admin:
    user_admin:
        __construct:
            - "goi@proximumgroup.com"
            - "D/TBAVl5oYyYU6/4F7gOT0mQkbBD8c5rBHga80zO"
            - "YzzBNEhw7I6H5xPuziQEAPAsg5g=" #vimeet_admin
            - 'fr'
            - "Layla"
            - "GOI"
            - 'ROLE_SUPER_ADMIN'
            - <dateTimeBetween('-10 days', 'now')>
        events: []
        lastLoginAt: <dateTime()>

    user_orga:
        __construct:
            - "larose@proximumgroup.com"
            - "hOcoU9/L7niTCDDLQOhqTzbrrEMO0/HWlbSQ6DNh"
            - "O9CLi6YZtHirpgd3fF/r2M2LMFs=" #vimeet_orga
            - 'fr'
            - "Vincent"
            - "LAROSE"
            - 'ROLE_ORGANIZER'
            - <dateTime()>
        events:
            - '@event_rdv_carnot_2016'
            - '@event_asddays_2016'
        lastLoginAt: <dateTime()>

    user_co:
        __construct:
            - "gagnard@proximumgroup.com"
            - "AkV6xDVrMTmD285rboI/Z9G31Id+WrvtoaLs/q3A"
            - "ENwYwD3WZei+Uv9Yl+DkbwlC6EY=" #vimeet_co
            - 'fr'
            - "Julien"
            - "GAGNARD"
            - 'ROLE_OPERATOR'
            - <dateTime()>
        events:
            - '@event_rdv_carnot_2016'
        lastLoginAt: <dateTime()>

    user_co_2:
        __construct:
            - "gagnard2@proximumgroup.com"
            - "AkV6xDVrMTmD285rboI/Z9G31Id+WrvtoaLs/q3A"
            - "ENwYwD3WZei+Uv9Yl+DkbwlC6EY=" #vimeet_co
            - 'fr'
            - "Julien 2"
            - "GAGNARD 2"
            - 'ROLE_OPERATOR'
            - <dateTime()>
        events:
            - '@event_rdv_carnot_2016'
            - '@event_asddays_2016'
        lastLoginAt: <dateTime()>
    user_co_3:
        __construct:
            - "gagnard3@proximumgroup.com"
            - "AkV6xDVrMTmD285rboI/Z9G31Id+WrvtoaLs/q3A"
            - "ENwYwD3WZei+Uv9Yl+DkbwlC6EY=" #vimeet_co
            - 'fr'
            - "Julien 3"
            - "GAGNARD 3"
            - 'ROLE_OPERATOR'
            - <dateTime()>
        events:
            - '@event_asddays_2016'
        lastLoginAt: <dateTime()>
    user_co_4:
        __construct:
            - "gagnard4@proximumgroup.com"
            - "AkV6xDVrMTmD285rboI/Z9G31Id+WrvtoaLs/q3A"
            - "ENwYwD3WZei+Uv9Yl+DkbwlC6EY=" #vimeet_co
            - 'fr'
            - "Julien 4"
            - "GAGNARD 4"
            - 'ROLE_OPERATOR'
            - <dateTime()>
        events:
            - '@event_asddays_2016'
        lastLoginAt: <dateTime()>
