Proximum\Vimeet\Domain\Model\Notification:
    asddays_must_select_package:
        __construct:
            - '@sheet_asddays_1'
            - 'packageSelected'
    asddays_sheet_translation_completeness:
        __construct:
            - '@sheet_asddays_1'
            - 'sheetTranslationCompleteness'
    asddays_pending_transaction:
        __construct:
            - '@sheet_asddays_1'
            - 'transactionPending'
