Proximum\Vimeet\Domain\Model\Type:
    event_asddays_2016_type_fournisseur:
        __construct: ["@event_asddays_2016"]
        position: 1
        package: '@package_asd_days'
        sheetTemplate: '@sheet_template_fournisseur_asddays'
        registrationTemplate: '@registration_template_asd_days'
        availabilityType: 'unavailable'
        displayAnalyticsOnCatalog: true

    event_asddays_2016_type_investisseur:
        __construct: ["@event_asddays_2016"]
        position: 2
        package: '@package_asd_days'
        sheetTemplate: '@sheet_template_investisseur_asddays'
        registrationTemplate: '@registration_template_asd_days'
        availabilityType: 'available'
        displayAnalyticsOnSheet: true

    event_asddays_2016_type_donneur_ordre:
        __construct: ["@event_asddays_2016"]
        position: 3
        package: '@package_asd_days'
        sheetTemplate: '@sheet_template_fournisseur_asddays'
        registrationTemplate: '@registration_template_asd_days'
        availabilityType: 'unavailable'

    event_asddays_2016_type_structure_de_recherche:
        __construct: ["@event_asddays_2016"]
        position: 4
        package: '@package_asd_days'
        sheetTemplate: '@sheet_template_fournisseur_asddays'
        registrationTemplate: '@registration_template_asd_days_in_one_step'
        availabilityType: 'unavailable'

    event_asddays_2016_type_delegation:
        __construct: ["@event_asddays_2016"]
        position: 5
        package: '@package_asd_days'
        sheetTemplate: '@sheet_template_fournisseur_asddays'
        registrationTemplate: '@registration_template_asd_days'
        availabilityType: 'unavailable'

Proximum\Vimeet\Domain\Model\TypeTranslation:
    event_asddays_2016_type_fournisseur_fr:
        __construct: ['@event_asddays_2016_type_fournisseur', fr, "Fournisseur"]
    event_asddays_2016_type_fournisseur_en:
        __construct: ['@event_asddays_2016_type_fournisseur', en, "Supplier"]
    event_asddays_2016_type_investisseur_fr:
        __construct: ['@event_asddays_2016_type_investisseur', fr, "Investisseur"]
    event_asddays_2016_type_investisseur_en:
        __construct: ['@event_asddays_2016_type_investisseur', en, "Investor"]
    event_asddays_2016_type_donneur_ordre_fr:
        __construct: ['@event_asddays_2016_type_donneur_ordre', fr, "Donneur d'ordre"]
    event_asddays_2016_type_donneur_ordre_en:
        __construct: ['@event_asddays_2016_type_donneur_ordre', en, "Contractor"]
    event_asddays_2016_type_structure_de_recherche_fr:
        __construct: ['@event_asddays_2016_type_structure_de_recherche', fr, "Structure de recherche"]
    event_asddays_2016_type_structure_de_recherche_en:
        __construct: ['@event_asddays_2016_type_structure_de_recherche', en, "Research entity"]
    event_asddays_2016_type_delegation_fr:
        __construct: ['@event_asddays_2016_type_delegation', fr, "Délégation"]
    event_asddays_2016_type_delegation_en:
        __construct: ['@event_asddays_2016_type_delegation', en, "Delegation / Cluster"]
