Proximum\Vimeet\Domain\Model\Event:
    event_asddays_2016:
        __construct:
            - "ASD Days"               #title
            -  fr                      #fallback
            - [fr, en]                 #locales
            - 'et'                     #mode
            - 20                       #vat
            - 'FR'                     #country
            -  'EUR'                   #currency
            - 'Europe/Paris'           #timeZone
            - asddays-2016.<domain()> #domain
            - "PROXIMUM"               #organiserName
        logo: 'assets/images/asddays-logo.png'
        assetPath: ''
        paymentAddress: '@payment_address_event_asddays_2016'
        configuration: '@configuration_asddays_2016'
        organiserEmail: "accounts@proximumgroup.com"
        bankInfo: |+
            HSBC Issy les Moulineaux
            IBAN: FR76 3005 6006 4306 4332 4153 439
            SWIFT (BIC): CCFRFRPP
        legalInformation: |+
            TVA acquittée sur les encaissements
            Pas d'escompte pour paiement anticipé
        # vat mode :
        # - 'ati' = All Taxes Include : prices include taxes, no additional taxes computed
        # - 'et'  = Exclusive of Taxes : prices don't includes taxes, taxes are computed from prices
        elementToJoinWithInvoice: |+
            - Numéro de la Facture
            - Nom de l'événement
            - Montant net à payer

Proximum\Vimeet\Domain\Model\Event\Configuration (local):
    configuration_asddays_2016:
        __construct:
            - '#59a4eb'
            - '#00398c'
            - '#00398C'

Proximum\Vimeet\Domain\Model\EventTranslation:
    event_asddays_2016_fr:
        __construct: false
        description: "ASD Days, le Rdv international dédié à l'Aéronautique, le Spatial, la Défense, la Sécurité et les Drones."
        locale: fr
        event: '@event_asddays_2016'
    event_asddays_2016_en:
        __construct: false
        description: "ASD Days, the international meeting dedicated to: Aerospace, Defence, Security & UAVs."
        locale: en
        event: '@event_asddays_2016'

Proximum\Vimeet\Domain\Model\Address (local):
    payment_address_event_asddays_2016:
        __construct:
            - 855 Avenue Roger Salengro
            - 92370
            - CHAVILLE
            - fr
