Proximum\Vimeet\Domain\Model\Catalog\Internal\SearchFacet:
    search_facet_category:
        __construct:
            - '@event_asddays_2016'
            - 'category'
            - false
    search_facet_type:
        __construct:
            - '@event_asddays_2016'
            - 'type'
            - true
    search_facet_position:
        __construct:
            - '@event_asddays_2016'
            - 'position'
            - true
    search_facet_organizationCategory:
        __construct:
            - '@event_asddays_2016'
            - 'organizationCategory'
            - true
    search_facet_keywords:
        __construct:
            - '@event_asddays_2016'
            - 'keywords'
            - true
    search_facet_localization:
        __construct:
            - '@event_asddays_2016'
            - 'localization'
            - true

Proximum\Vimeet\Domain\Model\Catalog\Internal\SearchFacetTranslation:
    search_facet_translation_type_fr:
        __construct:
            - '@search_facet_type'
            - 'Type'
            - ''
            - 'fr'
    search_facet_translation_type_en:
        __construct:
            - '@search_facet_type'
            - 'Type'
            - ''
            - 'en'
    search_facet_translation_position_fr:
        __construct:
            - '@search_facet_position'
            - 'Position'
            - ''
            - 'fr'
    search_facet_translation_position_en:
        __construct:
            - '@search_facet_position'
            - 'Position'
            - ''
            - 'en'
    search_facet_translation_category_fr:
        __construct:
            - '@search_facet_category'
            - 'Catégorie'
            - ''
            - 'fr'
    search_facet_translation_category_en:
        __construct:
            - '@search_facet_category'
            - 'Category'
            - ''
            - 'en'
    search_facet_translation_organization_category_fr:
        __construct:
            - '@search_facet_organizationCategory'
            - 'Structure'
            - 'PME, Startup ...'
            - 'fr'
    search_facet_translation_organization_category_en:
        __construct:
            - '@search_facet_organizationCategory'
            - 'Structure'
            - 'PME, Startup ...'
            - 'en'
    search_facet_translation_organization_keywords_fr:
        __construct:
            - '@search_facet_keywords'
            - 'Mots clés'
            - 'Société, Compétences ...'
            - 'fr'
    search_facet_translation_organization_keywords_en:
        __construct:
            - '@search_facet_keywords'
            - 'Keywords'
            - 'Company, Skills ...'
            - 'en'
    search_facet_translation_organization_localization_fr:
        __construct:
            - '@search_facet_localization'
            - 'Localisation'
            - '69, Paris, Lyon, France ...'
            - 'fr'
    search_facet_translation_organization_localization_en:
        __construct:
            - '@search_facet_localization'
            - 'Localization'
            - '69, Paris, Lyon, France ...'
            - 'en'
