Proximum\Vimeet\Domain\Model\Address (local):
    sheet_asddays_empty_address:
        __construct: false
        street: <address()>
        zipcode: <postcode()>
        city: <city()>
        country: FR
    sheet_asddays_1_address:
        __construct: false
        street: <address()>
        zipcode: <postcode()>
        city: <city()>
        country: FR

Proximum\Vimeet\Domain\Model\BillingInfo:
    sheet_asddays_empty_billing_info:
        __construct: false
        sheet: '@sheet_asddays_empty'
        gender: man
        firstname: <firstName()>
        lastname: <lastName()>
        function: Directeur
        phone: <phoneNumber()>
        mobile: <mobileNumber()>
        email: <safeEmail()>
        company: <company()>
        address: '@sheet_asddays_empty_address'
    sheet_asddays_1_billing_info:
        __construct: false
        sheet: '@sheet_asddays_1'
        gender: man
        firstname: <firstName()>
        lastname: <lastName()>
        function: Directeur
        phone: <phoneNumber()>
        mobile: <mobileNumber()>
        email: <safeEmail()>
        company: <company()>
        address: '@sheet_asddays_1_address'

Proximum\Vimeet\Domain\Model\Order:
    order_1:
        __construct:
            - '@sheet_asddays_empty'
            - '{"4":{"translations":{"fr":{"label":"Options d\u2019exposition"},"en":{"label":"Exhibiting options"}},"rank":1},"5":{"translations":{"fr":{"label":"Options d\u2019exposition et de communication"},"en":{"label":"Exhibiting and communication options"}},"rank":2},"6":{"translations":{"fr":{"label":"Options de communication"},"en":{"label":"Communication options"}},"rank":3}}'
            - <dateTimeBetween('-10days', 'now')>
    order_2:
        __construct:
            - '@sheet_asddays_1'
            - '{"4":{"translations":{"fr":{"label":"Options d\u2019exposition"},"en":{"label":"Exhibiting options"}},"rank":1},"5":{"translations":{"fr":{"label":"Options d\u2019exposition et de communication"},"en":{"label":"Exhibiting and communication options"}},"rank":2},"6":{"translations":{"fr":{"label":"Options de communication"},"en":{"label":"Communication options"}},"rank":3}}'
            - <dateTimeBetween('-10days', 'now')>
    order_3:
        __construct:
            - '@sheet_asddays_1'
            - '{"4":{"translations":{"fr":{"label":"Options d\u2019exposition"},"en":{"label":"Exhibiting options"}},"rank":1},"5":{"translations":{"fr":{"label":"Options d\u2019exposition et de communication"},"en":{"label":"Exhibiting and communication options"}},"rank":2},"6":{"translations":{"fr":{"label":"Options de communication"},"en":{"label":"Communication options"}},"rank":3}}'
            - <dateTimeBetween('-5days', 'now')>

Proximum\Vimeet\Domain\Model\Order\Row:
    order_1_row_1:
        __construct: false
        order: '@order_1'
        quantity: 1
        price: 1690
        vatRate: 20
        data: '{"id":10,"type":"plan","translations":{"fr":{"title":"Formule B2B Meeting","heading":"Pas de stand","description":"Vous changez de lieu \u00e0 chaque rendez-vous.","addon":""},"en":{"title":"B2B Meeting Formula","heading":"No booth","description":"You have to move at each appointment.","addon":""}},"productsIncluded":[{"quantity":2,"included":{"id":12,"type":"participant","translations":{"fr":{"title":"Participant suppl\u00e9mentaire","heading":"","description":"Accompagnant le premier sur un m\u00eame agenda incluant une entr\u00e9e \u00e0 la convention d\u2019affaire, acc\u00e8s illimit\u00e9 \u00e0 la pause caf\u00e9 et aux conf\u00e9rences.","addon":""},"en":{"title":"Extra participant","heading":"","description":"Accompanying the first one on the same agenda including an entry to selected business conventions and unlimited access to coffee breaks and conferences.","addon":""}},"productsIncluded":[]}}]}'
        product: '@product_plan_1_asddays'
    order_1_row_2:
        __construct: false
        order: '@order_1'
        quantity: 1
        groupId: 4
        price: 199
        vatRate: 20
        data: '{"id":1,"type":"option","translations":{"fr":{"title":"Option E","heading":"","description":"","addon":""},"en":{"title":"Option E","heading":"","description":"","addon":""}},"productsIncluded":[]}'
        product: '@product_option_7_asddays'
    order_1_row_3:
        __construct: false
        order: '@order_1'
        quantity: 3
        price: 59
        vatRate: 20
        data: '{"name":"Option F", "translations":{"fr":"{"title":"Option F","heading":"","description":"","addon":""}","en":"{"title":"Option F","heading":"","description":"","addon":""}"}}'
        product: '@product_option_8_asddays'
    order_2_row_1:
        __construct: false
        order: '@order_2'
        quantity: 1
        price: 1690
        vatRate: 20
        data: '{"id":10,"type":"plan","translations":{"fr":{"title":"Formule B2B Meeting","heading":"Pas de stand","description":"Vous changez de lieu \u00e0 chaque rendez-vous.","addon":""},"en":{"title":"B2B Meeting Formula","heading":"No booth","description":"You have to move at each appointment.","addon":""}},"productsIncluded":[{"quantity":2,"included":{"id":12,"type":"participant","translations":{"fr":{"title":"Participant suppl\u00e9mentaire","heading":"","description":"Accompagnant le premier sur un m\u00eame agenda incluant une entr\u00e9e \u00e0 la convention d\u2019affaire, acc\u00e8s illimit\u00e9 \u00e0 la pause caf\u00e9 et aux conf\u00e9rences.","addon":""},"en":{"title":"Extra participant","heading":"","description":"Accompanying the first one on the same agenda including an entry to selected business conventions and unlimited access to coffee breaks and conferences.","addon":""}},"productsIncluded":[]}}]}'
        product: '@product_plan_1_asddays'
    order_2_row_2:
        __construct: false
        order: '@order_2'
        quantity: 1
        groupId: 4
        price: 199
        vatRate: 20
        data: '{"id":20,"type":"option","translations":{"fr":{"title":"Option E","heading":"","description":"Description option E","addon":""},"en":{"title":"Option E","heading":"","description":"Description Option E","addon":""}},"productsIncluded":[]}'
        product: '@product_option_7_asddays'
    order_2_row_3:
        __construct: false
        order: '@order_2'
        quantity: 1
        price: 59
        groupId: 5
        vatRate: 20
        data: '{"id":21,"type":"option","translations":{"fr":{"title":"Option F","heading":"","description":"Description option F","addon":""},"en":{"title":"Option F","heading":"","description":"Description Option F","addon":""}},"productsIncluded":[]}'
        product: '@product_option_8_asddays'
    order_2_row_4:
        __construct: false
        order: '@order_2'
        quantity: 1
        price: 195
        vatRate: 20
        data: '{"id":12,"type":"participant","translations":{"fr":{"title":"Participant suppl\u00e9mentaire","heading":"","description":"Accompagnant le premier sur un m\u00eame agenda incluant une entr\u00e9e \u00e0 la convention d\u2019affaire, acc\u00e8s illimit\u00e9 \u00e0 la pause caf\u00e9 et aux conf\u00e9rences.","addon":""},"en":{"title":"Extra participant","heading":"","description":"Accompanying the first one on the same agenda including an entry to selected business conventions and unlimited access to coffee breaks and conferences.","addon":""}},"productsIncluded":[]}'
        product: '@product_participant_1_asddays'
    order_3_row_1:
        __construct: false
        order: '@order_3'
        quantity: 3
        groupId: 4
        price: 199
        vatRate: 20
        data: '{"id":20,"type":"option","translations":{"fr":{"title":"Option E","heading":"","description":"Description option E","addon":""},"en":{"title":"Option E","heading":"","description":"Description Option E","addon":""}},"productsIncluded":[]}'
        product: '@product_option_7_asddays'
    order_3_row_2:
        __construct: false
        order: '@order_3'
        quantity: 9
        groupId: 5
        price: 59
        vatRate: 20
        data: '{"id":21,"type":"option","translations":{"fr":{"title":"Option F","heading":"","description":"Description option F","addon":""},"en":{"title":"Option F","heading":"","description":"Description Option F","addon":""}},"productsIncluded":[]}'
        product: '@product_option_8_asddays'
    order_3_row_3:
        __construct: false
        order: '@order_3'
        quantity: 3
        price: 195
        vatRate: 20
        data: '{"id":12,"type":"participant","translations":{"fr":{"title":"Participant suppl\u00e9mentaire","heading":"","description":"Accompagnant le premier sur un m\u00eame agenda incluant une entr\u00e9e \u00e0 la convention d\u2019affaire, acc\u00e8s illimit\u00e9 \u00e0 la pause caf\u00e9 et aux conf\u00e9rences.","addon":""},"en":{"title":"Extra participant","heading":"","description":"Accompanying the first one on the same agenda including an entry to selected business conventions and unlimited access to coffee breaks and conferences.","addon":""}},"productsIncluded":[]}'
        product: '@product_participant_1_asddays'
    order_3_row_4:
        __construct: false
        order: '@order_3'
        quantity: 1
        price: 495
        vatRate: 20
        data: '{"id":13,"type":"planning","translations":{"fr":{"title":"Planning supplémentaire","heading":"","description":"En fonction du nombre de rendez-vous bi validuées","addon":""},"en":{"title":"Extra planning","heading":"","description":"According to the number of bi-validated meetings","addon":""}},"productsIncluded":[]}'
        product: '@product_planning_1_asddays'

Proximum\Vimeet\Domain\Model\Order\PromotionCode:
    order_promotion_code_row_1:
        __construct: false
        order: '@order_2'
        promotionCode: '@promotion_code_asddays_2016'
        data: '{"id":1,"translations":{"fr":{"label":"Assdays code promotionnel","description":"Assdays description code promotionnel"},"en":{"label":"Assdays promotion code","description":"Assdays promotion code description"}}}'
        price: -250
        vatRate: 20
