
Proximum\Vimeet\Domain\Model\Nomenclature:
    nomenclature_asddays_competences:
        __construct: false
        title: "Compétences"
        depth: 3
        value:
            ad987cae:
                label: { fr: "Compétences Aéronautiques", en: "Aeronautical skills" }
                children:
                    ecc44d0d:
                        label: { fr: "Ingénierie & Bureau d'études", en: "Engineering and Engineering consulting firm" }
                        children:
                            c93def9a: { label: { fr: "Modélisation et calculs", en: "Modelling and calculations" } }
                            34eab90c: { label: { fr: "Expérimentation & réalisation de prototypes", en: "Experiment and realization of prototypes" } }
                    32ef03cc:
                        label: { fr: "Informatique", en: "Computing" }
                        children:
                            cab0332d: { label: { fr: "Modélisation & simulation", en: "Modelling and simulation" } }
                    2ec033da:
                        label: { fr: "Instrumentation Appareils de mesures scientifiques in-situ", en: "Instrumentation in situ scientific Measuring devices" }
                        children:
                            aaa34eb9: { label: { fr: "Appareils de mesures scientifiques in-situ", en: "In situ scientific measuring devices" } }
                            bdec99a0: { label: { fr: "Prototypage", en: "Prototypage" } }
                            b35ae9c7: { label: { fr: "Technologie laser", en: "Laser technology" } }
            dea09e034:
                label: { fr: "Compétences Défenses", en: "Defence skills" }
                children:
                    acc44d0d:
                        label: { fr: "Ingénierie & Bureau d'études", en: "Engineering and Engineering consulting firm" }
                        children:
                            993def9a: { label: { fr: "Modélisation et calculs", en: "Modelling and calculations" } }
                            e4eab90c: { label: { fr: "Expérimentation & réalisation de prototypes", en: "Experiment and realization of prototypes" } }
                    42ef03cc:
                        label: { fr: "Informatique", en: "Computing" }
                        children:
                            dab0332d: { label: { fr: "Modélisation & simulation", en: "Modelling and simulation" } }
                    5ec033da:
                        label: { fr: "Instrumentation Appareils de mesures scientifiques in-situ", en: "Instrumentation in situ scientific Measuring devices" }
                        children:
                            faa34eb9: { label: { fr: "Appareils de mesures scientifiques in-situ", en: "In situ scientific measuring devices" } }
                            adec99a0: { label: { fr: "Prototypage", en: "Prototypage" } }
                            a35ae9c7: { label: { fr: "Technologie laser", en: "Laser technology" } }
    nomenclature_asddays_offre_besoins:
        __construct: false
        title: "Offre et besoins"
        depth: 1
        value:
            ab93de01:
                label: { fr: "Ingénierie & Bureau d'études", en: "Engineering and Engineering consulting firm" }
            ab93de02:
                label: { fr: "Modélisation et calculs", en: "Modelling and calculations" }
            ab93de03:
                label: { fr: "Expérimentation & réalisation de prototypes", en: "Experiment and realization of prototypes" }
            ab93de04:
                label: { fr: "Informatique", en: "Computing" }
            ab93de05:
                label: { fr: "Modélisation & simulation", en: "Modelling and simulation" }
            ab93de06:
                label: { fr: "Instrumentation Appareils de mesures scientifiques in-situ", en: "Instrumentation in situ scientific Measuring devices" }
            ab93de07:
                label: { fr: "Prototypage", en: "Prototypage" }
