Proximum\Vimeet\Domain\Model\Participant:
    # Elao participant
    participant_test:
        __construct: false
        user: '@user_test'
        sheet: '@sheet_test'
        owner: true
        active: true
        data:
            838197c7: "Dupond"
            541f84d4: "Jean"

    # Proximum participants
    proximum_participant_visiteur:
        __construct: false
        user: '@proximum_user_visiteur'
        sheet: '@proximum_sheet_visiteur'
        owner: true
        active: true
        data:
            838197c7: MARTIN
            541f84d4: Jean
    proximum_participant_exposant:
        __construct: false
        user: '@proximum_user_exposant'
        sheet: '@proximum_sheet_exposant'
        owner: true
        active: true
        data:
            838197c7: BOUCHON
            541f84d4: François
    proximum_participant_carnot:
        __construct: false
        user: '@proximum_user_carnot'
        sheet: '@proximum_sheet_carnot'
        owner: true
        active: true
        data:
            838197c7: MIGNOT
            541f84d4: Isabelle
    proximum_participant_admin:
        __construct: false
        user: '@proximum_user_admin'
        sheet: '@proximum_sheet_admin'
        owner: true
        active: true
        data:
            838197c7: GOI
            541f84d4: Layla
    proximum_participant_test:
        __construct: false
        user: '@proximum_user_test'
        sheet: '@proximum_sheet_test'
        owner: true
        active: true
        data:
            838197c7: LAROSE
            541f84d4: Vincent
    proximum_participant_ui:
        __construct: false
        user: '@proximum_user_ui'
        sheet: '@proximum_sheet_ui'
        owner: true
        active: true
        data:
            838197c7: GAGNARD
            541f84d4: Julien

    # Random
    participant_random_1:
        __construct: false
        user: '@user_random_1'
        sheet: '@sheet_exposant2'
        owner: false
        active: true
        data:
            838197c7: <firstName()>
            541f84d4: <lastName()>
    participant_random_2:
        __construct: false
        user: '@user_random_1'
        sheet: '@sheet_exposant2'
        owner: false
        active: true
        data:
            838197c7: <firstName()>
            541f84d4: <lastName()>
    participant_random_3:
        __construct: false
        user: '@user_random_1'
        sheet: '@sheet_exposant4'
        owner: false
        active: true
        data:
            838197c7: <firstName()>
            541f84d4: <lastName()>
    participant_random_4:
        __construct: false
        user: '@user_random_1'
        sheet: '@sheet_exposant5'
        owner: false
        active: true
        data:
            838197c7: <firstName()>
            541f84d4: <lastName()>
    participant_random_1{10..30}:
        __construct: false
        user: '@user_random_1'
        sheet: '@sheet_exposant*'
        owner: false
        active: true
        data:
            838197c7: <firstName()>
            541f84d4: <lastName()>
