Proximum\Vimeet\Domain\Model\User\Account (local):
    rdv_carnot_group_user_manager_account:
        __construct: false
        firstName: <firstName()>
        lastName: <lastName()>
        phone: <e164PhoneNumber()>
        mobile: <e164PhoneNumber()>
    rdv_carnot_group_sheet_1_owner_account:
        __construct: false
        firstName: <firstNameFemale()>
        lastName: <lastName()>
        phone: <e164PhoneNumber()>
        mobile: <e164PhoneNumber()>
    rdv_carnot_group_sheet_2_owner_account:
        __construct: false
        firstName: <firstNameMale()>
        lastName: <lastName()>
        phone: <e164PhoneNumber()>
        mobile: <e164PhoneNumber()>

Proximum\Vimeet\Domain\Model\User:
    rdv_carnot_group_user_manager:
        __construct: false
        email: "multifiche@proximum.com"
        salt: "600f1943340f930f8dd8a22c6f8876ae71415ed5"
        password: "+Ht6FUfCoS8Q063evTVxDS0yerY=" # password
        locale: "fr"
        account: '@rdv_carnot_group_user_manager_account'
    rdv_carnot_group_sheet_1_owner_user:
        __construct: false
        email: "multifiche-fiche1@proximum.com"
        salt: "600f1943340f930f8dd8a22c6f8876ae71415ed5"
        password: "+Ht6FUfCoS8Q063evTVxDS0yerY=" # password
        locale: "fr"
        account: '@rdv_carnot_group_sheet_1_owner_account'
    rdv_carnot_group_sheet_2_owner_user:
        __construct: false
        email: "multifiche-fiche2@proximum.com"
        salt: "600f1943340f930f8dd8a22c6f8876ae71415ed5"
        password: "+Ht6FUfCoS8Q063evTVxDS0yerY=" # password
        locale: "fr"
        account: '@rdv_carnot_group_sheet_2_owner_account'

Proximum\Vimeet\Domain\Model\Sheet\Group:
    rdv_carnot_group:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@rdv_carnot_group_user_manager'
            - 'Entité Institut Carnot'
            - false
            - <dateTime()>

Proximum\Vimeet\Domain\Model\Sheet:
    rdv_carnot_group_sheet_1:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_exposant'
            -
                # Titre de la fiche
                dcc42d3d: { text: { fr: "Institut Carnot Fiche 1" } }
                # Lien
                90713a3d: { url: "<url()>" }
                # Description d'activité
                d691d21c: { text: { fr: "<sentence()>" } }
            - '@rdv_carnot_group_sheet_1_owner_user'
            - <dateTime()>
            - '@rdv_carnot_group'
        registrationData:
            3ad4b72f: { text: 'Institut Carnot Fiche 1' }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        lastLoginAt: <dateTime()>
        inCatalog: true

    rdv_carnot_group_sheet_2:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_institute_carnot'
            -
                # Titre de la fiche
                dcc42d3d: { text: { fr: "Institut Carnot Fiche 2" } }
                # Lien
                90713a3d: { url: "<url()>" }
                # Description d'activité
                d691d21c: { text: { fr: "<sentence()>" } }
            - '@rdv_carnot_group_sheet_2_owner_user'
            - <dateTime()>
            - '@rdv_carnot_group'
        registrationData:
            3ad4b72f: { text: 'Institut Carnot Fiche 2' }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        lastLoginAt: <dateTime()>
        inCatalog: true

    rdv_carnot_group_sheet_3:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_institute_carnot'
            -
                # Titre de la fiche
                dcc42d3d: { text: { fr: "Institut Carnot Fiche 3" } }
                # Lien
                90713a3d: { url: "<url()>" }
                # Description d'activité
                d691d21c: { text: { fr: "<sentence()>" } }
            - '@rdv_carnot_group_user_manager' # case Sheet owner is a Group manager
            - <dateTime()>
            - '@rdv_carnot_group'
        registrationData:
            3ad4b72f: { text: 'Institut Carnot Fiche 3' }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        lastLoginAt: <dateTime()>
        inCatalog: true

Proximum\Vimeet\Domain\Model\Participant:
    rdv_carnot_group_sheet_1_participant_1:
        __construct: false
        user: '@rdv_carnot_group_sheet_1_owner_user'
        sheet: '@rdv_carnot_group_sheet_1'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstNameFemale()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: <e164PhoneNumber()> }
            4b674gba: { gender: "woman" }
            3b759fbb: { telephone: <e164PhoneNumber()> }
            6c4a3a4f: { items: ["position1"] }
    rdv_carnot_group_sheet_2_participant_1:
        __construct: false
        user: '@rdv_carnot_group_sheet_2_owner_user' # this user participate to rdv_carnot_group_sheet_2 and rdv_carnot_group_sheet_3
        sheet: '@rdv_carnot_group_sheet_2'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstNameMale()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: <e164PhoneNumber()> }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: <e164PhoneNumber()> }
            6c4a3a4f: { items: ["position2"] }
    rdv_carnot_group_sheet_3_participant_1:
        __construct: false
        user: '@rdv_carnot_group_user_manager' # case a participant is a Group manager
        sheet: '@rdv_carnot_group_sheet_3'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstNameMale()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: <e164PhoneNumber()> }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: <e164PhoneNumber()> }
            6c4a3a4f: { items: ["position2"] }
    rdv_carnot_group_sheet_3_participant_2:
        __construct: false
        user: '@rdv_carnot_group_sheet_2_owner_user' # this user participate to rdv_carnot_group_sheet_2 and rdv_carnot_group_sheet_3
        sheet: '@rdv_carnot_group_sheet_3'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstNameMale()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: <e164PhoneNumber()> }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: <e164PhoneNumber()> }
            6c4a3a4f: { items: ["position2"] }
