Proximum\Vimeet\Domain\Model\Sheet:
    # Elao sheet
    sheet_test:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_exposant'
            -
                # Titre de la fiche
                dcc42d3d:
                    text:
                        fr: "<catchPhrase()>"
                # Lien
                90713a3d:
                    url: "<url()>"
                # Description d'activité
                d691d21c:
                    text:
                        fr: "<sentence()>"
            - '@user_test'
            - <dateTime()>
        title: 'WorldCompanyInc'
        registrationData:
            3ad4b72f: { text: 'WorldCompanyInc' }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        owner: '@user_test'
        lastLoginAt: <dateTime()>
        inCatalog: true

    # Proximum sheets
    proximum_sheet_visiteur:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur'
            -
                # Titre de la fiche
                dcc42d3d:
                    text:
                        fr: "<catchPhrase()>"
                # Lien
                90713a3d:
                    url: "<url()>"
                # Description d'activité
                d691d21c:
                    text:
                        fr: "<sentence()>"
            - '@proximum_user_visiteur'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        lastLoginAt: <dateTime()>
    proximum_sheet_exposant:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_institute_carnot'
            -
                # Titre de la fiche
                dcc42d3d:
                    text:
                        fr: "<catchPhrase()>"
                # Lien
                90713a3d:
                    url: "<url()>"
                # Description d'activité
                d691d21c:
                    text:
                        fr: "<sentence()>"
            - '@proximum_user_exposant'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        owner: '@proximum_user_exposant'
        lastLoginAt: <dateTime()>
    proximum_sheet_carnot:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_institute_carnot'
            - []
            - '@proximum_user_carnot'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        owner: '@proximum_user_carnot'
        lastLoginAt: <dateTime()>
    proximum_sheet_admin:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_investisseur'
            - []
            - '@proximum_user_admin'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        owner: '@proximum_user_admin'
        lastLoginAt: <dateTime()>
    proximum_sheet_test:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_exposant'
            - []
            - '@proximum_user_test'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        lastLoginAt: <dateTime()>
    proximum_sheet_ui:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur'
            - []
            - '@proximum_user_ui'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        owner: '@proximum_user_ui'
        lastLoginAt: <dateTime()>

    # Random
    sheet_exposant1:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_exposant'
            -
                # Titre de la fiche
                dcc42d3d:
                    text:
                        fr: "<catchPhrase()>"
                # Lien
                90713a3d:
                    url: "<url()>"
                # Description d'activité
                d691d21c:
                    text:
                        fr: "<sentence()>"
            - '@user_random_1'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_exposant2:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_exposant'
            - []
            - '@user_random_2'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_exposant3:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_investisseur'
            - []
            - '@user_random_3'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_exposant4:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_exposant'
            - []
            - '@user_random_4'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_exposant5:
        __construct:
             - '@event_rdv_carnot_2016'
             - '@type_exposant'
             - []
             - '@user_random_5'
             - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_exposant6:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur'
            - []
            - '@user_random_6'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_exposant7:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_investisseur'
            - []
            - '@user_random_13'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_investisseur1:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_investisseur'
            - []
            - '@user_random_7'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_investisseur2:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_investisseur'
            - []
            - '@user_random_8'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_visiteur1:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur'
            - []
            - '@user_random_9'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_visiteur2:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur'
            - []
            - '@user_random_10'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_visiteur_visio1:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur_visio'
            - []
            - '@user_random_11'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    sheet_visiteur_visio2:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur_visio'
            - []
            - '@user_random_12'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
        lastLoginAt: <dateTime()>

    # Sheet with invoice
    sheet_with_invoice:
        __construct:
            - '@event_rdv_carnot_2016'
            - '@type_visiteur'
            -
                # Titre de la fiche
                dcc42d3d:
                    text:
                        fr: "<catchPhrase()>"
                # Lien
                90713a3d:
                    url: "<url()>"
                # Description d'activité
                d691d21c:
                    text:
                        fr: "<sentence()>"
            - '@proximum_user_visiteur'
            - <dateTime()>
        registrationData:
            3ad4b72f: { text: <company()> }
            93de093f: { text: "<address()>" }
            de66af5d: { text: "<postCode()>" }
            d224f0e7: { text: "<city()>" }
            e801edd4: { country: "FR" }
            57da9df7ced30: { boolean: true }
            57da8f210fbf2: { text: "<sentence()>" }
        lastLoginAt: <dateTime()>
