Proximum\Vimeet\Domain\Model\Sheet:
    # Elao sheet
    sheet_test:
        __construct: false
        type: '@type_exposant'
        event: '@event_rdv_carnot_2016'
        data: []
        registrationData:
            3ad4b72f: { text: 'WorldCompanyInc' }
        owner: '@user_test'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>

    # Proximum sheets
    proximum_sheet_visiteur:
        __construct: false
        type: '@type_visiteur'
        event: '@event_rdv_carnot_2016'
        data: []
        owner: '@proximum_user_visiteur'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    proximum_sheet_exposant:
        __construct: false
        type: '@type_exposant'
        event: '@event_rdv_carnot_2016'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@proximum_user_exposant'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    proximum_sheet_carnot:
        __construct: false
        type: '@type_institute_carnot'
        event: '@event_rdv_carnot_2016'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@proximum_user_carnot'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    proximum_sheet_admin:
        __construct: false
        type: '@type_exposant'
        event: '@event_rdv_carnot_2016'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@proximum_user_admin'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    proximum_sheet_test:
        __construct: false
        type: '@type_exposant'
        event: '@event_rdv_carnot_2016'
        data: []
        owner: '@proximum_user_test'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    proximum_sheet_ui:
        __construct: false
        type: '@type_visiteur'
        event: '@event_rdv_carnot_2016'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@proximum_user_ui'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>

    # Random
    sheet_exposant1:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_1'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_exposant2:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_2'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_exposant3:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_3'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_exposant4:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_4'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_exposant5:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_5'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_exposant6:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_6'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_exposant7:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_exposant'
        data: []
        owner: '@user_random_13'
        registrationData:
            3ad4b72f: { text: <company()> }
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>

    sheet_investisseur1:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_investisseur'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@user_random_7'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_investisseur2:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_investisseur'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@user_random_8'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>

    sheet_visiteur1:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_visiteur'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@user_random_9'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_visiteur2:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_visiteur'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@user_random_10'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>

    sheet_visiteur_visio1:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_visiteur_visio'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@user_random_11'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
    sheet_visiteur_visio2:
        __construct: false
        event: '@event_rdv_carnot_2016'
        type: '@type_visiteur_visio'
        data: []
        registrationData:
            3ad4b72f: { text: <company()> }
        owner: '@user_random_12'
        createdAt: <dateTime()>
        lastLoginAt: <dateTime()>
