Proximum\Vimeet\Domain\Model\User\Event\ExtraData:
    # Elao participant
    elao_participant_tes_visio:
        __construct: false
        name: 'is_participant_visio'
        value: 'true'
        user: '@user_test'
        event: '@event_rdv_carnot_2016'
        createdAt: "<date('2016-10-18 16:00:00', 'Europe/Paris', 'UTC')>"
        updatedAt: "<date('2016-10-18 16:00:00', 'Europe/Paris', 'UTC')>"

Proximum\Vimeet\Domain\Model\Participant:
    # Elao participant
    participant_test:
        __construct: false
        user: '@user_test'
        sheet: '@sheet_test'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: 'Paul' }
            838197c7: { text: 'GASCOIGNE' }
            1efb9cbb: { telephone: "+33909090909" }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: "+33069090909" }
            6c4a3a4f: { items: ["position34"] }

    # Proximum participants
    proximum_participant_visiteur:
        __construct: false
        user: '@proximum_user_visiteur'
        sheet: '@proximum_sheet_visiteur'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: "+33909090909" }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: "+33069090909" }
            6c4a3a4f: { items: ["position34"] }
    proximum_participant_exposant:
        __construct: false
        user: '@proximum_user_exposant'
        sheet: '@proximum_sheet_exposant'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: "+33909090909" }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: "+33069090909" }
            6c4a3a4f: { items: ["position36"] }
    proximum_participant_carnot:
        __construct: false
        user: '@proximum_user_carnot'
        sheet: '@proximum_sheet_carnot'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: "+33909090909" }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: "+33069090909" }
            6c4a3a4f: { items: ["position37"] }
    proximum_participant_carnot2:
        __construct: false
        user: '@proximum_user_carnot2'
        sheet: '@proximum_sheet_carnot'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: "+33909090909" }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: "+33069090909" }
            6c4a3a4f: { items: ["position38"] }
    proximum_participant_admin:
        __construct: false
        user: '@proximum_user_admin'
        sheet: '@proximum_sheet_admin'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            1efb9cbb: { telephone: "+33909090909" }
            4b674gba: { gender: "man" }
            3b759fbb: { telephone: "+33069090909" }
            6c4a3a4f: { items: ["position39"] }
    proximum_participant_test:
        __construct: false
        user: '@proximum_user_test'
        sheet: '@proximum_sheet_test'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position25"] }
    proximum_participant_ui:
        __construct: false
        user: '@proximum_user_ui'
        sheet: '@proximum_sheet_ui'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position26"] }

    # Random
    participant_random_1:
        __construct: false
        user: '@user_random_1'
        sheet: '@sheet_exposant1'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position27"] }
    participant_random_2:
        __construct: false
        user: '@user_random_2'
        sheet: '@sheet_exposant2'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_3:
        __construct: false
        user: '@user_random_3'
        sheet: '@sheet_exposant3'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_4:
        __construct: false
        user: '@user_random_4'
        sheet: '@sheet_exposant4'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_5:
        __construct: false
        user: '@user_random_5'
        sheet: '@sheet_exposant5'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_6:
        __construct: false
        user: '@user_random_6'
        sheet: '@sheet_exposant6'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_13:
        __construct: false
        user: '@user_random_13'
        sheet: '@sheet_exposant7'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }

    participant_random_7:
        __construct: false
        user: '@user_random_7'
        sheet: '@sheet_investisseur1'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_8:
        __construct: false
        user: '@user_random_8'
        sheet: '@sheet_investisseur2'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_9:
        __construct: false
        user: '@user_random_9'
        sheet: '@sheet_visiteur1'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_10:
        __construct: false
        user: '@user_random_10'
        sheet: '@sheet_visiteur2'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_11:
        __construct: false
        user: '@user_random_11'
        sheet: '@sheet_visiteur_visio1'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
    participant_random_12:
        __construct: false
        user: '@user_random_12'
        sheet: '@sheet_visiteur_visio2'
        active: true
        registrationDate: <dateTime()>
        data:
            541f84d4: { text: <firstName()> }
            838197c7: { text: <lastName()> }
            6c4a3a4f: { items: ["position28"] }
