Proximum\Vimeet\Domain\Model\Spot:
    spot_1:
        __construct:
            - G0345
            - "@event_rdv_carnot_2016"
            - 6
            - 3
            - 4
            - true
    spot_2:
        __construct:
            - A008
            - "@event_rdv_carnot_2016"
            - 6
            - 3
            - 4
            - true
    spot_3:
        __construct:
            - B090
            - "@event_rdv_carnot_2016"
            - 6
            - 5
            - 4
            - true
    spot_4:
        __construct:
            - A100
            - "@event_rdv_carnot_2016"
            - 6
            - 3
            - 4
            - true
    spot_5:
        __construct:
            - F098
            - "@event_rdv_carnot_2016"
            - 6
            - 5
            - 4
            - false
