Proximum\Vimeet\Domain\Model\Event\Day:
    event_rdv_carnot_2016_day_1:
        __construct: false
        event: '@event_rdv_carnot_2016'
        startTime: <(new DateTime('18-10-2016 08:00:00.000'))>
        endTime: <(new DateTime('18-10-2016 18:00:00.000'))>
    event_rdv_carnot_2016__day_2:
        __construct: false
        event: '@event_rdv_carnot_2016'
        startTime: <(new DateTime('19-10-2016 08:00:00.000'))>
        endTime: <(new DateTime('19-10-2016 18:00:00.000'))>

Proximum\Vimeet\Domain\Model\Address (local):
    event_rdv_carnot_2016_payment_address_event:
        __construct:
            - 855 Avenue Roger Salengro
            - 92370
            - CHAVILLE
            - fr

Proximum\Vimeet\Domain\Model\Event\Configuration (local):
    event_rdv_carnot_2016_configuration:
        __construct:
            - '#4697ff'
            - '#4b41d0'
            - '#00398C'
        contactFirstName: "Maryse"
        contactLastName: "DURAND"
        catalogOnlineDate: <dateTimeBetween('-20days', 'now')>
        happeningsOpenDate: <dateTimeBetween('-15days', 'now')>
        schedulePublishDate: <dateTimeBetween('-10days', 'now')>
        backgroundColor: '#00398C'

Proximum\Vimeet\Domain\Model\Invoice\Prefix:
    prefix_rdv_carnot:
        __construct:
            - 'RdvCarnot'
            - 'Rdv'
            - false

Proximum\Vimeet\Domain\Model\Event:
    event_rdv_carnot_2016:
        __construct:
            - "Les rendez-vous CARNOT 2016" #title
            -  fr                           #fallback
            - [fr, en]                      #locales
            - 'et'                          #mode
            - 20                            #vat
            - 'FR'                          #country
            -  'EUR'                        #currency
            - 'Europe/Paris'                #timeZone
            - rdv-carnot-2016.<domain()>    #domain
            - "PROXIMUM"                    #organiserName
            - 'team-project@example.net'    #emailTeam
            - '@prefix_rdv_carnot'
        assetPath: ''
        configuration: '@event_rdv_carnot_2016_configuration'
        paymentAddress: '@event_rdv_carnot_2016_payment_address_event'
        organiserEmail: accounts@proximumgroup.com


Proximum\Vimeet\Domain\Model\EventTranslation:
    event_translation_rdv_carnot_2016_fr:
        __construct: false
        description: LES RENDEZ-VOUS DE LA R&D POUR LES ENTREPRISES
        locale: fr
        event: '@event_rdv_carnot_2016'
        bankInfo: |+
            HSBC Issy les Moulineaux
            IBAN: FR76 3005 6006 4306 4332 4153 439
            SWIFT (BIC): CCFRFRPP
    event_translation_rdv_carnot_2016_en:
        __construct: false
        description: In 7 editions, les Rendez-vous CARNOT became the major R&D event for innovation.
        locale: en
        event: '@event_rdv_carnot_2016'
        bankInfo: |+
            HSBC Issy les Moulineaux
            IBAN: FR76 3005 6006 4306 4332 4153 439
            SWIFT (BIC): CCFRFRPP

Proximum\Vimeet\Domain\Model\Event\Content:
    content_terms_of_sale_rdv_carnot:
        __construct: false
        type: 'terms-of-sale'
        event: '@event_rdv_carnot_2016'

Proximum\Vimeet\Domain\Model\Event\ContentTranslation:
    content_terms_of_sale_rdv_carnot_fr:
        __construct: false
        content: '@content_terms_of_sale_rdv_carnot'
        locale: 'fr'
        value: |+
            Conditions générales de vente pour RDV Carnot
    content_terms_of_sale_rdv_carnot_en:
        __construct: false
        content: '@content_terms_of_sale_rdv_carnot'
        locale: 'en'
        value: |+
            Our General Terms and Conditions of Sale shall exclusively apply to all
            contracts between us and our clients. Any differing conditions or terms of
            buyer are herewith objected to and shall not apply. Any agreement affecting
            the execution of this contract must be in writing.
