Proximum\Vimeet\Domain\Model\Invoice\Prefix:
    prefix_spanish:
        __construct:
            - 'Spanish'
            - 'Spa'
            - false

Proximum\Vimeet\Domain\Model\Event:
    event_spanish:
        __construct:
            - "Evento en español"        #title
            -  es                        #fallback
            - [es]                       #locales
            - 'et'                       #mode
            - 20                         #vat
            - 'ES'                       #country
            -  'EUR'                     #currency
            - 'Europe/Paris'             #timeZone
            - spanish-event.<domain()>   #domain
            - "PROXIMUM"                 #organiserName
            - 'team-project@example.net' #emailTeam
            - '@prefix_spanish'
        locales: [es]
        assetPath: ''
        paymentAddress: '@payment_address_event_spanish'
        configuration: '@configuration_event_spanish'
        organiserEmail: accounts@proximumgroup.com


Proximum\Vimeet\Domain\Model\EventTranslation:
    event_spanish_es:
        __construct: false
        description: "Descripción de mi evento en español"
        locale: es
        event: '@event_spanish'
        bankInfo: |+
            HSBC Issy les Moulineaux
            IBAN: FR76 3005 6006 4306 4332 4153 439
            SWIFT (BIC): CCFRFRPP

Proximum\Vimeet\Domain\Model\Event\Configuration:
    configuration_event_spanish:
        __construct:
            - '#59a4eb'
            - '#00398c'
            - '#00398C'
        contactFirstName: "Maryse"
        contactLastName: "DURAND"
        backgroundColor: '#00398C'

Proximum\Vimeet\Domain\Model\Address:
    payment_address_event_spanish:
        __construct:
            - 855 Avenue Roger Salengro
            - 92370
            - CHAVILLE
            - fr

Proximum\Vimeet\Domain\Model\Product:
    # plans
    product_plan_1_spanish_event:
        __construct: { createPlan: ['@event_spanish', 'Formule B2B Meeting', 0, 1690, 20, 0, 0] }
        quantityMax: 1
        updatable: false
        deletableUntil: ~
    product_plan_2_spanish_event:
        __construct: { createPlan: [ '@event_spanish', 'Formule Exposant', 0, 2880, 20, 0, 0 ] }
        quantityMax: 1
        updatable: false
        deletableUntil: ~
    # participants
    product_participant_1_spanish_event:
        __construct: { createParticipant: [ '@event_spanish', 'Participant supplémentaire Fournisseur', 195, 20, 10 ] }
        image: ~
        availabilityCurrent: 0
        availabilityMax: 0
        updatable: false
        deletableUntil: ~
    # plannings
    product_planning_1_spanish_event:
        __construct: { createPlanning: [ '@event_spanish', 'Planning supplémentaire Fournisseur', 495, 20, 10 ] }
        availabilityCurrent: 0
        availabilityMax: 0
        updatable: false
        deletableUntil: ~
    # options
    product_option_1_spanish_event:
        __construct: { createOption: ['@event_spanish', 'Option 4m² supplémentaires Fournisseur', 0, 990, 20, 1, 0, 0, true, null] }
    product_option_2_spanish_event:
        __construct: { createOption: ['@event_spanish', 'Option chaise', 0, 9, 20, 10, 0, 0, true, null] }
    product_option_3_spanish_event:
        __construct: { createOption: ['@event_spanish', 'Option A', 0, 9, 20, 10, 0, 0, true, null] }
    product_option_4_spanish_event:
        __construct: { createOption: ['@event_spanish', 'Option B', 0, 9, 20, 10, 0, 0, true, null] }
    product_option_5_spanish_event:
        __construct: { createOption: ['@event_spanish', 'Option C', 0, 9, 20, 10, 0, 0, true, null] }

Proximum\Vimeet\Domain\Model\ProductTranslation:
    product_plan_1_spanish_event_fr:
        __construct: false
        product: '@product_plan_1_spanish_event'
        title: 'Formule B2B Meeting'
        heading: 'Pas de stand'
        description: 'Vous changez de lieu à chaque rendez-vous.'
        addon: ''
        locale: 'fr'
    product_plan_1_spanish_event_es:
        __construct: false
        product: '@product_plan_1_spanish_event'
        title: 'B2B Meeting Formula'
        heading: 'No booth'
        description: 'You have to move at each appointment.'
        addon: ''
        locale: 'es'
    product_plan_2_spanish_event_fr:
        __construct: false
        product: '@product_plan_2_spanish_event'
        title: 'Formule Exposant'
        heading: 'Stand équipé 4m² (2x2m)'
        description: 'Avec enseigne, drapeau, lampe, 1 table et 4 chaises.'
        addon: ''
        locale: 'fr'
    product_plan_2_spanish_event_es:
        __construct: false
        product: '@product_plan_2_spanish_event'
        title: 'Exhibitor Formula'
        heading: 'An equipped 4 sqm booth (2X2 m)'
        description: 'With a banner, lighting, 1 table and 4 chairs.'
        addon: ''
        locale: 'es'
    product_participant_1_spanish_event_fr:
        __construct: false
        product: '@product_participant_1_spanish_event'
        title: 'Participant supplémentaire'
        heading: ''
        description: 'Accompagnant le premier sur un même agenda incluant une entrée à la convention d’affaire, accès illimité à la pause café et aux conférences.'
        addon: ''
        locale: 'fr'
    product_participant_1_spanish_event_es:
        __construct: false
        product: '@product_participant_1_spanish_event'
        title: 'Extra participant'
        heading: ''
        description: 'Accompanying the first one on the same agenda including an entry to selected business conventions and unlimited access to coffee breaks and conferences.'
        addon: ''
        locale: 'es'
    product_planning_1_spanish_event_fr:
        __construct: false
        product: '@product_planning_1_spanish_event'
        title: 'Planning supplémentaire'
        heading: ''
        description: 'En fonction du nombre de rendez-vous bi validés'
        addon: ''
        locale: 'fr'
    product_planning_1_spanish_event_es:
        __construct: false
        product: '@product_planning_1_spanish_event'
        title: 'Extra planning'
        heading: ''
        description: 'According to the number of bi-validated meetings'
        addon: ''
        locale: 'es'
    product_option_1_spanish_event_fr:
        __construct: false
        product: '@product_option_1_spanish_event'
        title: 'Option 4m² supplémentaires'
        heading: ''
        description: 'Option valable uniquement en complément des formules Exposant et Parrain.'
        addon: ''
        locale: 'fr'
    product_option_1_spanish_event_es:
        __construct: false
        product: '@product_option_1_spanish_event'
        title: 'Add booth option (4 sqm)'
        heading: ''
        description: 'Option available in addition with exhibitor and sponsor formula only.'
        addon: ''
        locale: 'es'
    product_option_2_spanish_event_fr:
        __construct: false
        product: '@product_option_2_spanish_event'
        title: 'Chaise'
        heading: ''
        description: ''
        addon: ''
        locale: 'fr'
    product_option_2_spanish_event_es:
        __construct: false
        product: '@product_option_2_spanish_event'
        title: 'Chair'
        heading: ''
        description: ''
        addon: ''
        locale: 'es'

Proximum\Vimeet\Domain\Model\Product\Feature:
    feature_1_spanish_event:
        __construct: false
        product: '@product_plan_1_spanish_event'
    feature_2_spanish_event:
        __construct: false
        product: '@product_plan_1_spanish_event'
    feature_3_spanish_event:
        __construct: false
        product: '@product_plan_1_spanish_event'
    feature_4_spanish_event:
        __construct: false
        product: '@product_plan_2_spanish_event'
    feature_5_spanish_event:
        __construct: false
        product: '@product_plan_2_spanish_event'
    feature_6_spanish_event:
        __construct: false
        product: '@product_plan_2_spanish_event'
    feature_7_spanish_event:
        __construct: false
        product: '@product_plan_2_spanish_event'
    feature_8_spanish_event:
        __construct: false
        product: '@product_plan_2_spanish_event'

Proximum\Vimeet\Domain\Model\Product\FeatureTranslation:
    feature_translation_1_fr_spanish_event:
        __construct: false
        feature: '@feature_1_spanish_event'
        locale: 'fr'
        title: 'Presta 1'
        description: 'Description Presta 1'
    feature_translation_1_es_spanish_event:
        __construct: false
        feature: '@feature_1_spanish_event'
        locale: 'es'
        title: 'Presta 1'
        description: 'Description Presta 1'
    feature_translation_2_fr_spanish_event:
        __construct: false
        feature: '@feature_2_spanish_event'
        locale: 'fr'
        title: 'Presta 2'
        description: 'Description Presta 2'
    feature_translation_2_es_spanish_event:
        __construct: false
        feature: '@feature_2_spanish_event'
        locale: 'es'
        title: 'Presta 2'
        description: 'Description Presta 2'
    feature_translation_3_fr_spanish_event:
        __construct: false
        feature: '@feature_3_spanish_event'
        locale: 'fr'
        title: 'Presta 3'
        description: 'Description Presta 3'
    feature_translation_3_es_spanish_event:
        __construct: false
        feature: '@feature_3_spanish_event'
        locale: 'es'
        title: 'Presta 3'
        description: 'Description Presta 3'
    feature_translation_4_fr_spanish_event:
        __construct: false
        feature: '@feature_4_spanish_event'
        locale: 'fr'
        title: 'Presta 4'
        description: 'Description Presta 4'
    feature_translation_4_es_spanish_event:
        __construct: false
        feature: '@feature_4_spanish_event'
        locale: 'es'
        title: 'Presta 4'
        description: 'Description Presta 4'
    feature_translation_5_fr_spanish_event:
        __construct: false
        feature: '@feature_5_spanish_event'
        locale: 'fr'
        title: 'Presta 5'
        description: 'Description Presta 5'
    feature_translation_5_es_spanish_event:
        __construct: false
        feature: '@feature_5_spanish_event'
        locale: 'es'
        title: 'Presta 5'
        description: 'Description Presta 5'
    feature_translation_6_fr_spanish_event:
        __construct: false
        feature: '@feature_6_spanish_event'
        locale: 'fr'
        title: 'Presta 6'
        description: 'Description Presta 6'
    feature_translation_6_es_spanish_event:
        __construct: false
        feature: '@feature_6_spanish_event'
        locale: 'es'
        title: 'Presta 6'
        description: 'Description Presta 6'
    feature_translation_7_fr_spanish_event:
        __construct: false
        feature: '@feature_7_spanish_event'
        locale: 'fr'
        title: 'Presta 7'
        description: 'Description Presta 7'
    feature_translation_7_es_spanish_event:
        __construct: false
        feature: '@feature_7_spanish_event'
        locale: 'es'
        title: 'Presta 7'
        description: 'Description Presta 7'
    feature_translation_8_fr_spanish_event:
        __construct: false
        feature: '@feature_8_spanish_event'
        locale: 'fr'
        title: 'Presta 8'
        description: 'Description Presta 8'
    feature_translation_8_es_spanish_event:
        __construct: false
        feature: '@feature_8_spanish_event'
        locale: 'es'
        title: 'Presta 8'
        description: 'Description Presta 8'

Proximum\Vimeet\Domain\Model\Package:
    package_spanish_event:
        __construct: false
        event: '@event_spanish'
        title: "Package Spanish Event"
        createdAt: "<dateTimeBetween('-10days', 'now')>"
        planning: '@product_planning_1_spanish_event'
        plansEnabled: true
        participantAndPlanningEnabled: true
        optionsEnabled: true

Proximum\Vimeet\Domain\Model\PackageTranslation:
    package_spanish_event_fr:
        __construct: false
        package: '@package_spanish_event'
        locale: 'fr'
        plansLabel: 'Formules'
        participantAndPlanningLabel: 'Participants & plannings'
        optionsLabel: 'Options'
    package_spanish_event_es:
        __construct: false
        package: '@package_spanish_event'
        locale: 'es'
        plansLabel: 'Plan'
        participantAndPlanningLabel: 'Participants & plannings'
        optionsLabel: 'Options'

Proximum\Vimeet\Domain\Model\PackagePlanRank:
    package_plan_1_rank_spanish_event:
        __construct: false
        rank: 1
        package: '@package_spanish_event'
        plan: '@product_plan_1_spanish_event'
    package_plan_2_rank_spanish_event:
        __construct: false
        rank: 2
        package: '@package_spanish_event'
        plan: '@product_plan_2_spanish_event'

Proximum\Vimeet\Domain\Model\PackageParticipantRank:
    package_participant_1_rank_spanish_event:
        __construct: false
        rank: 1
        package: '@package_spanish_event'
        productParticipant: '@product_participant_1_spanish_event'

Proximum\Vimeet\Domain\Model\PackageGroup:
    package_group_1_spanish_event:
        __construct: false
        rank: 1
        package: '@package_spanish_event'
    package_group_2_spanish_event:
        __construct: false
        rank: 2
        package: '@package_spanish_event'
    package_group_3_spanish_event:
        __construct: false
        rank: 3
        package: '@package_spanish_event'

Proximum\Vimeet\Domain\Model\PackageGroupTranslation:
    package_group_1_spanish_event_fr:
        __construct: false
        locale: 'fr'
        label: 'Options d’exposition'
        group: '@package_group_1_spanish_event'
    package_group_1_spanish_event_es:
        __construct: false
        locale: 'es'
        label: 'Exhibiting options'
        group: '@package_group_1_spanish_event'
    package_group_2_spanish_event_fr:
        __construct: false
        locale: 'fr'
        label: "Options d'exposition et de communication"
        group: '@package_group_2_spanish_event'
    package_group_2_spanish_event_es:
        __construct: false
        locale: 'es'
        label: 'Exhibiting and communication options'
        group: '@package_group_2_spanish_event'
    package_group_3_spanish_event_fr:
        __construct: false
        locale: 'fr'
        label: 'Options de communication'
        group: '@package_group_3_spanish_event'
    package_group_3_spanish_event_es:
        __construct: false
        locale: 'es'
        label: 'Communication options'
        group: '@package_group_3_spanish_event'

Proximum\Vimeet\Domain\Model\PackageOptionRank:
    package_group_1_option_1_spanish_event:
        __construct: false
        rank: 1
        group: '@package_group_1_spanish_event'
        option: '@product_option_1_spanish_event'
    package_group_1_option_2_spanish_event:
        __construct: false
        rank: 1
        group: '@package_group_1_spanish_event'
        option: '@product_option_2_spanish_event'
    package_group_2_option_3_spanish_event:
        __construct: false
        rank: 1
        group: '@package_group_2_spanish_event'
        option: '@product_option_3_spanish_event'
    package_group_3_option_4_spanish_event:
        __construct: false
        rank: 1
        group: '@package_group_3_spanish_event'
        option: '@product_option_4_spanish_event'
    package_group_3_option_5_spanish_event:
        __construct: false
        rank: 1
        group: '@package_group_3_spanish_event'
        option: '@product_option_5_spanish_event'

Proximum\Vimeet\Domain\Model\Event\Content:
    content_terms_of_sale_spanish_event:
        __construct: false
        type: 'terms-of-sale'
        event: '@event_spanish'

Proximum\Vimeet\Domain\Model\Event\ContentTranslation:
    content_terms_of_sale_spanish_event_es:
        __construct: false
        content: '@content_terms_of_sale_spanish_event'
        locale: 'es'
        value: |+
            Conditions générales de vente pour événement espagnol
    content_terms_of_sale_spanish_event_en:
        __construct: false
        content: '@content_terms_of_sale_spanish_event'
        locale: 'en'
        value: |+
            Our General Terms and Conditions of Sale shall exclusively apply to all
            contracts between us and our clients. Any differing conditions or terms of
            buyer are herewith objected to and shall not apply. Any agreement affecting
            the execution of this contract must be in writing.
