
Proximum\Vimeet\Domain\Model\Nomenclature:
    nomenclature_competences_spanish:
        __construct: false
        event: '@event_spanish'
        original: '@nomenclature_competences'
        title: "Compétences"
        depth: 3
        value:
            ad987cae:
                label: { fr: "Aéronautiques", en: "Aeronautical" }
                children:
                    ecc44d0d:
                        label: { fr: "Ingénierie & Bureau d'études", en: "Engineering and Engineering consulting firm" }
                        children:
                            c93def9a: { label: { fr: "Modélisation et calculs", en: "Modelling and calculations" } }
                            34eab90c: { label: { fr: "Expérimentation & réalisation de prototypes", en: "Experiment and realization of prototypes" } }
                    32ef03cc:
                        label: { fr: "Informatique", en: "Computing" }
                        children:
                            cab0332d: { label: { fr: "Modélisation & simulation", en: "Modelling and simulation" } }
                    2ec033da:
                        label: { fr: "Instrumentation Appareils de mesures scientifiques in-situ", en: "Instrumentation in situ scientific Measuring devices" }
                        children:
                            aaa34eb9: { label: { fr: "Appareils de mesures scientifiques in-situ", en: "In situ scientific measuring devices" } }
                            bdec99a0: { label: { fr: "Prototypage", en: "Prototypage" } }
                            b35ae9c7: { label: { fr: "Technologie laser", en: "Laser technology" } }
            dea09e034:
                label: { fr: "Défenses", en: "Defence" }
                children:
                    acc44d0d:
                        label: { fr: "Ingénierie & Bureau d'études", en: "Engineering and Engineering consulting firm" }
                        children:
                            993def9a: { label: { fr: "Modélisation et calculs", en: "Modelling and calculations" } }
                            e4eab90c: { label: { fr: "Expérimentation & réalisation de prototypes", en: "Experiment and realization of prototypes" } }
                    42ef03cc:
                        label: { fr: "Informatique", en: "Computing" }
                        children:
                            dab0332d: { label: { fr: "Modélisation & simulation", en: "Modelling and simulation" } }
                    5ec033da:
                        label: { fr: "Instrumentation Appareils de mesures scientifiques in-situ", en: "Instrumentation in situ scientific Measuring devices" }
                        children:
                            faa34eb9: { label: { fr: "Appareils de mesures scientifiques in-situ", en: "In situ scientific measuring devices" } }
                            adec99a0: { label: { fr: "Prototypage", en: "Prototypage" } }
                            a35ae9c7: { label: { fr: "Technologie laser", en: "Laser technology" } }
    nomenclature_offre_besoins_spanish:
        __construct: false
        event: '@event_spanish'
        original: '@nomenclature_offre_besoins'
        title: "Offre et besoins"
        depth: 1
        value:
            ab93de01:
                label: { fr: "Ingénierie & Bureau d'études", en: "Engineering and Engineering consulting firm" }
            ab93de02:
                label: { fr: "Modélisation et calculs", en: "Modelling and calculations" }
            ab93de03:
                label: { fr: "Expérimentation & réalisation de prototypes", en: "Experiment and realization of prototypes" }
            ab93de04:
                label: { fr: "Informatique", en: "Computing" }
            ab93de05:
                label: { fr: "Modélisation & simulation", en: "Modelling and simulation" }
            ab93de06:
                label: { fr: "Instrumentation Appareils de mesures scientifiques in-situ", en: "Instrumentation in situ scientific Measuring devices" }
            ab93de07:
                label: { fr: "Prototypage", en: "Prototypage" }
    nomenclature_position_spanish:
        __construct: false
        event: '@event_spanish'
        original: '@nomenclature_position'
        title: "Fonction"
        depth: 2
        value:
            domainPositionCommerciale:
                label: { fr: "Commerciale/Vente", en: "Commercial / Sales", es: "" }
                children:
                    position1: { label: { fr: "Assistant commercial", en: "Sales Assistant", es: "" } }
                    position2: { label: { fr: "Assistant export", en: "Export Assistant", es: "" } }
                    position3: { label: { fr: "Chef de publicité", en: "Head of Advertising", es: "" } }
                    position4: { label: { fr: "Directeur commercial", en: "Commercial Director", es: "" } }
                    position5: { label: { fr: "Directeur de publicité", en: "Advertising Executive", es: "" } }
                    position6: { label: { fr: "Directeur des ventes", en: "Sales Director", es: "" } }
                    position7: { label: { fr: "Directeur des ventes export", en: "Director Export Sales", es: "" } }
                    position8: { label: { fr: "Directeur du développement", en: "Development Director", es: "" } }
                    position9: { label: { fr: "Ingénieur commercial ou d'affaires", en: "Business Engineer", es: "" } }
                    position10: { label: { fr: "Ingénieur technico-commercial", en: "Technical Sales Engineer", es: "" } }
                    position11: { label: { fr: "Responsable Commercial", en: "Sales Manager", es: "" } }
                    position12: { label: { fr: "Responsable comptes clés", en: "Key Account Manager", es: "" } }
                    position13: { label: { fr: "Responsable des ventes", en: "Sales Manager", es: "" } }
                    position14: { label: { fr: "Responsable du développement", en: "Development Manager", es: "" } }
                    position15: { label: { fr: "Responsable export", en: "Export Manager", es: "" } }
                    position16: { label: { fr: "Responsable régional des ventes", en: "Regional Sales Manager", es: "" } }
                    position17: { label: { fr: "Responsable Technico-commercial", en: "Technical Sales Manager", es: "" } }
            domainPositionCommunication:
                label: { fr: "Communication", en: "Communication", es: "" }
                children:
                    position18: { label: { fr: "Chargé de communication", en: "Communication Manager", es: "" } }
                    position19: { label: { fr: "Directeur de la communication", en: "Communication Director", es: "" } }
                    position20: { label: { fr: "Responsable communication", en: "Communication Manager", es: "" } }
            domainPositionDirection:
                label: { fr: "Direction", en: "Direction", es: "" }
                children:
                    position20: { label: { fr: "Co-Fondateur", en: "Co-Founder", es: "" } }
                    position21: { label: { fr: "Directeur Associé", en: "Associate Director", es: "" } }
                    position22: { label: { fr: "Directeur de Division", en: "Division Director", es: "" } }
                    position23: { label: { fr: "Directeur de la Stratégie", en: "CSO / Chief Strategy Officer", es: "" } }
                    position24: { label: { fr: "Directeur des ressources humaines", en: "Human Resources Director", es: "" } }
                    position25: { label: { fr: "Directeur général", en: "General Manager", es: "" } }
                    position26: { label: { fr: "Directeur Général Adjoint", en: "Deputy General Director", es: "" } }
                    position27: { label: { fr: "Fondateur", en: "Founder", es: "" } }
                    position28: { label: { fr: "Président", en: "President", es: "" } }
                    position29: { label: { fr: "Président-directeur général / Chef d'entreprise", en: "CEO / Chief Executive Officer", es: "" } }
                    position30: { label: { fr: "Secrétaire Général", en: "General Secretary", es: "" } }
            domainPositionInformatique:
                label: { fr: "Informatique", en: "IT", es: "" }
                children:
                    position31: { label: { fr: "Administrateur de base de données", en: "Database Administrator", es: "" } }
                    position32: { label: { fr: "Analyste fonctionnel", en: "Functional Analyst", es: "" } }
                    position33: { label: { fr: "Chef de projet informatique", en: "IT Project Manager", es: "" } }
                    position34: { label: { fr: "Développeur", en: "Developer", es: "" } }
                    position35: { label: { fr: "DSI / Directeur Informatique", en: "IST Manager", es: "" } }
                    position36: { label: { fr: "Gestionnaire de parc informatique", en: "IT Asset Manager", es: "" } }
                    position37: { label: { fr: "Ingénieur de développement informatique", en: "IT Development Engineer", es: "" } }
                    position38: { label: { fr: "Ingénieur d'études", en: "Studies Engineer", es: "" } }
                    position39: { label: { fr: "Ingénieur réseau", en: "Network Engineer", es: "" } }
                    position40: { label: { fr: "Ingénieur système", en: "System Engineer", es: "" } }
                    position41: { label: { fr: "Responsable d'application", en: "Application Manager", es: "" } }
                    position42: { label: { fr: "Responsable des systèmes d'information", en: "Head of Information Systems", es: "" } }
                    position43: { label: { fr: "Responsable d'exploitation / Responsable de production", en: "Operations Manager", es: "" } }
                    position44: { label: { fr: "Responsable Support Client", en: "Cusomer Support Manager", es: "" } }
            domainPositionMarketing:
                label: { fr: "Marketing", en: "Marketing", es: "" }
                children:
                    position45: { label: { fr: "Assistant chef de produits", en: "Assistant Product Manager", es: "" } }
                    position46: { label: { fr: "Assistant marketing", en: "Marketing Assistant", es: "" } }
                    position47: { label: { fr: "Brand Manager", en: "Brand Manager", es: "" } }
                    position48: { label: { fr: "CDO / Responsable de la Direction du Numérique	CDO / Chief Digital Officer", es: "" } }
                    position49: { label: { fr: "Chef de produits", en: "Product Manager", es: "" } }
                    position50: { label: { fr: "Community Manager", en: "Community Manager", es: "" } }
                    position51: { label: { fr: "Directeur marketing", en: "Marketing Director", es: "" } }
                    position52: { label: { fr: "Responsable E-commerce", en: "E-Commerce Manager", es: "" } }
                    position53: { label: { fr: "Directeur de la création", en: "Creative Director", es: "" } }
                    position54: { label: { fr: "Responsable marketing", en: "Marketing Manager", es: "" } }
            domainPositionRecherche:
                label: { fr: "Recherche/Etudes et Laboratoire", en: "Research / Studies and Laboratory", es: "" }
                children:
                    position55: { label: { fr: "Chef de projet R&D", en: "Head of R&D Project", es: "" } }
                    position56: { label: { fr: "Chercheur", en: "Searcher", es: "" } }
                    position57: { label: { fr: "Directeur de Laboratoire", en: "Laboratory Director", es: "" } }
                    position58: { label: { fr: "Directeur Open Innovation", en: "Open Innovation Director", es: "" } }
                    position59: { label: { fr: "Directeur R&D", en: "R&D Director", es: "" } }
                    position60: { label: { fr: "Directeur de Projet", en: "Project Director", es: "" } }
                    position61: { label: { fr: "Ingénieur chef de projet", en: "Senior Project Engineer", es: "" } }
                    position62: { label: { fr: "Ingénieur R&D", en: "R&D Engineer", es: "" } }
                    position63: { label: { fr: "Responsable bureau d'études", en: "Engineering Manager", es: "" } }
                    position64: { label: { fr: "Responsable de laboratoire", en: "Laboratory Manager", es: "" } }
                    position65: { label: { fr: "Responsable Open Innovation", en: "Open Innovation Manager", es: "" } }
                    position66: { label: { fr: "Responsable R&D", en: "R&D Manager", es: "" } }
            domainPositionTechnique:
                label: { fr: "Techniques - Qualité - Environnement", en: "Technical - Quality - Environment", es: "" }
                children:
                    position67: { label: { fr: "Directeur de production", en: "Production Director", es: "" } }
                    position68: { label: { fr: "Directeur environnement", en: "Environment Director", es: "" } }
                    position69: { label: { fr: "Directeur industriel", en: "Industrial Director", es: "" } }
                    position70: { label: { fr: "Directeur technique", en: "Technical Director", es: "" } }
                    position71: { label: { fr: "Ingénieur maintenance", en: "Maintenance Engineer", es: "" } }
                    position72: { label: { fr: "Ingénieur méthode", en: "Method Engineer", es: "" } }
                    position73: { label: { fr: "Ingénieur qualité", en: "Quality Engineer", es: "" } }
                    position74: { label: { fr: "Ingénieur sécurité", en: "Security Engineer", es: "" } }
                    position75: { label: { fr: "Responsable de Production", en: "Production Manager", es: "" } }
                    position76: { label: { fr: "Responsable d'exploitation", en: "Operations Manager", es: "" } }
                    position77: { label: { fr: "Responsable qualité", en: "Quality Manager", es: "" } }
                    position78: { label: { fr: "Responsable sécurité", en: "Security Manager", es: "" } }
                    position79: { label: { fr: "Responsable technique", en: "Technical Manager", es: "" } }
                    position80: { label: { fr: "Responsable technique maintenance", en: "Maintenance Manager", es: "" } }
            domainPositionAchat:
                label: { fr: "Achats", en: "Purchasing Department", es: "" }
                children:
                    position81: { label: { fr: "Acheteur", en: "Purchaser", es: "" } }
                    position82: { label: { fr: "Directeur des Achats", en: "Purchasing Director", es: "" } }
                    position83: { label: { fr: "Responsable achats", en: "Purchasing Manager", es: "" } }
                    position84: { label: { fr: "Responsable sourcing", en: "Sourcing Manager", es: "" } }
            domainPositionLogistique:
                label: { fr: "Logistique ", en: "Logistic Department", es: "" }
                children:
                    position85: { label: { fr: "Affréteur", en: "Charterer", es: "" } }
                    position86: { label: { fr: "Agent en transport", en: "Transport Agent", es: "" } }
                    position87: { label: { fr: "Directeur de la supply chain", en: "Supply Chain Director", es: "" } }
                    position88: { label: { fr: "Directeur des Opérations", en: "Operations Director", es: "" } }
                    position89: { label: { fr: "Directeur des Transports", en: "Transport Director", es: "" } }
                    position90: { label: { fr: "Directeur Logistique", en: "Logistic Director", es: "" } }
                    position91: { label: { fr: "Responsable des approvisionnements", en: "Procurement Manager", es: "" } }
                    position92: { label: { fr: "Responsable logistique", en: "Logistic Manager", es: "" } }
                    position93: { label: { fr: "Responsable transport", en: "Transport Manager", es: "" } }
            domainPositionAutres:
                label: { fr: "Autres", en: "Others", es: "" }
                children:
                    position94: { label: { fr: "Avocat", en: "Lawyer", es: "" } }
                    position95: { label: { fr: "Chargé de mission", en: "Project Manager", es: "" } }
                    position96: { label: { fr: "Chargé d'études", en: "Research Officer", es: "" } }
                    position97: { label: { fr: "Conférencier", en: "Speaker", es: "" } }
                    position98: { label: { fr: "Consultant", en: "Consultant", es: "" } }
                    position99: { label: { fr: "Elu", en: "Elected", es: "" } }
                    position100: { label: { fr: "Enseignant", en: "Teacher", es: "" } }
                    position101: { label: { fr: "Responsable des Ressources Humaines", en: "Human Ressources Manager", es: "" } }
                    position102: { label: { fr: "Journaliste", en: "Journalist", es: "" } }
                    position103: { label: { fr: "Juriste", en: "Jurist", es: "" } }
                    position104: { label: { fr: "Rédacteur en chef", en: "Editor in Chief", es: "" } }
                    position105: { label: { fr: "Rédacteur en chef Adjoint", en: "Deputy Chief Editor", es: "" } }
                    position106: { label: { fr: "Responsable des Partenariats", en: "Partnerships Manager", es: "" } }
    nomenclature_service_spanish:
        __construct: false
        event: '@event_spanish'
        original: '@nomenclature_service'
        title: "Service"
        depth: 1
        value:
            serviceCommerciale: { label: { fr: "Commerciale/Vente", en: "Commerciale/Vente" }}
            serviceCommunication: { label: { fr: "Communication", en: "Communication" }}
            serviceDirection: { label: { fr: "Direction", en: "Direction" }}
            serviceInformatique: { label: { fr: "Informatique", en: "Informatique" }}
            serviceMarketing: { label: { fr: "Marketing", en: "Marketing" }}
            serviceRecherche: { label: { fr: "Recherche/Etudes et Laboratoire", en: "Recherche/Etudes et Laboratoire" }}
    nomenclature_activite_spanish:
        __construct: false
        event: '@event_spanish'
        original: '@nomenclature_activite'
        title: "Activité"
        depth: 1
        value:
            activite1: { label: { fr: "AGRICULTURE, SYLVICULTURE ET PÊCHE", en: "AGRICULTURE, SYLVICULTURE ET PÊCHE" }}
            activite2: { label: { fr: "COMMERCE", en: "COMMERCE" }}
            activite3: { label: { fr: "INFORMATION ET COMMUNICATION", en: "INFORMATION ET COMMUNICATION" }}
    nomenclature_company_category_spanish:
        __construct: false
        event: '@event_spanish'
        original: '@nomenclature_company_category'
        title: "Catégorie"
        depth: 1
        value:
            category1: { label: { fr: "PME", es: "PME",en: "SMEs" }}
            category2: { label: { fr: "Start-up", es: "Start-up",en: "Start-up" }}
            category3: { label: { fr: "Grand groupe", es: "Grand groupe",en: "Large group" }}
            category4: { label: { fr: "Organisme public", es: "Organisme public", en: "Publique organization" }}
            category5: { label: { fr: "ETI", es: "ETI", en: "Midcaps Companies" }}
            category6: { label: { fr: "Institutionnelle", es: "Institutionnelle", en: "Institutional" }}
            category7: { label: { fr: "Structure de recherche", es: "Structure de recherche", en: "Research structure" }}
            category8: { label: { fr: "Association", es: "Association", en: "Association" }}
            category9: { label: { fr: "Pôle de compétitivité / Cluster", es: "Pôle de compétitivité / Cluster", en: "Cluster" }}
            category10: { label: { fr: "Expert", es: "Expert", en: "Expert"}}
            category11: { label: { fr: "Investisseur", es: "Investisseur", en: "Investor"}}
