Proximum\Vimeet\Domain\Model\Template\RegistrationTemplate:
    registration_template_event_spanish:
        __construct: false
        event: '@event_spanish'
        title: "Inscription Template Espagnol"
        locales: ['es']
        fallback: 'es'
        createdAt: <dateTimeBetween('-10days', 'now')>
        value:
            811f6edf:
                component: "block"
                type: "12"
                config:
                    style: "style-1"
                children:
                    -
                        dded0597:
                            component: "object"
                            type: "text"
                            config:
                                style: "style-1"
                                content:
                                  es: "Perfil"
                                type: "title"
                        541f84d4:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Primer nombre"
                                placeholder:
                                    es: "Primer nombre"
                                help:
                                    es: ""
                                length: "250"
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["participant_firstname", "participant_data"]
                        838197c7:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Nombre"
                                placeholder:
                                    es: "Nombre"
                                help:
                                    es: ""
                                length: "250"
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["participant_lastname", "participant_data"]
                        6c4a3a4f:
                            component: "object"
                            type: "nomenclature"
                            config:
                                style: "style-1"
                                label:
                                    es: "Función"
                                help:
                                    es: ""
                                nomenclature: "@nomenclature_position_spanish->id"
                                mode: "singles"
                                tags: ["participant_position", "participant_data"]
                        1efb9cbb:
                            component: "object"
                            type: "telephone"
                            config:
                                style: "style-1"
                                label:
                                    es: "Móvil"
                                placeholder:
                                    es: "Móvil"
                                help:
                                    es: ""
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["participant_mobile", "participant_data"]
                        3b759fbb:
                            component: "object"
                            type: "telephone"
                            config:
                                style: "style-1"
                                label:
                                    es: "Fijo"
                                placeholder:
                                    es: "Fijo"
                                help:
                                    es: ""
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["participant_phone", "participant_data"]
            4bb4db28:
                component: "block"
                type: "12"
                config:
                    style: "style-1"
                children:
                    -
                        0d86b25e:
                            component: "object"
                            type: "text"
                            config:
                                style: "style-1"
                                content:
                                    es: "Foto"
                                type: "title"
                        cb66008e:
                            component: "object"
                            type: "image"
                            config:
                                style: "style-1"
                                label:
                                    es: "Foto"
                                placeholder:
                                    es: "Foto"
                                help:
                                    es: ""
                                required: false
                                tags: ["participant_avatar", "participant_data"]
            67019e4a:
                component: "block"
                type: "12"
                config:
                    style: "style-1"
                children:
                    -
                        0fe9cb97:
                            component: "object"
                            type: "text"
                            config:
                                style: "style-1"
                                content:
                                    es: "Empresa"
                                type: "title"
                        3ad4b72f:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Empresa"
                                placeholder:
                                    es: "Empresa"
                                help:
                                    es: ""
                                length: "250"
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["sheet_organization", "sheet_title", "sheet_data"]
                        9ef18c06:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Sitio Internet"
                                placeholder:
                                    es: "Sitio Internet"
                                help:
                                    es: ""
                                required: false
                                type: "text"
                                translatable: false
                                tags: ["sheet_data"]
                        93de093f:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Dirección"
                                placeholder:
                                    es: "Dirección"
                                help:
                                    es: ""
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["sheet_data"]
                        de66af5d:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Código postal"
                                placeholder:
                                    es: "Código postal"
                                help:
                                    es: ""
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["sheet_data"]
                        d224f0e7:
                            component: "object"
                            type: "editable-text"
                            config:
                                style: "style-1"
                                label:
                                    es: "Ciudad"
                                placeholder:
                                    es: "Ciudad"
                                help:
                                    es: ""
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["sheet_data"]
                        e801edd4:
                            component: "object"
                            type: "country"
                            config:
                                style: "style-1"
                                label:
                                    es: "Paìs"
                                placeholder:
                                    es: "Paìs"
                                help:
                                    es: ""
                                required: true
                                type: "text"
                                translatable: false
                                tags: ["sheet_data"]
