Proximum\Vimeet\Domain\Model\Type:
    event_spanish_type_fournisseur:
        __construct: ["@event_spanish"]
        position: 0
        package: '@package_spanish_event'
        registrationTemplate: '@registration_template_event_spanish'

    event_spanish_type_exposant:
        __construct: ["@event_spanish"]
        position: 1
        package: '@package_spanish_event'
        registrationTemplate: '@registration_template_event_spanish'

Proximum\Vimeet\Domain\Model\TypeTranslation:
    event_spanish_type_fournisseur_es:
        __construct: ['@event_spanish_type_fournisseur', 'es', "Exponente"]
    event_spanish_type_exposant_es:
        __construct: ['@event_spanish_type_exposant', 'es', "Inversor"]
