Proximum\Vimeet\Domain\Model\Tip\Tip:
    tip_sample:
        __construct:
            - 'sample'
            - true
            - true
            - true
            - <dateTime()>

Proximum\Vimeet\Domain\Model\Tip\TipTranslation:
    tip_translation_fr:
        __construct:
            - '@tip_sample'
            - <dateTime()>
            - 'title_fr'
            - 'fr'
            - 'content_fr'

Proximum\Vimeet\Domain\Model\Tip\Tip:
    tip_1:
        __construct:
            - "title"
            - true
            - true
            - true
            - ['@tip_translation_fr']
            - <dateTime()>