Proximum\Vimeet\Domain\Model\Tip\Tip:
    tip_sample:
        __construct:
            - 'tip_sample'
            - null
            - true
            - true
            - true
            - false
            - false
            - false
            - false
            - <dateTime()>
        types:
            - '@type_exposant'

Proximum\Vimeet\Domain\Model\Tip\TipTranslation:
    tip_translation_fr:
        __construct:
            - '@tip_sample'
            - <dateTime()>
            - 'tip_title_fr'
            - 'fr'
            - 'tip_content_fr'
